### PR TITLE
Redmine#7624: Reduce malloc() thread contention

### PR DESCRIPTION
**Pull request by jimis**
Changelog: Reduce malloc() thread contention on heavily loaded
cf-serverd, by not exiting early in the logging function, if no message
is to be printed. (Redmine #7624)

### CODE REVIEW

**Comment by kacfengine** [comment]
+1000!

I thought this was always the case actually. Now I feel guilty for doing all those debug prints!

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
Cherry-picked to 3.6.x and 3.7.x.

**Comment by jimis** [comment]
Oh, thanks for doing the cherry-pickery!

**Pull request merged**
