### PR TITLE
ENT-11526: Changed cf-apache systemd unit to reload configuration gracefully

### PR DESCRIPTION
**Pull request by craigcomstock**
apachectl graceful doesn't close currently open connections.

Ticket: ENT-11526
Changelog: title

with https://github.com/cfengine/masterfiles/pull/2864

### CODE REVIEW

**Review by nickanderson — APPROVED** [review]
I commented in another PR to the MPF for a similar change with concern about aync vs sync. 

I think this is probably OK in a systemd unit where generally management calls have async behavior anyway.

**Review by vpodzime — APPROVED** [review]
Nice! I'm surprised we didn't have this. Just make sure this is also updated in MPF, we still have the service files in two places, AFAIK.

**Review by larsewi — APPROVED** [review]

**Comment by craigcomstock** [comment]
had a typo in the service file of `@workdir` instead of required `@workdir@`. `@` at end was missing so service file didn't work properly, especially during upgrades and server restarts.

**Review by vpodzime — APPROVED** [review]
Still looks good to me :grin:

**Review by larsewi — APPROVED** [review]

**Comment by craigcomstock** [comment]
Will wait to cherry pick for a week or so to see how/if this improves our CI. Will set a reminder for myself for 2024-04-19.

**Pull request merged**
