### PR TITLE
Child should exit if parent is dead.

### PR DESCRIPTION
**Pull request by jimis**
To avoid stale processes when test fails, relevant ticket is Redmine#6907.

### CODE REVIEW

**Comment by kacfengine** [comment]
Unfortunately the child appears to hang inside the database code, so it never returns to that loop. This is still a good fix though, so feel free to merge, but we can't remove the escape hatch in the script that runs this test.

**Comment by jimis** [comment]
OK merging. Next thing I can think of is having a periodic SIGALRM checking if parent is dead.

BTW what do you mean by "escape hatch in the script"?

**Comment by kacfengine** [comment]
> BTW what do you mean by "escape hatch in the script"?

Oh right, I haven't merged that yet. Here: https://github.com/kacfengine/core/commit/7ef4017a17949eab943ae0a5bcc80107198e0efc

**Comment by jimis** [comment]
> Oh right, I haven't merged that yet. Here: kacfengine@7ef4017

Interesting, I think it's good enough for a test. Maybe some other time I can try different solutions on the HP-UX system, like alarm() or setsid() on the parent process.

**Comment by kacfengine** [comment]
Cool!

**Pull request merged**
