### PR TITLE
Fix Redmine #7094 and add acceptance test

### PR DESCRIPTION
**Pull request by worr**
This takes the basic test that @kacfengine added in Redmine #7094 and expands it into a proper acceptance test. On master, this seems to pass.

### CODE REVIEW

**Comment by worr** [comment]
I've updated this a bit to better reflect the discussion in the ticket.

**Comment by worr** [comment]
I've added a fix to this problem as well, now that I'm back from vacation

**Comment by kacfengine** [comment]
Thanks for locating the problem. I have added one small optimization in https://github.com/cfengine/core/pull/2183, I'll merge that one instead if it passes.

**Comment by kacfengine** [comment]
Worked nicely!

**Pull request merged**
