### PR TITLE
ENT-9340: adjust cf-support to work on exotic unices

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
many commands are not found on exotics, but at least all five exotic platforms generate a support tarball now :)

will work on ensuring at least some command works for most of the bits we are collecting on the various platforms.

**Comment by nickanderson** [comment]
Good work

**Comment by nickanderson** [comment]
Thank you

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics please. thanks!

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9173/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9173/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9173/

**Comment by craigcomstock** [comment]
failures in CI are acceptable for this change:
- ssh connection flaky
- solaris lmdb file format problem
- EINVAL in lmdb
- core dump creation in 08-cf-support.test not quite right for exotics: made follow up ticket for that: https://tracker.mender.io/browse/ENT-9786

**Review by Lex-2008 — APPROVED** [review]
Great work! Also serves as "Rosetta stone" of all system administration commands on these unixes :)

**Comment by craigcomstock** [comment]
> Great work! Also serves as "Rosetta stone" of all system administration commands on these unixes :)

I know! I definitely was thinking: how can we share this info? Oh! A blog post eh?! ;)

**Comment by craigcomstock** [comment]
merge to master might not be OK, if shellcheck is not present the check-local in misc for cf-support might fail.

retry, I think this will fail on build hosts that don't have shellcheck installed.

[Build Status](https://ci.cfengine.com/job/pr-pipeline/9177/)

**Pull request merged**
