### PR TITLE
ENT-5313 libntech: Added SeqStringReadFile() and SeqStringWriteFile()

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4509/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4509/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4509/

**Comment by olehermanse** [comment]
@cf-bottom jenkins again, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4515/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4515/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4515/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4522/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4522/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4522/

**Comment by olehermanse** [comment]
Cherry-pick:
https://github.com/cfengine/core/pull/4046

**Pull request merged**
