### PR TITLE
CF-2951: ps command can handle longer usernames (3.12)

### PR DESCRIPTION
**Pull request by olehermanse**
Increased it to 30 chars instead of 8

Changelog: title
(cherry picked from commit 3a05f707332fe91447c53022b437205979ce420b)

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @vpodzime can review this?

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by olehermanse** [comment]
@cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1957/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1957/

**Pull request merged**
