### PR TITLE
ENT-5406/master: Fixed selection of standard_services when used from non-default namespace

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4805/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4805/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4805/

**Comment by olehermanse** [comment]
@nickanderson I tested this manually, and it seems to have fixed that issue on Ubuntu 18 superhub :) 👏

**Comment by nickanderson** [comment]
This was already cherry-picked and is present in  3.12.4, 3.15.1, 3.16.0

**Pull request merged**
