### PR TITLE
On a badly configured host, hostname might return "(none)", and ...

### PR DESCRIPTION
**Pull request by jimis**
...thos parenthesis are erring the shell, so they need to be quoted.

### CODE REVIEW

**Comment by jimis** [comment]
This fixes ill-configured buildslaves failing spuriously.

**Comment by jimis** [comment]
@tzz that's what I was asking you on IRC, thanks for helping! :-)

**Comment by tzz** [comment]
cool!

**Comment by jimis** [comment]
Great, merging myself because of urgency!

**Pull request merged**
