### PR TITLE
ENT-3710 Improved management of secondary groups to avoid intermediary state failures (3.15.x)

### PR DESCRIPTION
**Pull request by craigcomstock**
Modify user promise secondary groups attribute handling to examine current state and set new state appropriately instead of clearing all secondary groups and then setting (workaround for SUSE issue).

Cherry picked manually due to lots of conflicts in the C code.

Based on https://github.com/cfengine/core/pull/4126

### CODE REVIEW

**Comment by craigcomstock** [comment]
The diff in cf-agent/verify_users_pam.c is bigger than an easy cherry-pick, so I have cherry picked the other commits for ENT-3710 to see how they fare in CI. Will look more tomorrow on this.

**Comment by craigcomstock** [comment]
Nicely, with the tests and without the C change we get failure in CI! :)

```
./17_users/unsafe/20_modify_user_secondary_groups.cf FAIL (UNEXPECTED FAILURE)
```

So working on a patch. Doesn't look so hard after all. Just has to be done manually as far as I can tell. In progress.

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5036/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5036/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5036/

**Pull request merged**
