### PR TITLE
ENT-7362: cf-serverd default bind

### PR DESCRIPTION
**Pull request by vpodzime**
Merge together:
https://github.com/cfengine/core/pull/4750
https://github.com/cfengine/masterfiles/pull/2041

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6944/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6944/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6944/

**Review by larsewi — DISMISSED** [review]
Good old bubble sort

**Comment by vpodzime** [comment]
> Alright, I triggered a build:
> 
> [Build Status](https://ci.cfengine.com//job/pr-pipeline/6944/)

Sigh..., random failure in a unit test. @cf-bottom one more round in jenkins on me, please! :beers:

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6946/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6946/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6946/

**Comment by vpodzime** [comment]
> Alright, I triggered a build:
> 
> [Build Status](https://ci.cfengine.com//job/pr-pipeline/6946/)
> 
> ****

For some reason these two tests fail on Ubuntu 20 (and Ubuntu 20 alone!):
./16_cf-serverd/serial/simple_copy_from_admit_localhost.cf.simple_copy_from_admit_localhost.cf
./16_cf-serverd/serial/simple_copy_from_deny_localhost.cf.simple_copy_from_deny_localhost.cf

**Comment by vpodzime** [comment]
> For some reason these two tests fail on Ubuntu 20 (and Ubuntu 20 alone!):

Probably related to cfengine/buildscripts#843

**Comment by vpodzime** [comment]
Actually, this is the problem:
```
jenkins@ip-172-31-38-226:~$ cat /etc/hosts
127.0.0.1 localhost localhost.localdomain
::1 localhost
jenkins@ip-172-31-38-226:~$ host ::1
1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa has no PTR record
jenkins@ip-172-31-38-226:~$ sudo vi /etc/hosts
jenkins@ip-172-31-38-226:~$ host ::1
1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa domain name pointer bullshit.
jenkins@ip-172-31-38-226:~$ cat /etc/hosts
127.0.0.1 localhost localhost.localdomain
::1 bullshit
```
IOW, Ubuntu 20 ignores `localhost` in */etc/hosts* and it doesn't know how to resolve `127.0.0.1` or `::1` to `localhost` using a reverse lookup.

**Comment by vpodzime** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6973/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6973/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6973/

**Review by larsewi — APPROVED** [review]
ACK

**Comment by vpodzime** [comment]
> Alright, I triggered a build:
> 
> [Build Status](https://ci.cfengine.com//job/pr-pipeline/6973/)
> 
> ****

Only an unrelated failure in *bootstrap-tests*.

**Comment by vpodzime** [comment]
build on exotics only: [Build Status](https://ci.cfengine.com/job/pr-pipeline/6975/)

**Pull request merged**
