### PR TITLE
More debug messages to detect possible blocking in cf-serverd main loop.

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by kacfengine** [comment]
What about that bug that you and Eddy discovered in the agent a while ago, where the descriptor would overflow ``FD_SETSIZE``? Perhaps you should put in a check for that as well. It could happen on a heavily loaded server, couldn't it?

**Comment by jimis** [comment]
IIRC here we select() only on one file descriptor, the one for the listening socket. So no risk of overflow.

**Comment by kacfengine** [comment]
But the file descriptor itself may still overflow ``FD_SETSIZE`` if there are generally many open descriptors in the server, which I assume there will be under load.

**Comment by kacfengine** [comment]
Cherry-picked to 3.6.x as well.

**Comment by kacfengine** [comment]
For clarity: ``FD_SETSIZE`` is a limit on how high the file descriptor number can be, not on how many file descriptors you can have in the set.

**Pull request merged**
