### PR TITLE
Use StringCopy instead of strcpy

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @vpodzime can review this?

**Comment by vpodzime** [comment]
```

**Comment by olehermanse** [comment]
@vpodzime yes, working on it.

**Comment by olehermanse** [comment]
@cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2129/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/2129/

**Comment by olehermanse** [comment]
This pull request **fixes 2 alerts** when merging 629f01906978cf88bcc56de3ce05eb4985c14c20 into 79be22bf2b3e1dd5d8f27f513c19128cbfc3da87 - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-1799a093f5764e4618fbfd3b21ac3d5633ec5688)

**fixed alerts:**

* 2 for Unbounded write

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
