### PR TITLE
Iprange refactor

### PR DESCRIPTION
**Pull request by jimis**
Supersedes pull request #2529.

### CODE REVIEW

**Comment by jimis** [comment]
The change in `iprange()` is that it no longer matches on VIPADDRESS, I'm almost sure VIPADDRESS is included in the address returned from `EvalContextGetIpAddresses(ctx)`.

**Comment by jimis** [comment]
trigger build

**Comment by tzz** [comment]
I disagree with the removal of `FnReturnContextTrue` but the main code is good.

**Comment by jimis** [comment]
On Fri, Jun 24, 2016 at 4:16 PM, Ted Zlatanov <notifications@github.com>
wrote:

> I disagree with the removal of FnReturnContextTrue
>

I did that to get rid of the warning, it was only used in the old
`iprange()` and `FnReturnContext(true)` is used all over the place. I have
no preference between them, I just wanted to use one form consistently.

**Comment by tzz** [comment]
Oh, I see. Cool.

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
Merging then, thanks for the initial code and the review @tzz. Would you be able to submit a documentation pull request?

**Pull request merged**
