### PR TITLE
CFE-3460: Variables are now expanded in promise block attributes

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
Will be tested here: https://github.com/cfengine/core/pull/4346

**Comment by olehermanse** [comment]
@cf-bottom jenkins, just in case.

**Review by vpodzime — APPROVED** [review]
ACK

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5768/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5768/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5768/

**Comment by olehermanse** [comment]
It compiles, ship it.

**Pull request merged**
