### PR TITLE
CFE-2067:  Removed programming error in handling of process_count body

### PR DESCRIPTION
**Pull request by olehermanse**
Previously, having a failing function call inside in_range_define
or out_of_range_define would cause a programming error when
trying to define that as a class. Fixed it by detecting the
case, printing a normal error, and skipping defining the class.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2372/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2372/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2372/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2382/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2382/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2382/

**Comment by olehermanse** [comment]
@nickanderson What do you think about the test case here?

**Pull request merged**
