### PR TITLE
ENT-7048 mark flakey exotics tests

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
started a jenkins build focused on solaris 11 sparc: [Build Status](https://ci.cfengine.com/job/pr-pipeline/6488/)

**Comment by craigcomstock** [comment]
Let's see what happens if the test always fails but is marked flakey, just to be sure of that behavior and result in jenkins.

[Build Status](https://ci.cfengine.com/job/pr-pipeline/6500/)

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics

**Comment by craigcomstock** [comment]
oops, should have run `cf-promises` on the os_version_major.cf first. :p try again please @cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6504/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6504/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6504/

**Review by nickanderson — APPROVED** [review]

**Pull request merged**
