### PR TITLE
CFE-3099: Allow @ character in keys of classic array defined by module protocol (master)

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @vpodzime can review this?

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by nickanderson** [comment]
cf-bottom has a hangover or something. not working today.

So manually triggered PR build in jenkins;

 Build #2342

**Pull request merged**
