### PR TITLE
ENT-7718: No longer possible to undefine reserved hard classes

### PR DESCRIPTION
**Pull request by larsewi**
Fixed a bug allowing you to undefine a hard classes.

### CODE REVIEW

**Comment by larsewi** [comment]
@cf-bottom Jenkins please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7444/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7444/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7444/

**Review by vpodzime — COMMENTED** [review]
Please replace *cancel* with *undefine* in the commit message. Looks good to me otherwise. Nice fix! :grin:

**Review by olehermanse — APPROVED** [review]

**Review by nickanderson — APPROVED** [review]

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
