### PR TITLE
[3.12.x] SSL retry

### PR DESCRIPTION
**Pull request by vpodzime**

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2569/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2569/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2569/

**Comment by vpodzime** [comment]
> This pull request **introduces 2 alerts** when merging [221ce0f](https://github.com/cfengine/core/commit/221ce0f8e0dd7e760b0d540e329e4f49dd27d899) into [0c967fa](https://github.com/cfengine/core/commit/0c967fa6f93a5bbbbcb4f8715092aac5a1718127) - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-8b1d1654c2026687e81b86d5d27cd081a3060ab5)

I don't think so.

**Comment by vpodzime** [comment]
> **Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2569/

All green, deployment tests aborted.

**Pull request merged**
