### PR TITLE
masterfiles-stage: Added alternate global directory for cfbs build

### PR DESCRIPTION
**Pull request by olehermanse**
Merge together:
https://github.com/cfengine/nova/pull/2276

### CODE REVIEW

**Review by vpodzime — APPROVED** [review]
ACK

**Review by larsewi — APPROVED** [review]

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/11048/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/11048/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-11048/

**Review by nickanderson — APPROVED** [review]

**Review by craigcomstock — APPROVED** [review]

**Comment by craigcomstock** [comment]
unstable build is truly that. Good to go AFAICT.

**Pull request merged**
