### PR TITLE
ENT-11771: Fixed missing cf.events.dll in acceptance tests on windows

### PR DESCRIPTION
**Pull request by craigcomstock**
- Improve and re-enable windows acceptance test workflow
- Adjusted 3.18.x tags for cfengine package
- GH Actions macOS: Fixed installation and PATH for libtool and autoconf
- GH Actions macOS: Use brew --prefix to locate LMDB, OpenSSL, and pcre

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @larsewi can review this?

**Comment by craigcomstock** [comment]
A fix is in the works in master, after that is green I will cherry pick it back with these changes to make things "clean".

https://github.com/cfengine/core/pull/5509

**Comment by craigcomstock** [comment]
will likely abandon this PR as I fixed something in master that should "just work": see https://github.com/cfengine/core/pull/5513

**Comment by craigcomstock** [comment]
prefer https://github.com/cfengine/core/pull/5518

**Pull request closed without merging**
