### PR TITLE
Use F4 as RSA exponent - it's common practice.

### PR DESCRIPTION
**Pull request by jimis**
Redmine 7053. Thanks to Tomáš Chvátal for submitting the patch.

### CODE REVIEW

**Comment by kacfengine** [comment]
+1!

**Comment by kacfengine** [comment]
trigger build

**Comment by ncharles** [comment]
won't this break compatibility between new server and older agent ?

**Comment by kacfengine** [comment]
The build is green, and it looks good from my side.

I have no opinion on @ncharles's question, I'll let @jimis address that.

**Comment by jimis** [comment]
@ncharles no it shouldn't break anything, the only line that changes is in cf-key's key generation routine, the rest are tests. All functionality should remain unchanged.

I'm merging this in master, it's harmless so it might go in 3.6.x later on, please let me know if anyone finds performance issues - I believe this is the only possible regression.

**Pull request merged**
