### PR TITLE
Replaced 2 more occurences of gmtime with gmtime_r

### PR DESCRIPTION
**Pull request by olehermanse**
Reported by LGTM:
https://lgtm.com/rules/2154840805/

Signed-off-by: Ole Herman Schumacher Elgesem <ole.elgesem@northern.tech>

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1077/)

https://ci.cfengine.com/job/pr-pipeline/1077/

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1088/)

https://ci.cfengine.com/job/pr-pipeline/1088/

**Pull request merged**
