### PR TITLE
CFE-3434: Custom promise locking and ifelapsed

### PR DESCRIPTION
**Pull request by vpodzime**
steps:
- [x] shuffle validation and unresolved variables check
- [x] include container attributes in promise hash
- [x] enable promise locking for custom promises
- [x] acceptance test(s)

Merge together:
https://github.com/cfengine/core/pull/4905
https://github.com/cfengine/masterfiles/pull/2223

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7479/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7479/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7479/

**Review by larsewi — APPROVED** [review]
ACK

**Review by olehermanse — APPROVED** [review]
Great, thanks!

**Pull request merged**
