### PR TITLE
ENT-10997: Skip failing tests on Debian 12 (3.18.x)

### PR DESCRIPTION
**Pull request by larsewi**
Merge together:
* https://github.com/cfengine/buildscripts/pull/1356

### CODE REVIEW

**Comment by larsewi** [comment]
@cf-bottom Jenkins please :)

**Comment by larsewi** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/10227/)

**Review by craigcomstock — APPROVED** [review]

**Comment by larsewi** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/10238/)

**Comment by larsewi** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/10240/)

**Pull request merged**
