### PR TITLE
Failsafe bodies/bundles must be unique due to def.json problem

### PR DESCRIPTION
**Pull request by basvandervlies**
* https://dev.cfengine.com/issues/7954

### CODE REVIEW

**Comment by basvandervlies** [comment]
ping?

**Comment by nickanderson** [comment]
trigger build

**Comment by nickanderson** [comment]
trigger build

**Comment by nickanderson** [comment]
trigger build

**Comment by nickanderson** [comment]
Looks good, I didn’t see any failures from the build pipeline.

**Pull request merged**
