### PR TITLE
Add: Test that comments on vars promises are emitted in verbose output

### PR DESCRIPTION
**Pull request by nickanderson**
Jira #CFE-2442

### CODE REVIEW

**Comment by nickanderson** [comment]
Currently soft failing on 3.9.0

```
> $ cf-agent -V
CFEngine Core 3.9.0
> $ cf-agent -KIf ./vars_comments_emitted_in_verbose.cf -DAUTO
R: test description: Test that comments on variables are emitted in verbose output.
R: /home/nickanderson/CFEngine/core/tests/acceptance/01_vars/01_basic/./../../dcs.cf.sub SFAIL/CFE-2442
R: /home/nickanderson/CFEngine/core/tests/acceptance/01_vars/01_basic/./vars_comments_emitted_in_verbose.cf FAIL
```

**Comment by jimis** [comment]
do we really want to print all comments? We have handles for looking in the verbose output. I never really got the point of the "comment" attribute; But who am I to talk, I'm still struggling with "meta" ...

**Comment by jimis** [comment]
Quoting @nickanderson: 
> if necessry i can find a video where Mark says "comments come along in the logs"

So merging.

**Comment by jimis** [comment]
BTW @nickanderson it seems you are loving your `.cf.sub` executions. How about modifying `testall` to add output checking as a new feature? ;-) I must write a ticket for that ... TODO.

**Pull request merged**
