### PR TITLE
Removed unused functions from libcfnet/misc.c

### PR DESCRIPTION
**Pull request by KotzaBoss**
Request for this PR can be found [here](https://github.com/cfengine/core/pull/4579#discussion_r615307517)

Ticket: None
Changelog: None

### CODE REVIEW

**Comment by KotzaBoss** [comment]
Should the commented [function](https://github.com/cfengine/core/pull/4607/files#diff-73cce9856832db492eb6180fdc813c107c8fab0318115bddd3c8a48b3df43361L124) be removed too?

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6462/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6462/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6462/

**Review by olehermanse — APPROVED** [review]
Thanks!

**Comment by olehermanse** [comment]
> Should the commented function be removed too?

@KotzaBoss yes, feel free to open another PR doing that.

**Pull request merged**
