### PR TITLE
Replaced assert() with nt_static_assert() where possible

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom please test this in jenkins, with exotics.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5760/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5760/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5760/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5761/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5761/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5761/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5766/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5766/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5766/

**Review by vpodzime — APPROVED** [review]
ACK

**Comment by olehermanse** [comment]
Cherry-pick (only 1 of 4): https://github.com/cfengine/core/pull/4356

**Pull request merged**
