### PR TITLE
Add: test classic template wont render cf_null with absent data container

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
This test fails (at least on 3.9.0) softly.

```
> $ cf-agent -KIf ./classic_template_wont_render_cf_null_with_empty_datacontainer.cf -DAUTO
R: test description: Test that classic templates will not render
			     cf_null when dereferencing an absent data
                             container.
R: /home/nickanderson/CFEngine/core/tests/acceptance/10_files/templating/./../../dcs.cf.sub SFAIL/CFE-2422
    info: Edit file '/tmp/TEST.cfengine'
R: template_file
R: /home/nickanderson/CFEngine/core/tests/acceptance/10_files/templating/./classic_template_wont_render_cf_null_with_empty_datacontainer.cf FAIL
```

**Comment by jimis** [comment]
rebase for Travis?

**Comment by nickanderson** [comment]
freebased

**Comment by jimis** [comment]
red

**Comment by nickanderson** [comment]
NOT RED

**Comment by jimis** [comment]
THANK YOU

**Pull request merged**
