### PR TITLE
ENT-7340 Fixup SELinux configuration for RHEL 8 hub

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-7340
Changelog: title

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please, thanks.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6800/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6800/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6800/

**Comment by craigcomstock** [comment]
rhel8 failed with

```
14:44:55 cfengine-enterprise.te:183:ERROR 'permission noatsecure is not defined for class process' at token ';' on line 3102:
14:44:55 allow cfengine_execd_t cfengine_agent_t:process { noatsecure rlimitinh siginh transition };
14:44:55 type_transition cfengine_execd_t cfengine_agent_exec_t:process cfengine_agent_t;
14:44:55 cfengine-enterprise.te:183:ERROR 'permission rlimitinh is not defined for class process' at token ';' on line 3102:
14:44:55 allow cfengine_execd_t cfengine_agent_t:process { noatsecure rlimitinh siginh transition };
14:44:55 type_transition cfengine_execd_t cfengine_agent_exec_t:process cfengine_agent_t;
14:44:55 cfengine-enterprise.te:183:ERROR 'permission siginh is not defined for class process' at token ';' on line 3102:
14:44:55 allow cfengine_execd_t cfengine_agent_t:process { noatsecure rlimitinh siginh transition };
14:44:55 type_transition cfengine_execd_t cfengine_agent_exec_t:process cfengine_agent_t;
14:44:55 cfengine-enterprise.te:214:ERROR 'unknown type ifconfig_t' at token ';' on line 3133:
14:44:55 allow cfengine_execd_t hostname_exec_t:file getattr;
14:44:55 allow cfengine_execd_t ifconfig_t:process { noatsecure rlimitinh siginh };
14:44:55 /usr/bin/checkmodule:  error(s) encountered while parsing configuration
```

Will try to fix and build locally first if I can.

**Comment by craigcomstock** [comment]
trying again, just redhat_8 builds: 
[Build Status](https://ci.cfengine.com/job/pr-pipeline/6801/)

**Comment by vpodzime** [comment]
Tested manually with this changes. Everything seems to be working fine, the only violated rules are these:
```
# ausearch -m AVC -ts boot | audit2allow | grep cfengine
#============= cfengine_execd_t ==============
allow cfengine_execd_t cfengine_agent_t:process { noatsecure rlimitinh siginh };
allow cfengine_execd_t ifconfig_t:process { noatsecure rlimitinh siginh };
#============= cfengine_monitord_t ==============
allow cfengine_monitord_t ifconfig_t:process { noatsecure rlimitinh siginh };
#============= cfengine_serverd_t ==============
allow cfengine_serverd_t ifconfig_t:process { noatsecure rlimitinh siginh };
allow ifconfig_t cfengine_execd_t:unix_stream_socket { read write };
allow ifconfig_t cfengine_serverd_t:unix_stream_socket { read write };
```
which I believe should all be enforced and not allowed.

**Review by vpodzime — APPROVED** [review]
Seems to work fine. :heavy_check_mark:

**Review by craigcomstock — COMMENTED** [review]
Cool! Looks good to me. :) I can't approve though ;)

**Review by olehermanse — APPROVED** [review]

**Pull request merged**
