### PR TITLE
Updated libntech to master (3.21)

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: none
Changelog: none

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @vpodzime can review this?

**Comment by vpodzime** [comment]
I think we also need to backport https://github.com/cfengine/nova/pull/2044

**Comment by craigcomstock** [comment]
no need for this.

**Comment by olehermanse** [comment]
Round 2: https://github.com/cfengine/core/pull/5250

**Pull request closed without merging**
