### PR TITLE
CFE-2406: cf-serverd should reload def.json when reloading policy

### PR DESCRIPTION
**Pull request by tzz**
First attempt to fix this issue. @nickanderson please test.

### CODE REVIEW

**Comment by nickanderson** [comment]
maybe @kacf can look at this.

I tried to build it and failed.

```
cf-serverd-functions.c: In function 'CheckFileChanges':
cf-serverd-functions.c:452:13: error: implicit declaration of function 'LoadAugments' [-Werror=implicit-function-declaration]
             LoadAugments(ctx, config);
             ^
cc1: some warnings being treated as errors
make[2]: *** [cf-serverd-functions.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by kacf** [comment]
`LoadAugments` is not exported outside of `generic_agent.c`, but it could easily be. Add a function prototype in `generic_agent.h` (take the function signature from the c file, add it to the h file and add `;`).

**Comment by nickanderson** [comment]
ping @jimis

**Comment by tzz** [comment]
@jimis tiny and urgent bug fix. Please merge ASAP.

**Comment by jimis** [comment]
Thanks, merging.

**Comment by jimis** [comment]
Err, I just noticed that this one is not rebased, thus Travis didn't test it. @tzz can you rebase?

**Comment by jimis** [comment]
And please squash it alltogether, since some commits are not even building right.

**Comment by jimis** [comment]
What is not clear if it's addressed, is auto-detection that def.json has changed. I think it /should/ work since a change in def.json /should/ alter cf_promises_validated. Right? :-) 

The acceptance test is indeed hard, so I will trust your manual testing @tzz and @nickanderson.

**Comment by tzz** [comment]
OK; rebased.

@jimis I agree the `cf_promises_validated` mechanism is enough.

**Pull request merged**
