### PR TITLE
Fixes to readenvfile() readcsv() readfile() (CFE-2657, CFE-2656)

### PR DESCRIPTION
**Pull request by olehermanse**
`readfile()`, `readjson()`, `readyaml()`, `readenvfile()` and `readcsv()` now all follow the same syntax: 
 * First parameter is file path, and required
 * Second parameter is max bytes to read, and optional.

Fixed an issue where csv and env parser would output bogus error messages and destroy data when the byte limit was reached.

Need to update docs and add more tests.

https://tracker.mender.io/browse/CFE-2657
https://tracker.mender.io/browse/CFE-2656

### CODE REVIEW

**Comment by olehermanse** [comment]
@jimis @nickanderson @kacf Please review.

**Comment by jimis** [comment]
@tzz what do you think about the syntax change?

**Comment by tzz** [comment]
It's lovely :)

**Comment by olehermanse** [comment]
@jimis @nickanderson I think at least 2 out of the 3 commits should be cherry-picked to 3.10.x. Maybe not the argument changes, but the other 2 are bug fix / error messages. See: https://tracker.mender.io/browse/CFE-2657

**Comment by jimis** [comment]
Yes, as I have noted in the ticket the bug-fix should be cherry-picked. I'll do it now and close the ticket, thanks!

**Pull request merged**
