### PR TITLE
Implement assertion when mixing cursors with other transactions.

### PR DESCRIPTION
**Pull request by kacfengine**
This has been a problem in the past that often goes unnoticed and can
lead to database corruption or hangs.

### CODE REVIEW

**Comment by kacfengine** [comment]
For @jimis.

@basvandervlies: The result of my late night hacking after arguing with Jimis at CfgMgmtCamp! :-)

**Comment by basvandervlies** [comment]
@kacfengine belgium beer did its work ;-D!

**Comment by jimis** [comment]
+1, merging, that doesn't mean you won though... ;-)

**Comment by kacfengine** [comment]
The battle goes on!

**Pull request merged**
