### PR TITLE
Added test for GLOB_BRACE with findfiles()

### PR DESCRIPTION
**Pull request by nickanderson**
Mergetogether:
https://github.com/cfengine/libntech/pull/64

Ticket: CFE-3292
Changelog: None

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @vpodzime can review this?

**Comment by olehermanse** [comment]
@nickanderson can you add this as an expected failure until we have time to work on it?

**Comment by nickanderson** [comment]
> @nickanderson can you add this as an expected failure until we have time to work on it?

@olehermanse, aaas yooooou wiiiiiiiiish

```
> $ diff -u tests/acceptance/01_vars/02_functions/findfiles.cf tests/acceptance/01_vars/02_functions/findfiles-GLOB_BRACE.cf       
--- tests/acceptance/01_vars/02_functions/findfiles.cf  2020-04-15 10:09:57.219322655 -0500
+++ tests/acceptance/01_vars/02_functions/findfiles-GLOB_BRACE.cf       2020-04-15 10:09:57.247322828 -0500
@@ -40,8 +40,15 @@
 bundle agent test
 {
   meta:
-      "test_suppress_fail" string => "windows",
-        meta => { "redmine4730" };
+      "description" -> { "CFE-3292" }
+        string => "Test that findfiles() works as expected.";
+
+      #"test_suppress_fail" string => "windows",
+      #  meta => { "redmine4730" };
+      # This test should be merged with findfiles.cf when it's fixed.
+      # In order to soft-fail it as requested, I had to strip it to a separate-test
+      "test_soft_fail" string => "windows",
+        meta => { "CFE-3292" };
 
   vars:
       "patterns[a]" string => "$(G.testdir)/?";
@@ -52,6 +59,7 @@
       "patterns[relative_path_1]" string => "./*";
       "patterns[relative_path_2]" string => "**";
       "patterns[relative_path_3]" string => "../**";
+      "patterns[GLOB_BRACE]" string => "$(G.testdir)/{a,bc}";
 
     !windows::
       "patterns[f]" string => "$(G.testdir)/tu/\\*";
@@ -86,6 +94,7 @@
       "expected[c]" string => "$(G.testdir)/d/e,$(G.testdir)/g/h";
       "expected[d]" string => "$(G.testdir)/a,$(G.testdir)/bc";
       "expected[e]" string => "";
+      "expected[GLOB_BRACE]" string => "$(G.testdir)/a,$(G.testdir)/bc";
 
     !windows::
       "expected[f]" string => "$(G.testdir)/tu/*";

```

**Comment by nickanderson** [comment]
> Looks good to me. But if we have other tests for globs, I'd suggest this test to be very short and specific to the `GLOB_BRACE`-related cases.

https://www.youtube.com/watch?v=88svMqo3ZEk&t=8s

**Comment by nickanderson** [comment]
Squashed.

**Pull request merged**
