### PR TITLE
ENT-6935 Disable testall selftest

### PR DESCRIPTION
**Pull request by craigcomstock**
Getting this selftest working in CI is proving difficult.
Remove for now in preference for green builds.

Ticket: ENT-6935
Changelog: title

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6407/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6407/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6407/

**Review by vpodzime — DISMISSED** [review]
ACK

**Comment by vpodzime** [comment]
I think we can merge this and then revert, hopefully soon. :crossed_fingers:

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6409/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6409/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6409/

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
