### PR TITLE
WIP ENT-4653 fixed ifelse() to return fallback when unresolved vars

### PR DESCRIPTION
**Pull request by craigcomstock**
Root cause is that if there is only one iteration wheel remaining and
that wheel has an unresolved value PromiseIteratorNext() was returning
false which cause ExpandPromiseAndDo() to not evaluate the ifelse
function and not assign the default value in the ifelse() expression.

Changelog: title
Ticket: ENT-4653

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5012/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5012/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5012/

**Comment by craigcomstock** [comment]
This PR actually looks quite good. My fix for skipping ./00_basics/01_compiler/800.cf.800.cf on pureos broken debian build platforms. Other than that it seems all tests are passing? I will work on confirming this. If it is looking good I will do the big cleanup of debug logging and squashing.

**Comment by craigcomstock** [comment]
@cf-bottom jenkins exotics thanks.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5030/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5030/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5030/

**Comment by craigcomstock** [comment]
Closing this PR in preference for a simplified one without all the debug logging and such. https://github.com/cfengine/core/pull/4149

**Pull request closed without merging**
