### PR TITLE
[test/dontmerge] unblock Solaris

### PR DESCRIPTION
**Pull request by Lex-2008**
This temporary reverts commit ef86e711843798157b24d3d38b484a9aef67baf9.

### CODE REVIEW

**Comment by hughmcmaster** [comment]
Hi @Lex-2008, what's the reasoning behind this reversion MR?

**Comment by Lex-2008** [comment]
hi @hughmcmaster, issue is that currently our master branch fails to build Solaris, with errors like this:
```
files_editxml.c: In function 'DeleteTextInNode':
files_editxml.c:1659:9: error: implicit declaration of function 'xmlFirstElementChild' [-Werror=implicit-function-declaration]
         elemnode = xmlFirstElementChild(docnode);
         ^
```
and this:
```
xml-c14nize.c: In function 'xmlC14nizeFile':
xml-c14nize.c:25:37: error: 'XML_C14N_1_0' undeclared (first use in this function)
     if (xmlC14NDocSaveTo(doc, NULL, XML_C14N_1_0, 0, true, out) < 0)
                                     ^
xml-c14nize.c:25:37: note: each undeclared identifier is reported only once for each function it appears in
Makefile:706: recipe for target 'xml_c14nize-xml-c14nize.o' failed
gmake[4]: *** [xml_c14nize-xml-c14nize.o] Error 1
```
I created this PR for two reasons:
a) to confirm that it's indeed caused by this commit
b) to unblock testing some other work that I'm doing on Solaris (https://github.com/cfengine/buildscripts/pull/1107, if you're interested)

I'll work on a proper fix a bit later. No, we're not planning to revert your commit for real :) I should've marked this PR as test/dontmerge from the beginning, sorry for the confusion!

**Comment by hughmcmaster** [comment]
Thanks for clarifying.

It would be good to know what version of libxml2 is available on your Solaris 10 system.

`xmlFirstChildElement` requires 2.7.3 at a minimum.

My Solaris 10 test VM had libxml 2.6.23 – too old to have the needed symbol. But once I installed a more recent version, it was fine.

I can't check your Solaris logs, since I get 403 access denied (same with your CI builds, unless using the GitHub checks tab).

Functionally, there is little difference pre-patch and post-patch. If it is a version issue, I'd recommend adding a minimum version.

**Comment by vpodzime** [comment]
> It would be good to know what version of libxml2 is available on your Solaris 10 system.

We build _libxml2_ for CFEngine on our build machines (including the Solaris 10 ones) in our build root. But for some reason, the pkg-config files for libxml are available on the Solaris 10 machines in the system. And they are picked up and preferred over the definitions using _libxml_ from our build root.

**Comment by vpodzime** [comment]
Thanks for the tips, @hughmcmaster! However, I think the easiest thing will be to remove the problematic `.pc` files from our Solaris hosts. We don't need them there.

**Comment by hughmcmaster** [comment]
That should work too!

**Comment by Lex-2008** [comment]
Indeed, our Solaris 10 build machines have quite a lot of *.pc files in `/usr/lib/pkgconfig`.

Thanks @hughmcmaster and @vpodzime for your input, I managed to get a green build by setting relevant `PKG_CONFIG_` variable - see https://github.com/cfengine/buildscripts/pull/1109

Just deleting a `*.pc` file might be simple, but fragile solution - what if we migrate to another Solaris VM in the future?

FWIW, pkg-config on Solaris 10 doesn't use `PKG_CONFIG_LIBDIR` env variable, only `PKG_CONFIG_PATH`.

Oh, and also to answer @hughmcmaster's question: yes, our Solaris build machine also has libxml version 2.6.23 installed.

**Pull request closed without merging**
