### PR TITLE
libcfnet: bandwidth limit on the network

### PR DESCRIPTION
**Pull request by xrg**
This time, bwlimit is implemented with integer arithmetics only. It is written as a separate function, applied both to classic SendStream and TLS methods.

### CODE REVIEW

**Comment by jimis** [comment]
I'll review this for 3.7 inclusion. @xrg let me know if you have any updates sitting in your local branches.

**Comment by xrg** [comment]
���� ��� 20 ��� 2015 6:56:16 �.�. Dimitrios Apostolou ������:
> I'll review this for 3.7 inclusion. @xrg let me know if you have any updates
> sitting in your local branches.
> 

Not for the "bwlimit" patch.  AFAICR

But the terrible lag for reviewing that patch has made the "future-syntax" one 
a must-have.

**Comment by jimis** [comment]
On Fri, Mar 20, 2015 at 3:32 PM, Panos <notifications@github.com> wrote:

> Not for the "bwlimit" patch. AFAICR
>
> But the terrible lag for reviewing that patch has made the "future-syntax"
> one
> a must-have.
>

Can you update and point me to the future-syntax patch? I would like to see
such functionality included soon, and there are active discussions
regarding such a feature.

**Comment by kacfengine** [comment]
Superseded by #2167.

**Pull request closed without merging**
