### PR TITLE
CFE-2824: Eliminated noisy error message - 3.12.x

### PR DESCRIPTION
**Pull request by karlhto**

### CODE REVIEW

**Comment by karlhto** [comment]
@cf-bottom Please trigger a jenkins build.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com/job/pr-pipeline/811/)

https://ci.cfengine.com/job/pr-pipeline/811/

**Comment by karlhto** [comment]
@cf-bottom Please trigger a jenkins build for this PR!

**Comment by karlhto** [comment]
@cf-bottom Please trigger a jenkins build.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com/job/pr-pipeline/814/)

https://ci.cfengine.com/job/pr-pipeline/814/

**Comment by olehermanse** [comment]
@cf-bottom Please trigger a build for this in jenkins :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com/job/pr-pipeline/817/)

https://ci.cfengine.com/job/pr-pipeline/817/

**Comment by karlhto** [comment]
This build is passing.
[Build Status](https://ci.cfengine.com/job/pr-pipeline/819/)

**Pull request merged**
