### PR TITLE
Redmine#7765: Log INFO messages to Mission Portal even if not logging…

### PR DESCRIPTION
**Pull request by jimis**
… to console nor syslog.

### CODE REVIEW

**Comment by jimis** [comment]
This is not good:
1. it fails in `logging_timestamp_test.c` and I can't figure out why!
2. I'm using an ugly `#ifdef` to hide enterprise-specific code. I have no clue if this is correct, but it's surely ugly. Do you know any valid way to distinguish inside libpromises whether the enterprise plugin is loaded?

**Comment by pasinskim** [comment]
@jimis go home. One way of doing this migt be moving this stuff to separate
function and create enterprise stub. Then in core you can do nothing and
implement needed thing in enterprise.
I don't believe I am replaying at 12:30...

**Comment by jimis** [comment]
This is ridiculous; quick, somebody erase the timestamps!

**Comment by kacfengine** [comment]
@pasinskim's suggestion is the correct approach. You can't use an ifdef, since Community and Enterprise are the same binary.

**Comment by kacfengine** [comment]
But isn't it much easier to simply avoid the optimization for INFO messages? I mean, *by far* the greatest bottleneck here are the DEBUG messages, and both those and VERBOSE messages will still be covered by the optimization.

**Comment by jimis** [comment]
Kristian, I knew the ifdef wouldn't work, but I couldn't find some global variable either when the enterprise plugin is loaded. Are you aware of any?

I'll probably go with moving this code in Enterprise, but it's more overhead than I had hoped for.

> But isn't it much easier to simply avoid the optimization for INFO messages?

I can't just arbitrarily do "if INFO then always run hook", this is a generic logging library.

**Comment by jimis** [comment]
trigger build

**Pull request merged**
