### PR TITLE
CFE-3649: Fix failing test os_version_major.cf for Redhat 5

### PR DESCRIPTION
**Pull request by larsewi**
Ticket: CFE-3649
Changelog: None
Signed-off-by: larsewi <lars.erik.wik@northern.tech>

### CODE REVIEW

**Comment by larsewi** [comment]
@cf-bottom Jenkins with exotics please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6506/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6506/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6506/

**Review by vpodzime — APPROVED** [review]
Looks good to me.

**Comment by larsewi** [comment]
Updated commit message with ticket number

**Comment by larsewi** [comment]
@cf-bottom Jenkins with exotics please !

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6515/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6515/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6515/

**Review by craigcomstock — APPROVED** [review]
looks good :)

**Comment by larsewi** [comment]
[Pull 4634](https://github.com/cfengine/core/pull/4634) should fix this issue. So I think we can close this one. Any objections?

**Comment by craigcomstock** [comment]
> [Pull 4634](https://github.com/cfengine/core/pull/4634) should fix this issue. So I think we can close this one. Any objections?

@larsewi agreed. 🍕

**Pull request closed without merging**
