### PR TITLE
Improve ifelse() test

### PR DESCRIPTION
**Pull request by tzz**
this is partly for https://tracker.mender.io/browse/CFE-2357 but also just to clean up the test

### CODE REVIEW

**Comment by jimis** [comment]
-1 for adding JSON file
+2 for removing the "secondpass" nightmare

trigger build

**Comment by tzz** [comment]
@jimis so you're positive about it? ;)

**Comment by jimis** [comment]
Indeed `1>0` :-)

**Comment by jimis** [comment]
Merged, thanks.

**Pull request merged**
