### PR TITLE
ENT-6398: Audit mode was renamed to simulate mode

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Review by nickanderson — APPROVED** [review]
simulate_safe kinda ugly, perhaps simulation_safe but no strong objection

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5926/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5926/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5926/

**Comment by olehermanse** [comment]
> simulate_safe kinda ugly, perhaps simulation_safe but no strong objection

@nickanderson I named it like that since it refers to `simulate mode`. There is nothing called `simulation mode`. `safe_in_simulate_mode`?

Personally I would prefer something more generic and straight forward, like `safe`.

**Comment by nickanderson** [comment]
i think simulate_safe is better than simply safe, its more descriptive.

**Pull request merged**
