### PR TITLE
Expand all variables in data/list references

### PR DESCRIPTION
**Pull request by vpodzime**
Variables in data/list references should be expanded, not only if
they are in place of the data/list name but also in field name or
index.

Ticket: CFE-3299
Changelog: Expand variables in data/list references

TODO:
- [x] fix introduced memory leak
- [x] ~add a test for `@(container.${slist_var_field})`~ (I thought we supported the `data.field` syntax)

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom jenkins with exotics, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5561/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5561/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5561/

**Comment by vpodzime** [comment]
@cf-bottom jenkins with exotics, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5563/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5563/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5563/

**Review by olehermanse — APPROVED** [review]
🚀

**Pull request merged**
