### PR TITLE
ENT-4313: Fixed memory leak in filesexist function

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@vpodzime your favorite function!

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1727/)

https://ci.cfengine.com/job/pr-pipeline/1727/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1737/)

https://ci.cfengine.com/job/pr-pipeline/1737/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1749/)

https://ci.cfengine.com/job/pr-pipeline/1749/

**Comment by olehermanse** [comment]
Cherry-picks:
https://github.com/cfengine/core/pull/3454
https://github.com/cfengine/core/pull/3455

**Pull request merged**
