### PR TITLE
ENT-5986 LMDB files are now created with correct permissions (3.12.x)

### PR DESCRIPTION
**Pull request by craigcomstock**
merge with:
https://github.com/cfengine/masterfiles/pull/1766

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5178/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5178/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5178/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5205/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5205/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5205/

**Comment by craigcomstock** [comment]
closing this one in preference for a cherry-pick here: https://github.com/cfengine/core/pull/4208

**Pull request closed without merging**
