### PR TITLE
Bumped libntech to master (3.24.x)

### PR DESCRIPTION
**Pull request by larsewi**
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

### CODE REVIEW

**Comment by larsewi** [comment]
@cf-bottom Jenkins please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/11446/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/11446/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-11446/

**Review by craigcomstock — APPROVED** [review]
seems reasonable :)

Is the bump for a particular purpose or reason? What initiated the bump?

**Comment by larsewi** [comment]
> Is the bump for a particular purpose or reason? What initiated the bump?

No particular reason @craigcomstock . Just though it's nice to keep these branches somewhat up to date with master. Can ofc wait til after release or not merge them at all.

**Comment by craigcomstock** [comment]
> > Is the bump for a particular purpose or reason? What initiated the bump?
> 
> No particular reason @craigcomstock . Just though it's nice to keep these branches somewhat up to date with master. Can ofc wait til after release or not merge them at all.

I don't care too much one way or another, just figured it would be nice to include a "why" in the commit comment. Even just chore: or deps-update: sort of tag.

**Pull request closed without merging**
