### PR TITLE
CFE-3734: Allow trailing comma in policy argument list

### PR DESCRIPTION
**Pull request by larsewi**
Ticket: CFE-3734
Changelog: Title
Signed-off-by: larsewi <lars.erik.wik@northern.tech>

### CODE REVIEW

**Comment by larsewi** [comment]
@cf-bottom Jenkins please !

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7090/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7090/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7090/

**Comment by larsewi** [comment]
@cf-bottom Jenkins again please !

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7092/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7092/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7092/

**Review by vpodzime — APPROVED** [review]
:heart: very nice PR!

**Review by vpodzime — CHANGES_REQUESTED** [review]
Actually! `Ticket:` should say `CFE-3734`.

**Comment by larsewi** [comment]
> larsewi force-pushed the larsewi:trailing-comma branch from 8e4d42e to 97a5d24 4 minutes ago
Changed commit message only

**Review by olehermanse — APPROVED** [review]

**Pull request merged**
