### PR TITLE
CFE-3631: Changed files promise repaired log level to verbose

### PR DESCRIPTION
**Pull request by KotzaBoss**
Ticket: CFE-3631
Changelog: Title

### CODE REVIEW

**Review by olehermanse — CHANGES_REQUESTED** [review]
@KotzaBoss there are some tests that need to be adjusted, for example:

```
tests/acceptance/28_inform_testing/01_files/changes01.cf
```

**Comment by olehermanse** [comment]
@cf-bottom please test this in jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6594/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6594/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6594/

**Comment by KotzaBoss** [comment]
Assuming this is a proper way to deal with the failling tests, [one](https://github.com/cfengine/core/blob/master/tests/acceptance/28_inform_testing/01_files/transformer.cf.expected) fails on my machine but not on travis. The expected has /bin/gzip yet on my pc /usr/cbin/gzip is generated. Is this something that calls for further investigation?

**Comment by olehermanse** [comment]
> Assuming this is a proper way to deal with the failling tests, one fails on my machine but not on travis. The expected has /bin/gzip yet on my pc /usr/cbin/gzip is generated. Is this something that calls for further investigation?

@KotzaBoss Try running said test on master, to see whether it is related to your changes here or not.

If it fails on master, it's worth looking into, but it's a separate issue, then ;)

**Review by olehermanse — APPROVED** [review]
Looks good to me :)

**Pull request merged**
