### PR TITLE
CFE-3046: Only add unique Ipv4 and MAC address to sys variables

### PR DESCRIPTION
**Pull request by oleorhagen**
The finished PR for CFE-3046. This is the same commit as in: https://github.com/cfengine/core/pull/4027

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, with exotics, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4480/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4480/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4480/

**Comment by olehermanse** [comment]
@cf-bottom jenkins, with exotics, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4481/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4481/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4481/

**Comment by vpodzime** [comment]
Retry on Solaris 10 only:
[Build Status](https://ci.cfengine.com/job/pr-pipeline/4485/)

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please, with exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4504/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4504/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4504/

**Comment by olehermanse** [comment]
@cf-bottom jenkins with exotics, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4512/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4512/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4512/

**Comment by oleorhagen** [comment]
:fireworks:

**Pull request merged**
