### PR TITLE
CFE-3461: Fixed small memory leak in cf-promises

### PR DESCRIPTION
**Pull request by olehermanse**
Found by running acceptance tests with ASAN.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5775/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5775/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5775/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5776/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5776/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5776/

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
