### PR TITLE
CFE-3472: Changed most tests to use ifvarclass instead of if

### PR DESCRIPTION
**Pull request by olehermanse**
Skipped those that explicitly mentioned ifvarclass in file name or test description.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom please test this in jenkins :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5851/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5851/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5851/

**Review by vpodzime — APPROVED** [review]
TL;DR ACK

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5854/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5854/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5854/

**Comment by olehermanse** [comment]
Aborted deployment tests since this PR only affects acceptance tests.

**Pull request merged**
