### PR TITLE
[3.12.x] LMDB remediation follow-up

### PR DESCRIPTION
**Pull request by vpodzime**
Merge together:
https://github.com/cfengine/core/pull/4003
https://github.com/cfengine/enterprise/pull/575

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4363/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4363/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4363/

**Comment by vpodzime** [comment]
@cf-bottom another jenkins, please, this time with exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4364/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4364/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4364/

**Pull request merged**
