### PR TITLE
ENT-9340: Fixed cf-support shellcheck check target

### PR DESCRIPTION
**Pull request by craigcomstock**
Needed to check shellcheck command differently.

Ticket: ENT-9340
Changelog: none

### CODE REVIEW

**Comment by craigcomstock** [comment]
try: [Build Status](https://ci.cfengine.com/job/pr-pipeline/9185/)

**Comment by craigcomstock** [comment]
retry with unrevert: [Build Status](https://ci.cfengine.com/job/pr-pipeline/9186/)

**Review by Lex-2008 — DISMISSED** [review]

**Review by Lex-2008 — APPROVED** [review]

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics, and we can merge when canaries are green.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9187/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9187/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9187/

**Review by Lex-2008 — APPROVED** [review]

**Comment by craigcomstock** [comment]
will cherry pick to 3.21.x and 3.18.x after I see that master CI is all green in testing-prs.

**Comment by craigcomstock** [comment]
cherry picks
3.21.x: https://github.com/cfengine/core/pull/5166
3.18.x: https://github.com/cfengine/core/pull/5167

**Pull request merged**
