### PR TITLE
CoreOS support in 3.10

### PR DESCRIPTION
**Pull request by olehermanse**
I cherry-picked **my own** commits from master to be able to bring over the os-release parsing for CoreOS. This PR doesn't include the changes to readdata, os-release policy variable and acceptance tests from #2791 . Code for env file parsing (internally, not via policy) brought over, and set hard classes and variables for CoreOS.

### CODE REVIEW

**Comment by olehermanse** [comment]
This must be cherry-picked in enterprise: https://github.com/cfengine/enterprise/commit/3a9747c12f6ec14fe0e66219f29a4818c2abd7e2

**Comment by olehermanse** [comment]
@jimis Please review (and start in jenkins?). Unit tests and bootstrap worked fine on my machine.

**Comment by olehermanse** [comment]
Travis is down atm, will restart once available.

**Comment by jimis** [comment]
@olehermanse all cherry-picks to maintenance branches should happen with the `-x` switch. It helps when we automatically try to see what commit has been cherry-picked and what not.

**Comment by jimis** [comment]
I did the cherry-picks using the `-x` switch in #2810. Didn't pick the CoreOS stuff though, that's up to you. Feel free to force-push to this pull request when you have it.

**Comment by olehermanse** [comment]
@jimis Thanks! Rebased now, waiting for travis.

**Comment by olehermanse** [comment]
@jimis Please review

**Comment by olehermanse** [comment]
started in jenkins: https://ci.cfengine.com/job/bootstrap-enterprise-pr/220/

**Comment by jimis** [comment]
Jenkins is green (besides the usual spurious errors).

**Comment by jimis** [comment]
I don't see the cherry-picks showing the source commit. Did you use `git cherry-pick -x` ?

**Comment by jimis** [comment]
Superseded by #2813.

**Comment by jimis** [comment]
@olehermanse Your last commit 7389f76092900866d560cac19fbd6054cf827513 is not a single cherry-pick, since I cherry-picked it separately and it's much smaller. Please don't mix cherry-picks because they mess-up the release scripts. If you want to add new functionality use a separate commit only for 3.10.x branch, after you are done with the cherry-picks.

**Pull request closed without merging**
