### PR TITLE
GH Actions: Backported fixes for macOS (3.21)

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Review by larsewi — APPROVED** [review]

**Comment by larsewi** [comment]
@olehermanse, can you do the same for 3.18?

**Comment by olehermanse** [comment]
@larsewi probably won't get to it today, maybe tomorrow 😅 

FYI, it looks like you were upgrading libntech in your PR - I was not. I only fixed GH Actions.

**Comment by olehermanse** [comment]
3.18:
https://github.com/cfengine/core/pull/5505

**Comment by olehermanse** [comment]
@craigcomstock @larsewi It would've been a lot more efficient if you just did the cherry-pick and got it merged, rather than asking me to do it, waiting, opening a PR, closing it again, etc.

**Pull request merged**
