### PR TITLE
Protect classes and variables from CMDB data from being re-defined in augments

### PR DESCRIPTION
**Pull request by vpodzime**
Host-specific values should take precedence over possibly more generic values from augments.

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6589/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6589/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6589/

**Comment by basvandervlies** [comment]
Just a question what does this do? What kind of classes/vars we can not override anymore in `def.json`?

**Comment by vpodzime** [comment]
> Just a question what does this do? What kind of classes/vars we can not override anymore in `def.json`?

There's a new functionality being added to 3.18.0+ -- host-specific data. The agent loads the `/var/cfengine/data/host-specific.json` file first, even before augments. In enterprise, this file will be produced on the hub with data from Mission Portal, in community, some other mechanism may be used to create it on the policy server. Then the individual host-specific files are distributed together with policy to individual hosts.

The idea behind this PR is that if something is set in the host-specific data, augments should not override it. But unless you start using the `host-specific.json` functionality, you have nothing to worry about.

**Comment by vpodzime** [comment]
> Alright, I triggered a build:
> 
> [Build Status](https://ci.cfengine.com//job/pr-pipeline/6589/)

Unrelated failures in FR tests and bootstrap tests.

**Comment by basvandervlies** [comment]
@vpodzime thanks for the explanation this makes sense

**Review by olehermanse — APPROVED** [review]
LGTM, thanks!

**Comment by olehermanse** [comment]
Merging this one rather quickly to avoid unnecessary conflicts when working on CMDB / augments functionality.

**Pull request merged**
