### PR TITLE
When there is an parse error quit after 3 errors instead of 12

### PR DESCRIPTION
**Pull request by basvandervlies**
Changelog: Title

### CODE REVIEW

**Comment by jimis** [comment]
@basvandervlies the parser test is failing. Do

```
cd tests/unit
make parser_test
./parser_test
```

Does it work for you?

**Comment by basvandervlies** [comment]
@jimis. I just saw this. It has more impact then I thought. The test program quits because due this statement in `cf3parse.y`
```
    if (P.error_count > 3)
    {   
        fprintf(stderr, "Too many errors\n");
        exit(EXIT_FAILURE);
    }
```

The test program can not handle this correcly. That is why we have the value 12 which is insane.

**Comment by jimis** [comment]
Can you fix the parser test?

**Comment by basvandervlies** [comment]
@jimis the `parser_test` will exit due the above `exit...` statement in `cf3parse.y` can I catch this exit code or must I make a lot different parser test files? I am not that familiar with the `assert_false` stuff.

**Comment by jimis** [comment]
I see: the tested function `exit()`s instead of returning false, so the `assert_false()` never gets to verify the return value.

It's tricky and I can't think of any straightforward fix. Maybe have a global variable `CF_PARSER_MAX_NUMBER_OF_ERRORS = 3`. At the beginning of the test this could be changed to 12? Dirty but should do the trick...

**Comment by olehermanse** [comment]
@basvandervlies Are you able to update the parser test to reflect this change?

**Comment by basvandervlies** [comment]
@olehermanse I did not look at the parser test code and the coming 2 weeks I am on vacation

**Comment by olehermanse** [comment]
Closing since it's been more than a year. Feel free to open a new PR if you get back to this.

**Pull request closed without merging**
