### PR TITLE
Process state add zombie state.

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
The `process_terminate_unix_test` needed lots of massaging to work again, fixed, rebased, and force-pushed.

**Comment by jimis** [comment]
trigger build

**Comment by kacfengine** [comment]
There appears to be some problems on Solaris, and there is a test specific to Solaris there, ``solaris_process_test``. Maybe it can be merged with the others.

The code looks very good though!

**Comment by jimis** [comment]
I'll look into the solaris failure right away. Those darn unit tests are mocking all system functions, it took me almost as long as I wrote the rest of the code to make them work, and now another one is failing...

**Comment by kacfengine** [comment]
Yeah, I don't like mocking, it makes everything harder to understand, and ultimately it doesn't test the real thing anyway. Should be used only when there is no other way.

**Comment by jimis** [comment]
trigger build

**Comment by kacfengine** [comment]
``solaris_process_test`` seems fixed, but ``process_test`` still fails on Solaris:

```
16:11:14 3 != 2
16:11:14 ERROR: process_test.c:183 Failure!
16:11:14 1 out of 3 tests failed!
16:11:14     test_graceful_terminate
16:11:14 ==================================================
16:11:14 Starting test: process_test.c
16:11:14 ==================================================
16:11:14 test_process_start_time: Starting test
16:11:14 test_process_start_time: Test completed successfully.
16:11:14 test_process_state: Starting test
16:11:14 Spawned a "sleep" child with PID 5406
16:11:14 Started, state: 0
16:11:14 Stopped, state: 1
16:11:14 Resumed, state: 0
16:11:14 Killed,  state: 3
16:11:14 test_process_state: Test completed successfully.
16:11:14 test_graceful_terminate: Starting test
16:11:14 Spawned a "sleep" child with PID 5407 and start_time 1424877064
16:11:14 Killing child with wrong start_time, child should not die...
16:11:14 Killing child with correct start_time, child should die...
16:11:14 test_graceful_terminate: Test failed.
16:11:14 FAIL: process_test
```

**Comment by jimis** [comment]
Yeah just ignore this pull request until further notice, it's way too complicated to detect a zombie process on Solaris 9...

**Comment by kacfengine** [comment]
Should we work around the test and merge the rest then? Would be good to have it in by tomorrow, and it's already better than it was.

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
> Should we work around the test and merge the rest then? Would be good to have it in by tomorrow, and it's already better than it was.

I think I'm almost there. But anyway no need to hurry, it's only meant to stay in master.

**Comment by jimis** [comment]
And yes [the build is green](http://jenkins.usdc.cfengine.com/job/testing-enterprise-pr_core/56/), the latest changes seem to fix this in every platform (AIX is failing for other reasons).

Feel free to merge in master then, but first have a look in `process_solaris.c` to get an image of the hack I had to resort in.

**Comment by jimis** [comment]
OK this is done now.

In the last commit I changed the interface of `GracefulTerminate()` to make it more sane.

**Comment by jimis** [comment]
trigger build

**Comment by kacfengine** [comment]
Nearly there, but now Windows doesn't build! :-)

**Comment by jimis** [comment]
damer!

**Comment by jimis** [comment]
The fix is a single line change for enterprise, in the windows implementation of GracefulTerminate. Merging and will push the enterprise fix directly.

**Pull request merged**
