### PR TITLE
Call cleanup functions in binaries' main()

### PR DESCRIPTION
**Pull request by vpodzime**
Merge together:
https://github.com/cfengine/core/pull/4369
https://github.com/cfengine/nova/pull/1725

### CODE REVIEW

**Comment by vpodzime** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/5855/)

**Comment by vpodzime** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/5858/)

**Comment by vpodzime** [comment]
*bootstrap-tests* are green: [Build Status](https://ci.cfengine.com/job/bootstrap-tests/2030/)

**Comment by vpodzime** [comment]
*sequential-tests* failed in upgrades and with this:
```
3.250.129.122	   error: Database /var/cfengine/state/nova_cookies.lmdb refcount is still not zero (1), forcing CloseDB()!
34.245.143.73	   error: Database /var/cfengine/state/nova_cookies.lmdb refcount is still not zero (1), forcing CloseDB()!
34.245.97.196	   error: Database /var/cfengine/state/nova_cookies.lmdb refcount is still not zero (1), forcing CloseDB()!
34.245.98.221	   error: Database /var/cfengine/state/nova_cookies.lmdb refcount is still not zero (1), forcing CloseDB()!
54.78.178.170	   error: Database /var/cfengine/state/nova_cookies.lmdb refcount is still not zero (1), forcing CloseDB()!
3.250.140.2	   error: Database /var/cfengine/state/nova_cookies.lmdb refcount is still not zero (1), forcing CloseDB()!
34.248.165.21	   error: Database /var/cfengine/state/nova_cookies.lmdb refcount is still not zero (1), forcing CloseDB()!
3.250.91.132	   error: Database /var/cfengine/state/nova_cookies.lmdb refcount is still not zero (1), forcing CloseDB()!
3.249.76.30	   error: Database /var/cfengine/state/nova_cookies.lmdb refcount is still not zero (1), forcing CloseDB()!
```

**Review by olehermanse — APPROVED** [review]
LGTM 👍

**Comment by olehermanse** [comment]
@cf-bottom please test this again in jenkins, now that I fixed the cookie bug :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5876/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5876/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5876/

**Pull request merged**
