### PR TITLE
CFE-1915: Disallow modifications of foreign variables

### PR DESCRIPTION
**Pull request by vpodzime**
As described in [[CFE-1915]](https://tracker.mender.io/browse/CFE-1915).

### CODE REVIEW

**Comment by vpodzime** [comment]
jenkins job: https://ci.cfengine.com/job/pr-pipeline/191/

**Comment by ncharles** [comment]
Hi,
This PR would break a lot of things within Rudder - we use this behaviour for setting audit mode and going back to enforce mode.
What is worse is that this PR doesn't offer any workaround for this legitimate use case - without this, we can't use the CFEngine agent anymore

**Comment by vpodzime** [comment]
> What is worse is that this PR doesn't offer any workaround for this legitimate use case - without this, we can't use the CFEngine agent anymore

Please see the [JIRA ticket](https://tracker.mender.io/browse/CFE-1915) for the discussion and suggestions for workarounds.

**Comment by vpodzime** [comment]
> jenkins job: https://ci.cfengine.com/job/pr-pipeline/191/

All green except for some non-related issues with nested VMs.

**Comment by fanf** [comment]
Wow. Even with a big "warning" of the impact of that modification, you didn't care? This is extremelly disturbing. I don't know what we, Rudder dev (and the other people who gave voice to that) should understand about that. But the general message is extremelly bad.

**Comment by olehermanse** [comment]
@fanf We do care. Our decision is to fix this bug, which will break compatibility for those "using" it, however we want to help those affected by the change (including Normation / Rudder). It is my understanding that someone from the CFEngine team will contact you about this shortly.

**Pull request merged**
