### PR TITLE
[3.10.x] Core changes for windows detection

### PR DESCRIPTION
**Pull request by vpodzime**
Merge together:
https://github.com/cfengine/enterprise/pull/490

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @olehermanse can review this?

**Comment by vpodzime** [comment]
@cf-bottom jenkins with exotics, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2165/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/2165/

**Comment by vpodzime** [comment]
> Build Status

Unrelated fail in deployment tests on Debian 7.

**Pull request merged**
