### PR TITLE
ENT-4653: Test that ifelse works when used with 3 arguments and undefined variable variables

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @olehermanse can review this?

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2746/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2746/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2746/

**Comment by vpodzime** [comment]
@cf-bottom one more round of jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2310/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2310/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2310/

**Pull request merged**
