### PR TITLE
Testing tom

### PR DESCRIPTION
**Pull request by olehermanse**
Merge together:
cfengine/core#3272
cfengine/enterprise#429
https://github.com/cfengine/nova/pull/1141

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom: jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1174/)

https://ci.cfengine.com/job/pr-pipeline/1174/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1175/)

https://ci.cfengine.com/job/pr-pipeline/1175/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1176/)

https://ci.cfengine.com/job/pr-pipeline/1176/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1177/)

https://ci.cfengine.com/job/pr-pipeline/1177/

**Pull request closed without merging**
