### PR TITLE
Added test for readfile() of no size

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
Started in jenkins:
https://ci.cfengine.com/job/bootstrap-enterprise-pr/357/
https://ci.cfengine.com/job/testing-enterprise-pr/333/

**Comment by olehermanse** [comment]
@jimis Please review

**Comment by olehermanse** [comment]
Restarted in jenkins:
https://ci.cfengine.com/job/bootstrap-enterprise-pr/365/
https://ci.cfengine.com/job/testing-enterprise-pr/340/

**Comment by olehermanse** [comment]
@jimis This is mostly green in jenkins.

**Comment by jimis** [comment]
takk for testen !?!

**Pull request merged**
