### PR TITLE
ENT-5335 Typo fix: no comma after promisee

### PR DESCRIPTION
**Pull request by Lex-2008**
----

#

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom: build it, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5446/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5446/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5446/

**Comment by craigcomstock** [comment]
PACKAGES_HUB_x86_64_linux_debian_9 failure looks like a flake to me, the timed_tests often are flaky in my opinion.

```
./00_basics/ifelapsed_and_expireafter/timed/defaults.cf.defaults.cf
```

**Comment by craigcomstock** [comment]
Jenkins has passed enough tests for the scope of this change so I am merging. :)

**Pull request merged**
