### PR TITLE
ENT-6935 Fixup tests/acceptance/selftest.sh execution and results

### PR DESCRIPTION
**Pull request by craigcomstock**
Follow up to the first commit which worked well in pr-pipeline but not in nightly.

Ticket: ENT-6935
Changelog: title

test with https://github.com/cfengine/buildscripts/pull/821

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6393/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6393/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6393/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6394/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6394/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6394/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6395/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6395/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6395/

**Comment by craigcomstock** [comment]
Nice! 6 failures. This is expected in canaries... 3 hosts, 2 failures per host: 1 for default run of selftest and one for `FLAKEY_IS_FAIL=1`. I will "fix" the failure and see if all is green and then probably just merge. @nickanderson can you give a quick look here?

**Review by Lex-2008 — APPROVED** [review]

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6396/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6396/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6396/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6398/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6398/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6398/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6400/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6400/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6400/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6401/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6401/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6401/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6403/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6403/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6403/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6405/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6405/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6405/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins again, this time MOVE the test results files instead of copying them, maybe avoid dupes because JUnit plugin parses both outputs AND xml inside of `core/tests/**` ?

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6406/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6406/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6406/

**Comment by Lex-2008** [comment]
@craigcomstock : note that "merge" button here is disabled because of Conflicting files, so it's unclear what Jenkins is/will be building here - it tried to fetch a "merge commit" from github, and if that fails…

So you need to either rebase this branch on top of latest master, or go to Jenkins and rebuild the build using the `pull/NUMBER/head` syntax for the CORE_REV parameter

**Comment by craigcomstock** [comment]
deferring integration of selftest into CI, was difficult to include results along-side other core/tests/acceptance reports processing in jenkins.

**Pull request closed without merging**
