### PR TITLE
Fixed bounds check in SeqGetRange

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @vpodzime can review this?

**Comment by olehermanse** [comment]
@cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1506/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1506/

**Comment by olehermanse** [comment]
Solaris 10 failure unrelated. Merging.

**Pull request merged**
