### PR TITLE
name_index_count KILL

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
This pull request is small, basically only one commit, the rest will disappear when #2511 gets merged.

So @tzz can you review commit eee0ad7 ?

**Comment by jimis** [comment]
Hmm actually I just rememberer I asked @tzz about this on IRC and he is not the expert here. So maybe @kacf can you review commit eee0ad7 ?

**Comment by tzz** [comment]
Yeah sorry I can't be very helpful with this, but I'm absolutely in favor of killing unused fields and code to reduce complexity.

**Comment by jimis** [comment]
Now that #2511 got merged, this one is only one small commit. @kacf can you have a quick look in case I'm missing something obvious?

**Comment by kacf** [comment]
Looks alright to me.

**Comment by kacf** [comment]
trigger build

**Comment by jimis** [comment]
Build is green locally, and this is quite platform agnostic, so merging. Thanks for reviewing! :-)

**Pull request merged**
