### PR TITLE
Add '-n' flag to cf-key to avoid host name lookups.

### PR DESCRIPTION
**Pull request by kacf**
Changelog: Title

### CODE REVIEW

**Comment by kacf** [comment]
Warning: Drunk code....

@jimis: Here is the cf-key fix.

@nickanderson: Is there a ticket for this?

**Comment by jimis** [comment]
@kacf nice, will review drunk code carefully though. :-) I don't think there is a ticket, this came from my TODO.org document...

**Comment by GregorioDiStefano** [comment]
Drunk code?!

**Comment by jimis** [comment]
Inspiring initiative @kacf, merging, what can go wrong... ;-)

**Pull request merged**
