### PR TITLE
Redmine#6480: Add url_get() function.

### PR DESCRIPTION
**Pull request by kacfengine**

### CODE REVIEW

**Comment by kacfengine** [comment]
Supersedes https://github.com/cfengine/core/pull/2152.

**Comment by tzz** [comment]
docs in https://github.com/cfengine/documentation/pull/1191

**Comment by jimis** [comment]
@tzz two tests are failing when I build without CURL:

```
./01_vars/02_functions/url_get_local.cf
./01_vars/02_functions/network/url_get.cf
```

Maybe you can use our new syntax to set the "test_skip_unsupported" meta?

**Comment by tzz** [comment]
@jimis go ahead, it's easier for you at this point.

**Comment by jimis** [comment]
@tzz it's policy that's why I pushed towards you, else I would have done it already ;-) I want to see an example of the new `@if` syntax anyway before using it :-p

**Comment by tzz** [comment]
OK, see #2394

**Pull request merged**
