### PR TITLE
Fixed LGTM alerts: "Array argument size mismatch"

### PR DESCRIPTION
**Pull request by olehermanse**
Reported by LGTM:
https://lgtm.com/rules/1507386896202/

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2340/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2340/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2340/

**Comment by olehermanse** [comment]
This pull request **fixes 8 alerts** when merging 277b7e87f168cdcfa91b9255ce7c95cb578064cd into ee8c7c13b745df075231dd0d8cd44cff88f5d432 - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-2e095c8f90476f5b8e8c5054cdf7e80f935fe6da)

**fixed alerts:**

* 8 for Array argument size mismatch

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by olehermanse** [comment]
> minumum in the last commit's message, but otherwise this looks good to me.

@vpodzime fixed.

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2342/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2342/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2342/

**Comment by olehermanse** [comment]
This pull request **fixes 8 alerts** when merging 36a85e9df10beca482ccd6891bd74639c450a8de into 6dafc4082363c8902eb17e5f2c25945e0c776b21 - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-e903f583baa4a8cd26aeaf7500065d1183507946)

**fixed alerts:**

* 8 for Array argument size mismatch

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by olehermanse** [comment]
Cherry-pick: https://github.com/cfengine/core/pull/3639

**Pull request merged**
