### PR TITLE
CFE-3263 libntech: ASan / fuzzing fixes

### PR DESCRIPTION
**Pull request by olehermanse**
Updates submodule to master.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4709/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4709/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4709/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4714/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4714/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4714/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4716/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4716/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4716/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4717/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4717/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4717/

**Pull request merged**
