### PR TITLE
ENT-9363: Improved MacOS support (3.18)

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9291/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9291/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9291/

**Comment by craigcomstock** [comment]
missed the libntech module update somehow, fixed now so @cf-bottom jenkins again please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9292/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9292/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9292/

**Review by larsewi — APPROVED** [review]

**Review by olehermanse — APPROVED** [review]

**Pull request merged**
