### PR TITLE
ENT-4136: Prevent OOB read in ApplyPlatformExtraTable and free in unit test

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @vpodzime can review this?

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1311/)

https://ci.cfengine.com/job/pr-pipeline/1311/

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1314/)

https://ci.cfengine.com/job/pr-pipeline/1314/

**Pull request merged**
