### PR TITLE
ENT-4505: Don't allow NULL pointers as strings in hashing

### PR DESCRIPTION
**Pull request by olehermanse**
Merge together: 
https://github.com/cfengine/core/pull/3549
https://github.com/cfengine/enterprise/pull/493
https://github.com/cfengine/nova/pull/1382

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2203/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2203/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2203/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2206/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2206/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2206/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2207/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2207/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2207/

**Comment by olehermanse** [comment]
@vpodzime Updated PR title and commit title.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2209/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2209/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2209/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2211/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2211/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2211/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2212/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2212/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2212/

**Pull request merged**
