### PR TITLE
GenericAgentWriteHelp renamed and moved out of libpromises

### PR DESCRIPTION
**Pull request by olehermanse**
Must be merged with: https://github.com/cfengine/nova/pull/989

I'm doing this since cf-net tool should not depend on libpromises, but should use this function, like the other binaries.

### CODE REVIEW

**Comment by olehermanse** [comment]
@jimis Please review once travis passes.

!Must be merged with: cfengine/nova#989

**Comment by olehermanse** [comment]
Removed some cf-net stuff. Ready AFAICT

**Comment by olehermanse** [comment]
@jimis Can we merge this into master?

**Comment by jimis** [comment]
Simple to merge, let me know when you see Jenkins turn green.

**Comment by olehermanse** [comment]
Relevant Jenkins jobs:
https://ci.cfengine.com/job/bootstrap-enterprise-pr/76/
https://ci.cfengine.com/job/testing-enterprise-pr/66/

**Pull request merged**
