### PR TITLE
CFE-3256: Added warning if CSV parser parses nothing from non-empty file

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4628/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4628/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4628/

**Comment by olehermanse** [comment]
3.15: https://github.com/cfengine/core/pull/4081

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by olehermanse** [comment]
From libntech: https://github.com/cfengine/libntech/pull/50

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4630/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4630/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4630/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4631/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4631/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4631/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4632/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4632/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4632/

**Comment by olehermanse** [comment]
> Maybe we should add test case for this?

@karlhto It's such a small thing, so I don't think it's necessary, but if you want to, feel free to submit a follow-up PR.

**Pull request merged**
