### PR TITLE
ENT-5304: Replaced determine-version.py with a manually updated file

### PR DESCRIPTION
**Pull request by olehermanse**
Added determine-version.sh to replace it. A much simpler
solution which trusts the version number from the commited
file, but just adds a commit SHA if there is no tag.

This should get rid of all our problems with version mismatch.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4424/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4424/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4424/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4426/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4426/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4426/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4427/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4427/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4427/

**Comment by olehermanse** [comment]
Cherry-picks: 
https://github.com/cfengine/core/pull/4025
https://github.com/cfengine/core/pull/4026

**Pull request merged**
