### PR TITLE
ENT-7452: Use ts_key file for measurement names in cf-check dump (3.15)

### PR DESCRIPTION
**Pull request by craigcomstock**
Without using ts_key we can't dump custom measurements.

Ticket: ENT-7452
Changelog: title
(cherry picked from commit 418aa12f13e3fa5f4edd07c5fea55806e39b3f14)

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6964/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6964/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6964/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins again now that CI is more stable

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7031/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7031/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7031/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins should work now that I merged https://github.com/cfengine/system-testing/pull/402

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7043/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7043/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7043/

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
