### PR TITLE
[3.12.x] single copy list fixes

### PR DESCRIPTION
**Pull request by vpodzime**
3.12.x backport of #4589 and #4592.

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6439/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6439/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6439/

**Comment by vpodzime** [comment]
@cf-bottom jenkins, try nr. 2, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6449/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6449/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6449/

**Pull request merged**
