### PR TITLE
libntech: Updated to master

### PR DESCRIPTION
**Pull request by olehermanse**
Just some smaller improvements to stack data type, alloc
header, queue, etc. Nothing which should affect behavior.
Also had to adjust one include to make the new version work.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom Please test this in jenkins 🙇

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2951/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2951/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2951/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2952/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2952/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2952/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2953/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2953/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2953/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2954/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2954/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2954/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2956/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2956/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2956/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2957/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2957/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2957/

**Comment by olehermanse** [comment]
@cf-bottom one more jenkins build now, just in case.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2965/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2965/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2965/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2966/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2966/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2966/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2968/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2968/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2968/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2978/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2978/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2978/

**Comment by olehermanse** [comment]
@cf-bottom please test this in jenkins again, with exotics :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2983/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2983/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2983/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2989/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2989/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2989/

**Comment by olehermanse** [comment]
Debian 6 build:

[Build Status](https://ci.cfengine.com/job/testing-pr/label=PACKAGES_HUB_x86_64_linux_debian_6/4717/)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2990/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2990/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2990/

**Pull request merged**
