### PR TITLE
CFE-3551/master: Added inline json example

### PR DESCRIPTION
**Pull request by nickanderson**
Ticket: CFE-3551
Changelog: None

### CODE REVIEW

**Review by craigcomstock — APPROVED** [review]

**Review by olehermanse — CHANGES_REQUESTED** [review]
Fails `check_outputs.cf` acceptance test. Looks like you have some trouble with quoting (JSON numbers vs strings):

```
Q: "...r/bin/perl /hom": +R: Data container defined from json_multi_line: {
Q: "...r/bin/perl /hom":  "CFEngine Champions": [
Q: "...r/bin/perl /hom":  {
Q: "...r/bin/perl /hom":  "Name": "Aleksey Tsalolikhin",
Q: "...r/bin/perl /hom": -"Year": 2011
Q: "...r/bin/perl /hom": +"Year": "2011"
Q: "...r/bin/perl /hom":  },
Q: "...r/bin/perl /hom":  {
Q: "...r/bin/perl /hom":  "Name": "Ted Zlatanov",
Q: "...r/bin/perl /hom": -"Year": 2013
Q: "...r/bin/perl /hom": +"Year": "2013"
```

**Review by craigcomstock — APPROVED** [review]

**Review by olehermanse — CHANGES_REQUESTED** [review]
Please squash the commits.

**Review by olehermanse — CHANGES_REQUESTED** [review]
Also, the test still fails.

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6082/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6082/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6082/

**Comment by nickanderson** [comment]
Alrighty, test fixed, commits squashed. Please re-review @craigcomstock &| @olehermanse

**Review by olehermanse — APPROVED** [review]
LGTM (Assuming Jenkins looked green enough)

**Comment by nickanderson** [comment]
image

**Pull request merged**
