### PR TITLE
CFE-2919: Ensure suid log has proper permissions

### PR DESCRIPTION
**Pull request by olehermanse**
Separated commits, and gave a short explanation to the second change, with link to PR discussion.

Replaces: #3326

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2402/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2402/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2402/

**Comment by olehermanse** [comment]
> I think the permissions in the first commit's message are wrong, they shouldn't be 0077 in the end, right? Looks good to me otherwise.

Fixed. Also changed the log message to be more clear.

**Comment by olehermanse** [comment]
@cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2409/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2409/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2409/

**Comment by olehermanse** [comment]
@craigcomstock @vpodzime I split the changes into 2 separate commits, made the commit messages more verbose and clear, and changed the log messages to also be more explicit and clear. Please re-review.

**Comment by olehermanse** [comment]
Cherry-picks:
https://github.com/cfengine/core/pull/3637
https://github.com/cfengine/core/pull/3638

**Pull request merged**
