### PR TITLE
Relieve libcfnet from dependency on libpromises

### PR DESCRIPTION
**Pull request by vpodzime**
Merge together:
https://github.com/cfengine/libntech/pull/56
https://github.com/cfengine/core/pull/4088
https://github.com/cfengine/enterprise/pull/598
https://github.com/cfengine/nova/pull/1627
https://github.com/cfengine/buildscripts/pull/692

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please. Let's see the redness!

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4686/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4686/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4686/

**Comment by vpodzime** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4778/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4778/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4778/

**Comment by vpodzime** [comment]
This went into a dead end long time ago.

**Pull request closed without merging**
