### PR TITLE
ENT-7502: Fixed Windows version unknown in MP (3.18.x)

### PR DESCRIPTION
**Pull request by larsewi**
cherry-pick from master - https://github.com/cfengine/core/pull/4758

Ticket: ENT-7502
Changelog: None
Signed-off-by: larsewi lars.erik.wik@northern.tech

### CODE REVIEW

**Comment by larsewi** [comment]
@cf-bottom Jenkins please !

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7003/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7003/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7003/

**Comment by larsewi** [comment]
@olehermanse, should I test these cherry-picks on Windows?

**Review by olehermanse — APPROVED** [review]

**Comment by olehermanse** [comment]
@larsewi Please write down behind your ear that you are going to test windows and this feature as part of the next releases :)

**Pull request merged**
