### PR TITLE
try to debug ubuntu14 FR tests failures with --debug during bootstrap…

### PR DESCRIPTION
**Pull request by craigcomstock**
… update

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please, thanks.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5962/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5962/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5962/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins thanks

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5963/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5963/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5963/

**Comment by craigcomstock** [comment]
Instead of this, remove ubuntu 14 hub from fr-tests config :)

**Pull request closed without merging**
