### PR TITLE
Tzz pull 2316 regex_replace redmine7346

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
This supersedes pull request #2316, @tzz I only changed one small thing in the unit tests Makefile to make tests pass, please have a look and let me know, so that I squash into your commit.

**Comment by tzz** [comment]
Looks excellent.

**Comment by jimis** [comment]
Thanks @tzz, squashed the small fix in your huge commit. Lets see what jenkins has to say!

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
@tzz thanks for implementing `regex_replace()` !

**Comment by tzz** [comment]
You're welcome.  This could be one of the most useful functions in CFEngine long-term.  Next we need to think about applying it to a list.

**Comment by jimis** [comment]
Dammit I forgot the "Changelog:"  entry in the commit message, I'll amend an empty commit to master or @kacfengine will kill me. :-)

@tzz for your future patches you might want to read about it in HACKING.md. And BTW documentation would be welcome when you find time.

**Comment by jimis** [comment]
Changelog in commit 5e831cdfc8b44ebe44b438dfe77ae636b2c57a26.

**Comment by jimis** [comment]
Hmmm @pasinskim @kacfengine will there be a new build for 3.8.0b1? I'm very much tempted to cherry-pick this since review was completed before the deadline, and it was delayed mainly because of small details. The feature here is quite independent, so please consider cherry-picking if another build is needed.

**Comment by tzz** [comment]
make sure to merge https://github.com/cfengine/core/pull/2397 as well, it's an example.

**Comment by tzz** [comment]
docs in https://github.com/cfengine/documentation/pull/1200

**Pull request merged**
