### PR TITLE
ENT-8456: Fixes for cf-serverd starting before DNS works

### PR DESCRIPTION
**Pull request by vpodzime**
Merge together:
https://github.com/cfengine/core/pull/5045
https://github.com/cfengine/masterfiles/pull/2485

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8588/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8588/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8588/

**Comment by vpodzime** [comment]
As discussed, we should probably cherry-pick the systemd unit file change (and the template in MPF) to 3.18.x.

**Review by nickanderson — COMMENTED** [review]
How often does serverd reload? Once a minute?

Feels like we should document this behavior here: https://docs.cfengine.com/docs/master/reference-components-cf-serverd.html#allowconnects ?

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8616/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8616/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8616/

**Review by larsewi — DISMISSED** [review]
> It was lying about what the function was doing, probably being a leftover
from refactorization where the code that actually thus the described things
ended up in EvalContextSetPolicyServer().

Should it be `s/thus/does` in the commit message?

**Review by olehermanse — APPROVED** [review]
LGTM 👍

**Pull request merged**
