### PR TITLE
Context tags NULL redmine6924

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
Build successful, @kacfengine merge at will!

**Comment by jimis** [comment]
BTW `CF_ASSERT_FIX()` was introduced for the [relevant pull request for enterprise](https://github.com/cfengine/enterprise/pull/245) but I'm thinking it's pretty neat and we should use it all around the codebase!

**Comment by kacfengine** [comment]
``CF_ASSERT_FIX`` is clever!

**Pull request merged**
