### PR TITLE
CFE-3669: Added check to fail errorexit tests that dont report errors

### PR DESCRIPTION
**Pull request by KotzaBoss**
Ticket: CFE-3669
Changelog: None

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @vpodzime can review this?

**Review by vpodzime — APPROVED** [review]
*don't*. Looks good to me otherwise.

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6629/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6629/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6629/

**Comment by vpodzime** [comment]
> Sure, I triggered a build:
> 
> [Build Status](https://ci.cfengine.com//job/pr-pipeline/6629/)

Nothing to worry about, AFAICT.

**Pull request merged**
