### PR TITLE
Redmine #7297: Make sure systemd is detected on Debian systems.

### PR DESCRIPTION
**Pull request by kacfengine**
Debian systems symlink /sbin/init to their systemd binary, but the
/proc/1/cmdline entry will contain the name of the link, not of the
target, hence our existing method will not work. So check the link
target of /sbin/init in addition.

### CODE REVIEW

**Comment by kacfengine** [comment]
I tested by switching out the link manually (scary on a live system!), but I haven't tested on an actual Debian system. Inspired by https://github.com/cfengine/masterfiles/pull/488.

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
@jimis: Review?

**Comment by jimis** [comment]
Hmmm, wouldn't it be safer to first read `/proc/1/cmdline`, second see if it's a link and if so dereference it, and third see if the end result ends with "/systemd"?

**Comment by kacfengine** [comment]
My thinking was that reading a link would be faster than opening and reading a process entry, so we start with the cheapest option. But this is guesstimation at best, and we can reverse that order if you think that's better.

``readlink`` will both tell you if it's a link and dereference it, so you only need that one call. I assume under the hood that both ``readlink`` and ``stat`` go to the inode.

**Comment by kacfengine** [comment]
> ``readlink`` will both tell you if it's a link and dereference it

Which is the ``EINVAL`` error check, I should add.

**Comment by jimis** [comment]
My guesstimation is that reading /proc/whatever is faster, since it has nothing to do with filesystem, inode cache, and even possibly hitting the disk.

Plus it catches the case where `/sbin/init` exists but was not chosen as PID 1.

**Comment by kacfengine** [comment]
> My guesstimation is that reading /proc/whatever is faster, since it has nothing to do with filesystem, inode cache, and even possibly hitting the disk.

Ah, good point, I didn't think of that.

> Plus it catches the case where /sbin/init exists but was not chosen as PID 1.

A perverse case, but yeah, I suppose it is possible! I'll change it.

**Comment by kacfengine** [comment]
Alright, moved the readlink check after the /proc check, and also reused the name obtained from ``/proc/1/cmdline`` instead of hardcoding ``/sbin/init``.

**Comment by kacfengine** [comment]
trigger build

**Comment by jimis** [comment]
I would nitpick on this that it's too complex, e.g. there is code duplication about detecting the last component of the path. Instead I took 10 min and wrote what I consider as simple:

https://github.com/cfengine/core/pull/2252

What do you think?

**Pull request closed without merging**
