### PR TITLE
Send promise type to custom promise modules

### PR DESCRIPTION
**Pull request by vpodzime**
Custom promise modules can potentially implement multiple promise types so they need to know the type of the promise they are asked to validate or evaluate.

### CODE REVIEW

**Comment by vpodzime** [comment]
```
< {"attributes":{"repo":"https://github.com/cfengine/masterfiles"},"log_level":"info","operation":"validate_promise","promise_type":"git","promiser":"/tmp/masterfiles"}
< 
> {"operation": "validate_promise", "promiser": "/tmp/masterfiles", "attributes": {"repo": "https://github.com/cfengine/masterfiles"}, "result": "valid"}
> 
< {"attributes":{"repo":"https://github.com/cfengine/masterfiles"},"log_level":"info","operation":"evaluate_promise","promise_type":"git","promiser":"/tmp/masterfiles"}
< 
> {"operation": "evaluate_promise", "promiser": "/tmp/masterfiles", "attributes": {"repo": "https://github.com/cfengine/masterfiles"}, "result": "repaired", "result_classes": ["/tmp/masterfiles_\
cloned"]}
```

**Review by olehermanse — APPROVED** [review]
Great, thanks!

**Review by larsewi — APPROVED** [review]
Looks good. There is extensive use of `strcmp` though. Should not `StringEqual` be used instead? If so, I can make a ticket and change them later if you want.

**Comment by vpodzime** [comment]
Sanity-check run in jenkins: [Build Status](https://ci.cfengine.com/job/pr-pipeline/6228/)

**Comment by vpodzime** [comment]
> There is extensive use of `strcmp` though. Should not `StringEqual` be used instead?

Yeah, I noticed that too, but I thought I was already doing too much on top of the scope of the ticket. :wink:

**Pull request merged**
