### PR TITLE
Add: Example showing report promise features

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
Would be nice if this can be picked to 3.7 as well for improved documentation (cannot goto 3.6 because if macro is included)

**Comment by nickanderson** [comment]
ping @jimis or @kacfengine

**Comment by nickanderson** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by jimis** [comment]
@nickanderson  merged as you requested but I'll leave cherry-picking to somebody who understands these things.

**Comment by nickanderson** [comment]
Thanks

**Pull request merged**
