### PR TITLE
Create global set of keys for bodies

### PR DESCRIPTION
**Pull request by worr**
The new global set of keys currently has only one entry (meta),
but can be extended into multiple entries later.

### CODE REVIEW

**Comment by jimis** [comment]
So this adds "meta" attribute to all bodies?

**Comment by basvandervlies** [comment]
the discussion is here: https://groups.google.com/forum/#!msg/dev-cfengine/xXU8GqPKt0U/fM1S5Yg5zrwJ

**Comment by kacfengine** [comment]
So I suppose this only adds the syntax, and doesn't make any use of the tags?

I'd still like to know what people want to achieve with this. The only reason I've heard so far is a "deprecated" attribute, for which I think this is a little overkill. Is there anything else you have in mind?

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
Given the fact that we have used ``meta`` to deprecate things in masterfiles already, and the fact that we're merely extending a concept into bodies which already exists for bundles, I'm gonna merge this.

**Comment by kacfengine** [comment]
Thanks, @worr!

**Pull request merged**
