### PR TITLE
Acceptance test for ensuring that a pre-existing failsafe.cf is not overwritten.

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
@nickanderson please review.

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
Jenkins doesn't want to build this for some strange reason. Still, I tested locally and passes all tests.

**Comment by pasinskim** [comment]
I am cherry-picking this stuff to 3.7 together with https://github.com/cfengine/core/pull/2353
See https://github.com/cfengine/core/pull/2368

**Pull request merged**
