### PR TITLE
Bump libntech and fix GH Actions failures

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10645/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10645/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10645/

**Review by larsewi — APPROVED** [review]

**Review by craigcomstock — APPROVED** [review]
if it works, let's go with it for now. I created a ticket to integrate the workarounds back into configure.ac and such.

**Comment by olehermanse** [comment]
Backport to 3.21: https://github.com/cfengine/core/pull/5500

**Pull request merged**
