### PR TITLE
libntech: Changes needed for use in Mender

### PR DESCRIPTION
**Pull request by olehermanse**
Merge together:
https://github.com/cfengine/core/pull/4352
https://github.com/cfengine/enterprise/pull/639

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5791/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5791/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5791/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5792/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5792/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5792/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5793/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5793/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5793/

**Comment by olehermanse** [comment]
Last [force-push](https://github.com/cfengine/core/compare/f83dc0025e55e32dd07f74df730fb272d9a7c7f7..b05e31f5ea7ac6a6362d6d7b362e7cbe3d873a21) just added a merge commit, no changes, so Jenkins results should still be valid.

**Comment by olehermanse** [comment]
@cf-bottom jenkins again, just for fun.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5795/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5795/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5795/

**Review by vpodzime — APPROVED** [review]
ACK

**Comment by olehermanse** [comment]
Cherry-pick: https://github.com/cfengine/core/pull/4356

**Pull request merged**
