### PR TITLE
Use simple custom testing helpers in tests/unit/process_test.c

### PR DESCRIPTION
**Pull request by vpodzime**
The test forks a child process which confuses the test framework
the other tests use.

Ticket: ENT-7249
Changelog: None

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6766/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6766/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6766/

**Comment by vpodzime** [comment]
exotics: [Build Status](https://ci.cfengine.com/job/pr-pipeline/6769/) (just in case)

**Comment by vpodzime** [comment]
HP-UX retry: [Build Status](https://ci.cfengine.com/job/pr-pipeline/6770/) (failed above due to bad system time)

**Review by craigcomstock — APPROVED** [review]
yes, looks good :+1:

**Pull request merged**
