### PR TITLE
Redmine #6582: Fix deletion of dangling symlinks

### PR DESCRIPTION
**Pull request by worr**
`DepthSearch` isn't entered when there's a dangling symlink. This is usually a good thing, however if a user wants to delete a dangling symlink with CFEngine, this poses a problem.

Also includes acceptance test.

### CODE REVIEW

**Comment by worr** [comment]
Redmine: https://dev.cfengine.com/issues/6582

**Comment by nickanderson** [comment]
Nice test

**Comment by nickanderson** [comment]
Might want to make sure that "$(G.testdir)/sourcefile" doesn't exist in init.

**Comment by tdlee** [comment]
Thanks for looking at this.  And thanks also for ensuring there is an acceptance test!

**Comment by worr** [comment]
@nickanderson fixed acceptance test per your recommendation

**Comment by kacfengine** [comment]
> Might want to make sure that "$(G.testdir)/sourcefile" doesn't exist in init.

Actually this isn't necessary when running under the test framework, since it always starts with a blank testdir. It doesn't harm though.

**Comment by kacfengine** [comment]
> It doesn't harm though.

Or actually in this case it did. It was missing the body definition. I fixed that and one other issue and resubmitted the PR here: #2108

**Pull request closed without merging**
