### PR TITLE
CFE-2952: Fix failing example test

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1733/)

https://ci.cfengine.com/job/pr-pipeline/1733/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1734/)

https://ci.cfengine.com/job/pr-pipeline/1734/

**Comment by olehermanse** [comment]
@vpodzime See the change to the perl script, do you think this is okay?

**Comment by nickanderson** [comment]
It's passing jenkins too, I am going to go ahead and merge this.

**Pull request merged**
