### PR TITLE
ENT-9363: Improved MacOS support (3.21)

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9290/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9290/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9290/

**Comment by craigcomstock** [comment]
missed the libntech module update somehow, fixed now so @cf-bottom jenkins again please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9293/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9293/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9293/

**Review by olehermanse — CHANGES_REQUESTED** [review]
LGTM, but please get rid of the extra commit at the end.

**Review by olehermanse — APPROVED** [review]

**Pull request merged**
