### PR TITLE
CFE-2551: Test that merged data does not include variables from caller

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by jimis** [comment]
./01_vars/02_functions/mergedata-CFE-2551-2.cf FAIL (The test Passed, but failure was expected) (UNEXPECTED FAILURE)

**Comment by jimis** [comment]
So the test passes? There is no bug here?

**Comment by olehermanse** [comment]
Ping @nickanderson

**Comment by nickanderson** [comment]
I apologise for being so terrible at following up on these

**Comment by nickanderson** [comment]
So, now the proper ones are passing and proper ones are soft failing. Does Jenkins agree?

**Comment by nickanderson** [comment]
https://ci.cfengine.com/view/all/job/pr-pipeline/246/

**Comment by nickanderson** [comment]
Yeah, but that was a different test case. Probably spurious.

FAIL (UNEXPECTED FAILURE) ./25_cf-execd/timed/mailfilter_repeated_runs.cf

Merging.

**Pull request merged**
