### PR TITLE
Statedir compile time option

### PR DESCRIPTION
**Pull request by kacfengine**

### CODE REVIEW

**Comment by kacfengine** [comment]
Merge together with https://github.com/cfengine/enterprise/pull/260 and https://github.com/cfengine/nova/pull/908.

**Comment by basvandervlies** [comment]
Nice one. Finally ;-)

**Comment by cdituri** [comment]
Resurrected - thanks!
Also good call with 9107879; implementing a fallback like that hadn't occurred to me at the time :-)

**Comment by kacfengine** [comment]
@cdituri: Better late than never! Thanks for waiting this long.

**Pull request merged**
