### PR TITLE
redmine3993, redmine6870: Disable class set on reverse lookup of interfaces IP addresses.

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
Speeding up the acceptance tests, one commit at a time.

**Comment by jimis** [comment]
trigger build

**Comment by kacfengine** [comment]
FYI, this reduces build/test time on HP-UX, the slowest platform, by more than 30%. I really want this!

**Comment by jimis** [comment]
pinging @estenberg

**Comment by estenberg** [comment]
OK, makes sense, let's use the beta as a testbed for this as well.
But please add a loud message in the release notes about this being removed.

**Comment by jimis** [comment]
Merging then! Lets see how it goes...

**Comment by kacfengine** [comment]
Yey!

**Pull request merged**
