### PR TITLE
Changed several functions to use bool type correctly

### PR DESCRIPTION
**Pull request by olehermanse**
Reported by LGTM:
https://lgtm.com/rules/1508604166004/

Merge together:
https://github.com/cfengine/core/pull/3706
https://github.com/cfengine/enterprise/pull/526

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2686/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2686/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2686/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2688/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2688/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2688/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2694/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2694/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2694/

**Pull request merged**
