### PR TITLE
CFE-2954: Augments files can now handle class expressions by appending '::'

### PR DESCRIPTION
**Pull request by olehermanse**
A condition in an augments file is treated as a class expression
if it ends in `::`. Otherwise it is treated as a regular
expression.

Previously there was a bug, where the conditions in augments files
were treated as both class expressions and regular expressions.
This was ambiguous, and problematic since something like
`cfengine.nginx.enabled` as a regex would match a class called
`cfengine_nginx_enabled`, while as a class expression would match
`cfengine && nginx && enabled`.

This was fixed in 3.12.1 by treating it as a regex only.
(Documented and intended behavior).

Some users still wanted a way to use class expression, so the `::`
suffix solves the problem. For the example above, you can use this
in the augments file:

`cfengine.nginx.enabled::`

Since classes cannot end with `:`, this shouldn't be a problem,
it is not useful to have regular expressions ending with `::` in
this context.

Original commit made by @basvandervlies(bas.vandervlies@surfsara.nl).
Reworked by @olehermanse(ole@northern.tech).

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @vpodzime can review this?

**Comment by olehermanse** [comment]
Replaces: https://github.com/cfengine/core/pull/3666

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2481/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2481/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2481/

**Comment by vpodzime** [comment]
Maybe merge or pull in here changes from #3466 ?

**Comment by nickanderson** [comment]
@cf-bottom I added an acceptance test, can you please test in jenkins again?

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2502/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2502/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2502/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, again, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2504/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2504/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2504/

**Comment by nickanderson** [comment]
@cf-bottom @craigcomstock helped me see what I was missing, my test should pass now. Please have jenkins try it again.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2505/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2505/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2505/

**Comment by olehermanse** [comment]
@cf-bottom I'd like one more build. Just in case.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2506/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2506/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2506/

**Comment by olehermanse** [comment]
Cherry-pick: https://github.com/cfengine/core/pull/3672

**Pull request merged**
