### PR TITLE
ENT-6967 Increase waiting time for the package_lock.cf

### PR DESCRIPTION
**Pull request by Lex-2008**
Ticket: ENT-6967

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7488/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7488/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7488/

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7763/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7763/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7763/

**Comment by olehermanse** [comment]
@cf-bottom please test this in Jenkins, with exotics :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7764/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7764/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7764/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7793/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7793/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7793/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7827/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7827/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7827/

**Comment by Lex-2008** [comment]
with this "fix", I'm unable to reproduce the issue anymore. Latest pr-pipeline build: https://ci.cfengine.com/job/pr-pipeline/7895/

**Review by craigcomstock — APPROVED** [review]

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
