### PR TITLE
ENT-4617: Tests for connections requiring TLS 1.3

### PR DESCRIPTION
**Pull request by vpodzime**
TODO:
- [x] test for both ends requiring TLS 1.3
- [x] test for client requiring TLS 1.3
- [x] test for client requiring TLS 1.3, but server not supporting it

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8525/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8525/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8525/

**Comment by vpodzime** [comment]
> ** Travis CI - Pull Request ** Failing after 33m — Build Failed

```
acceptance/16_cf-serverd/serial/copy_from_tls_1_3_fail.cf  FAIL
acceptance/16_cf-serverd/serial/copy_from_tls_1_3_success.cf  FAIL
```
but when I run `make vm-check` which runs a CentOS 7 machine with CentOS 7-provided OpenSSL, I get this:
```
    no-deps-build: ./16_cf-serverd/serial/copy_from_tls_1_3_fail.cf Skipped (No platform support)
    no-deps-build: ./16_cf-serverd/serial/copy_from_tls_1_3_success.cf Skipped (No platform support)
```
And when `configure` is running in Travis, it properly says:
```
checking whether SSL_OP_NO_TLSv1_3 is declared... no
```
so it should just skip the tests too.

**Review by larsewi — APPROVED** [review]
ACK

**Pull request merged**
