### PR TITLE
MatchRegion no longer relies on a 4k buffer

### PR DESCRIPTION
**Pull request by worr**
From #2050

### CODE REVIEW

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
Hmm, I got some strange errors, hard to say if it is related or not. I'm gonna run it again.

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
Thanks, nice and clean fix!

**Comment by kacfengine** [comment]
Cherry-picked to 3.6.x as well.

**Comment by jimis** [comment]
+1, thanks for splitting the pull request into small chunks!

**Comment by basvandervlies** [comment]
+1 for fixing

**Pull request merged**
