### PR TITLE
Caller promisers

### PR DESCRIPTION
**Pull request by peckpeck**
Add this.callers_promisers variable
Only evaluate this variable when a "cfengine:callers_promisers" meta tag is present

### CODE REVIEW

**Comment by tzz** [comment]
Didn't we agree to make this change on top of #2331 ?  The functions I wrote are also very useful.

**Comment by tzz** [comment]
I can merge #2344 and #2331 if you prefer, @peckpeck

**Comment by peckpeck** [comment]
I think the function used is the same no ?
You can merge the PR.

**Comment by tzz** [comment]
I've cherry-picked and adjusted #2331 with the commits here, so this can probably be closed.

**Comment by kacfengine** [comment]
Ok, thanks!

**Comment by peckpeck** [comment]
Thanks @tzz

**Pull request closed without merging**
