### PR TITLE
cf-check: Added timestamp validation and fixed various smaller issues (3.15)

### PR DESCRIPTION
**Pull request by olehermanse**
No conflicts.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4462/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4462/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4462/

**Comment by vpodzime** [comment]
@olehermanse any conflicts?

**Comment by vpodzime** [comment]
> @olehermanse any conflicts?

I see the description now. No review needed then.

**Pull request merged**
