### PR TITLE
Coding style

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
This is about replacing `NULL == func(whatever)` with `func(whatever) == NULL`, and similar cases.

@tzz because you asked for it! ;-)
@kacf lets try to enforce this now in our reviews.

**Comment by jimis** [comment]
trigger build

**Comment by tzz** [comment]
`GOOD == this_pr`

**Comment by kacf** [comment]
> @kacf lets try to enforce this now in our reviews.

Ack!

**Pull request merged**
