### PR TITLE
Automake: Added CORE_ variables in libutils and libpromises

### PR DESCRIPTION
**Pull request by olehermanse**
This is the mechanism we have for taking variables like CFLAGS
from configure.ac to Makefile.am.

For more information on how to use CFLAGS and AM_CFLAGS, see:

https://www.gnu.org/software/automake/manual/html_node/Flag-Variables-Ordering.html

https://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_check_enable_debug.m4

There are many cases where we don't follow the recommended way,
and many more cases to clean up, but this set of patches
(one for libutils, one for libpromises) fixed my problems.

This patch allows you to do something like this:

```
$ ./autogen.sh --enable-debug
$ make -j2 CFLAGS='-Werror -Wall -Wno-pointer-sign'
```

And still get debugging information (line numbers in gdb) for
libpromises. Previously, the explicit `CFLAGS` in make command
would override the `-g` option from `--enable-debug`.

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @vpodzime can review this?

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2822/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2822/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2822/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2823/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2823/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2823/

**Comment by vpodzime** [comment]
The second commit looks a bit unrelated.

**Comment by olehermanse** [comment]
> The second commit looks a bit unrelated.

@vpodzime Necessary to make libpromises compile, it now gets more flags from configure than before, causing a compilation error about unused result from `freopen`.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2829/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2829/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2829/

**Pull request merged**
