### PR TITLE
Replaced uses of localtime with the safer localtime_r

### PR DESCRIPTION
**Pull request by olehermanse**
Reported by LGTM:
https://lgtm.com/rules/2154840805/

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2330/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2330/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2330/

**Comment by olehermanse** [comment]
This pull request **fixes 2 alerts** when merging 59d7457476fbf1dc606ab25328df22e996470205 into ee8c7c13b745df075231dd0d8cd44cff88f5d432 - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-10d095ce97996cac98d674fbd42eda7e5750881c)

**fixed alerts:**

* 2 for Use of potentially dangerous function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by olehermanse** [comment]
Cherry-pick: https://github.com/cfengine/core/pull/3613

**Pull request merged**
