### PR TITLE
CFE-3103/master: Added test for execresult() capturing stderr and stdout

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @vpodzime can review this?

**Comment by nickanderson** [comment]
@craig, the example you requested from my doc pr clarifying execresult capturing stdout and stdr is in this pr.

**Comment by nickanderson** [comment]
@cf-bottom  jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2413/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2413/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2413/

**Pull request merged**
