### PR TITLE
Tweak LGTM.com code quality badge so it doesn't mention C++

### PR DESCRIPTION
**Pull request by sjvs**
As requested by @olehermanse in #3241 (feel free to tweak!)

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @olehermanse can review this?

**Comment by olehermanse** [comment]
@sjvs Sorry, for the confusion I meant `C` instead of `C/C++`. The preview now shows no language. I don't think LGTM has this badge currently (since C/C++ is considered one language).

**Comment by olehermanse** [comment]
@sjvs Oh, sorry, I see what you meant now.

**Comment by olehermanse** [comment]
Thanks

**Pull request merged**
