### PR TITLE
ENT-3858: Travis: Run unit tests with ASAN (3.12)

### PR DESCRIPTION
**Pull request by olehermanse**
Merge together:
https://github.com/cfengine/core/pull/3563
https://github.com/cfengine/enterprise/pull/498
https://github.com/cfengine/nova/pull/1392

### CODE REVIEW

**Comment by olehermanse** [comment]
This might require more cherry-picks.

**Comment by olehermanse** [comment]
@vpodzime @craigcomstock Do you think these cherry-picks are ok for 3.12? They are needed if we want ASAN running on 3.12.x.

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2235/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2235/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2235/

**Comment by olehermanse** [comment]
This pull request **introduces 1 alert** when merging 3cbe38bdc2d47502ee0b167a5b92d65c9b970989 into fb371c7fa265796d7c772c9cd2863995fa227679 - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-fa443f00e8ffd1e344f38bdb0b2318126f8e4149)

**new alerts:**

* 1 for For loop variable changed in body

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2238/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2238/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2238/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2239/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2239/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2239/

**Pull request merged**
