### PR TITLE
Moved addr_lib to libcfnet

### PR DESCRIPTION
**Pull request by olehermanse**
(Do not merge yet)

### CODE REVIEW

**Comment by olehermanse** [comment]
Started in jenkins:
https://ci.cfengine.com/job/bootstrap-enterprise-pr/136/
https://ci.cfengine.com/job/testing-enterprise-pr/121/

**Comment by olehermanse** [comment]
@jimis Please review, what do you think? Will squash before merge.

**Comment by olehermanse** [comment]
@jimis Green in jenkins and travis.

**Comment by jimis** [comment]
Good start @olehermanse. Since cfnet shouldn't include `libpromises`, try to replace the `cf3.defs.h` inclusion with `platform.h`, and remove completely the `item_lib.h` inclusion.

**Comment by olehermanse** [comment]
@jimis Thanks, removed cf3.defs as requested.

Started in jenkins:
https://ci.cfengine.com/job/bootstrap-enterprise-pr/148/
https://ci.cfengine.com/job/testing-enterprise-pr/133/

**Comment by jimis** [comment]
Awesome, another step closer to the two libraries separation. Merging!

**Pull request merged**
