### PR TITLE
Change: Soften legacy package promise implementation warning

### PR DESCRIPTION
**Pull request by nickanderson**
Ref: https://dev.cfengine.com/issues/7603

### CODE REVIEW

**Comment by nickanderson** [comment]
I think this should go into 3.8 and also be picked into 3.7.x

**Comment by nickanderson** [comment]
ping @kacfengine @estenberg

**Comment by estenberg** [comment]
Looks good. Only thing is if we should set a release here so people have time to migrate. I propose "Removed from 3.11 and later versions".

**Comment by kacfengine** [comment]
> Only thing is if we should set a release here so people have time to migrate. I propose "Removed from 3.11 and later versions".

In principle I agree, but I don't think we can do that unless we have a clear plan for when some of the more exotic package managers will be replaced. Inventory still depends on the old package promise for many platforms, for example.

**Comment by kacfengine** [comment]
Cherry-picked to 3.8.x as well.

**Comment by kacfengine** [comment]
Oh, and 3.7.x too (I didn't think the message existed there).

**Pull request merged**
