### PR TITLE
ENT-3728: trial of not setting TCP_NODELAY in serverd

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by olehermanse** [comment]
@craigcomstock Syntax error:

```
Making all in cf-runagent
  CC       cf-runagent.lo
  CCLD     libcf-runagent.la
  CCLD     cf-runagent
Making all in cf-serverd
  CC       cf-serverd.lo
  CC       cf-serverd-enterprise-stubs.lo
  CC       cf-serverd-functions.lo
  CC       server_common.lo
  CC       server.lo
  CC       server_transform.lo
server.c: In function ‘HandleConnection’:
server.c:358:2: error: expected expression before ‘/’ token
 */
  ^
```

**Comment by craigcomstock** [comment]
debian_7 is their platform... so https://ci.cfengine.com/job/pr-pipeline/344/

**Comment by olehermanse** [comment]
@craigcomstock This can be closed, correct?

**Comment by craigcomstock** [comment]
trial did not have a positive effect so will drop this investigation

**Pull request closed without merging**
