### PR TITLE
CFE-2850 Added example for string_replace - 3.12.x

### PR DESCRIPTION
**Pull request by karlhto**
Tests replacing once, several and no occurences, as well as
ambiguous order.

Ticket: CFE-2850
Changelog: none

### CODE REVIEW

**Comment by karlhto** [comment]
@cf-bottom A jenkins!

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1033/)

https://ci.cfengine.com/job/pr-pipeline/1033/

**Comment by nickanderson** [comment]
See comment made for your 3.10.x cherrypick as well. 

New features should only go into .0 releases.

**Comment by olehermanse** [comment]
@karlhto Please go back and revert the commits which added string_replace to 3.10 and 3.12. Sorry for the noise. This will be a new feature in 3.13.0.

**Pull request closed without merging**
