### PR TITLE
supersedes PR# 2400 evalfunction.c: file-size arg of readjson() and readyaml() should be optional

### PR DESCRIPTION
**Pull request by soumyadipdm**
supersedes https://github.com/cfengine/core/pull/2400

### CODE REVIEW

**Comment by kacfengine** [comment]
Thanks for the update! Will run through the test build shortly.

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
These tests are failing with this change:

* `./01_vars/02_functions/readdata.cf`
* `./01_vars/02_functions/readdata_yaml.cf`

It failed on all platforms, so it should fail in your environment as well. Can you look into it? (`cd tests/acceptance ; ./testall ./01_vars/02_functions/readdata.cf ; cat test.log`)

**Comment by soumyadipdm** [comment]
Thanks, it should be good now.

**Comment by kacfengine** [comment]
Thanks!

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
Merged manually, accompanied by https://github.com/cfengine/documentation/commit/8d59492d981b18f036aaa850802bb3575789242c.

**Pull request closed without merging**
