### PR TITLE
ENT-6527 Added retry for opening lmdb transactions

### PR DESCRIPTION
**Pull request by craigcomstock**
Issue seen in ubuntu and debian hosts in jenkins CI using AWS hosts.

Ticket: ENT-6527
Changelog: title

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5969/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5969/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5969/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5988/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5988/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5988/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics, let's see if this retry gives us some stability

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5992/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5992/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5992/

**Comment by craigcomstock** [comment]
@vpodzime maybe this is what you had thought of doing for this issue.

**Comment by vpodzime** [comment]
> @vpodzime maybe this is what you had thought of doing for this issue.

Yes, I guess we will have to do something like this. Just be more careful about the specific errors.

**Pull request closed without merging**
