### PR TITLE
ENT-9050: Address package cache lmdb validation issues in valgrind-check (3.18)

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-9050
Changelog: none
(in each of two commits instead)

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8406/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8406/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8406/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8409/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8409/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8409/

**Pull request closed without merging**
