### PR TITLE
Changed SanityCheckDeletions to return false on failure

### PR DESCRIPTION
**Pull request by karlhto**
Split into a separate PR to check consequences.

Ticket: None
Changelog: None

### CODE REVIEW

**Comment by karlhto** [comment]
@olehermanse Now it's easier to test it.

**Comment by olehermanse** [comment]
@karlhto Thanks for splitting it up. I'd like to put this on hold until Jenkins is green.

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2448/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2448/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2448/

**Comment by karlhto** [comment]
@olehermanse Should we just close this?

**Pull request closed without merging**
