### PR TITLE
cf-check: Added timestamp validation and fixed various smaller issues

### PR DESCRIPTION
**Pull request by olehermanse**
Fixes:
https://tracker.mender.io/browse/ENT-5309
https://tracker.mender.io/browse/CFE-2988

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4457/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4457/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4457/

**Comment by olehermanse** [comment]
@cf-bottom jenkins, with exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4460/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4460/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4460/

**Comment by olehermanse** [comment]
I expect we will need to tweak this / make it less strict with some testing and feedback from users. I did test it manually on a fresh setup, and it seems fine.

**Ubuntu 18 hub:**

```
root@ip-172-31-22-71:~# cf-check diagnose --validate
    info: No filenames specified, defaulting to .lmdb files in /var/cfengine/state
    info: Status of '/var/cfengine/state/cf_lock.lmdb': OK
    info: Status of '/var/cfengine/state/cf_changes.lmdb': OK
    info: Status of '/var/cfengine/state/packages_updates_apt_get.lmdb': OK
    info: Status of '/var/cfengine/state/packages_installed_$(package_module_knowledge.platform_default).lmdb': OK
    info: Status of '/var/cfengine/state/nova_static.lmdb': OK
    info: Status of '/var/cfengine/state/history.lmdb': OK
    info: Status of '/var/cfengine/state/packages_installed_apt_get.lmdb': OK
    info: Status of '/var/cfengine/state/performance.lmdb': OK
    info: Status of '/var/cfengine/state/cf_lastseen.lmdb': OK
    info: Status of '/var/cfengine/state/cf_observations.lmdb': OK
    info: Status of '/var/cfengine/state/nova_agent_execution.lmdb': OK
    info: Status of '/var/cfengine/state/nova_track.lmdb': OK
    info: Status of '/var/cfengine/state/nova_measures.lmdb': OK
    info: Status of '/var/cfengine/state/cf_state.lmdb': OK
    info: Status of '/var/cfengine/state/nova_cookies.lmdb': OK
    info: All 15 databases healthy
root@ip-172-31-22-71:~# cf-check dump /var/cfengine/state/cf_lastseen.lmdb
{
	"a172.31.17.94": "SHA=7aab9681f671441f6d62811259bdba55e2dad3d0c8b57e5d9e5e19f52034a0a9",
	"a172.31.22.71": "SHA=f855916de3965283e0538ef3b1d61400c1948100b1cb3b314b4992eedd912b32",
	"a172.31.25.198": "SHA=e1b541f7beca5a2c86e151d3a07d722f632dc5f04e84a8adab4d063c9fb580a7",
	"a172.31.29.129": "SHA=2965a65820c4963c8fa765489e8e7f0d5425ffe799ccf3e34906356ff7236e87",
	"kSHA=2965a65820c4963c8fa765489e8e7f0d5425ffe799ccf3e34906356ff7236e87": "172.31.29.129",
	"kSHA=7aab9681f671441f6d62811259bdba55e2dad3d0c8b57e5d9e5e19f52034a0a9": "172.31.17.94",
	"kSHA=e1b541f7beca5a2c86e151d3a07d722f632dc5f04e84a8adab4d063c9fb580a7": "172.31.25.198",
	"kSHA=f855916de3965283e0538ef3b1d61400c1948100b1cb3b314b4992eedd912b32": "172.31.22.71",
	"qiSHA=2965a65820c4963c8fa765489e8e7f0d5425ffe799ccf3e34906356ff7236e87": {"Q":{"dq":0.0000,"expect":47.3920,"q":61.0000,"var":889.0906},"lastseen":1579695100},
	"qiSHA=7aab9681f671441f6d62811259bdba55e2dad3d0c8b57e5d9e5e19f52034a0a9": {"Q":{"dq":8.0000,"expect":52.4960,"q":83.0000,"var":2269.0566},"lastseen":1579695060},
	"qiSHA=e1b541f7beca5a2c86e151d3a07d722f632dc5f04e84a8adab4d063c9fb580a7": {"Q":{"dq":97.0000,"expect":44.5600,"q":106.0000,"var":4213.7440},"lastseen":1579695054},
	"qiSHA=f855916de3965283e0538ef3b1d61400c1948100b1cb3b314b4992eedd912b32": {"Q":{"dq":0.0000,"expect":0.0000,"q":0.0000,"var":0.0000},"lastseen":1579695050},
	"qoSHA=2965a65820c4963c8fa765489e8e7f0d5425ffe799ccf3e34906356ff7236e87": {"Q":{"dq":0.0000,"expect":0.0000,"q":0.0000,"var":0.0000},"lastseen":1579695050},
	"qoSHA=7aab9681f671441f6d62811259bdba55e2dad3d0c8b57e5d9e5e19f52034a0a9": {"Q":{"dq":0.0000,"expect":0.0000,"q":0.0000,"var":0.0000},"lastseen":1579695050},
	"qoSHA=e1b541f7beca5a2c86e151d3a07d722f632dc5f04e84a8adab4d063c9fb580a7": {"Q":{"dq":0.0000,"expect":0.0000,"q":0.0000,"var":0.0000},"lastseen":1579695050},
	"qoSHA=f855916de3965283e0538ef3b1d61400c1948100b1cb3b314b4992eedd912b32": {"Q":{"dq":201.0000,"expect":80.4000,"q":201.0000,"var":16160.4000},"lastseen":1579695050},
}
root@ip-172-31-22-71:~# cf-check --log-level debug diagnose --validate /var/cfengine/state/cf_lastseen.lmdb
   debug: LMDB validation: Adding key 'a172.31.17.94'
   debug: LMDB validation: Adding key 'a172.31.22.71'
   debug: LMDB validation: Adding key 'a172.31.25.198'
   debug: LMDB validation: Adding key 'a172.31.29.129'
   debug: LMDB validation: Adding key 'kSHA=2965a65820c4963c8fa765489e8e7f0d5425ffe799ccf3e34906356ff7236e87'
   debug: LMDB validation: Adding key 'kSHA=7aab9681f671441f6d62811259bdba55e2dad3d0c8b57e5d9e5e19f52034a0a9'
   debug: LMDB validation: Adding key 'kSHA=e1b541f7beca5a2c86e151d3a07d722f632dc5f04e84a8adab4d063c9fb580a7'
   debug: LMDB validation: Adding key 'kSHA=f855916de3965283e0538ef3b1d61400c1948100b1cb3b314b4992eedd912b32'
   debug: LMDB validation: Adding key 'qiSHA=2965a65820c4963c8fa765489e8e7f0d5425ffe799ccf3e34906356ff7236e87'
   debug: LMDB validation: Quality-entry lastseen time is 1579695100, current time is 1579695126
   debug: LMDB validation: Adding key 'qiSHA=7aab9681f671441f6d62811259bdba55e2dad3d0c8b57e5d9e5e19f52034a0a9'
   debug: LMDB validation: Quality-entry lastseen time is 1579695060, current time is 1579695126
   debug: LMDB validation: Adding key 'qiSHA=e1b541f7beca5a2c86e151d3a07d722f632dc5f04e84a8adab4d063c9fb580a7'
   debug: LMDB validation: Quality-entry lastseen time is 1579695054, current time is 1579695126
   debug: LMDB validation: Adding key 'qiSHA=f855916de3965283e0538ef3b1d61400c1948100b1cb3b314b4992eedd912b32'
   debug: LMDB validation: Quality-entry lastseen time is 1579695050, current time is 1579695126
   debug: LMDB validation: Adding key 'qoSHA=2965a65820c4963c8fa765489e8e7f0d5425ffe799ccf3e34906356ff7236e87'
   debug: LMDB validation: Quality-entry lastseen time is 1579695050, current time is 1579695126
   debug: LMDB validation: Adding key 'qoSHA=7aab9681f671441f6d62811259bdba55e2dad3d0c8b57e5d9e5e19f52034a0a9'
   debug: LMDB validation: Quality-entry lastseen time is 1579695050, current time is 1579695126
   debug: LMDB validation: Adding key 'qoSHA=e1b541f7beca5a2c86e151d3a07d722f632dc5f04e84a8adab4d063c9fb580a7'
   debug: LMDB validation: Quality-entry lastseen time is 1579695050, current time is 1579695126
   debug: LMDB validation: Adding key 'qoSHA=f855916de3965283e0538ef3b1d61400c1948100b1cb3b314b4992eedd912b32'
   debug: LMDB validation: Quality-entry lastseen time is 1579695050, current time is 1579695126
    info: Status of '/var/cfengine/state/cf_lastseen.lmdb': OK
    info: All 1 databases healthy
root@ip-172-31-22-71:~# 
```

**Ubuntu 16 client:**

```
root@ip-172-31-17-94:~# cf-check diagnose --validate
    info: No filenames specified, defaulting to .lmdb files in /var/cfengine/state
    info: Status of '/var/cfengine/state/packages_installed_apt_get.lmdb': OK
    info: Status of '/var/cfengine/state/cf_lock.lmdb': OK
    info: Status of '/var/cfengine/state/cf_state.lmdb': OK
    info: Status of '/var/cfengine/state/packages_updates_apt_get.lmdb': OK
    info: Status of '/var/cfengine/state/nova_measures.lmdb': OK
    info: Status of '/var/cfengine/state/cf_lastseen.lmdb': OK
    info: Status of '/var/cfengine/state/nova_agent_execution.lmdb': OK
    info: Status of '/var/cfengine/state/packages_installed_$(package_module_knowledge.platform_default).lmdb': OK
    info: Status of '/var/cfengine/state/cf_observations.lmdb': OK
    info: Status of '/var/cfengine/state/performance.lmdb': OK
    info: Status of '/var/cfengine/state/nova_static.lmdb': OK
    info: Status of '/var/cfengine/state/history.lmdb': OK
    info: Status of '/var/cfengine/state/cf_changes.lmdb': OK
    info: Status of '/var/cfengine/state/nova_cookies.lmdb': OK
    info: All 14 databases healthy
root@ip-172-31-17-94:~# cf-check dump /var/cfengine/state/cf_lastseen.lmdb
{
	"a172.31.22.71": "SHA=f855916de3965283e0538ef3b1d61400c1948100b1cb3b314b4992eedd912b32",
	"kSHA=f855916de3965283e0538ef3b1d61400c1948100b1cb3b314b4992eedd912b32": "172.31.22.71",
	"qiSHA=f855916de3965283e0538ef3b1d61400c1948100b1cb3b314b4992eedd912b32": {"Q":{"dq":0.0000,"expect":0.0000,"q":0.0000,"var":0.0000},"lastseen":1579695050},
	"qoSHA=f855916de3965283e0538ef3b1d61400c1948100b1cb3b314b4992eedd912b32": {"Q":{"dq":0.0000,"expect":64.6976,"q":83.0000,"var":1733.6316},"lastseen":1579695143},
}
root@ip-172-31-17-94:~# cf-check --log-level debug diagnose --validate /var/cfengine/state/cf_lastseen.lmdb
   debug: LMDB validation: Adding key 'a172.31.22.71'
   debug: LMDB validation: Adding key 'kSHA=f855916de3965283e0538ef3b1d61400c1948100b1cb3b314b4992eedd912b32'
   debug: LMDB validation: Adding key 'qiSHA=f855916de3965283e0538ef3b1d61400c1948100b1cb3b314b4992eedd912b32'
   debug: LMDB validation: Quality-entry lastseen time is 1579695050, current time is 1579695171
   debug: LMDB validation: Adding key 'qoSHA=f855916de3965283e0538ef3b1d61400c1948100b1cb3b314b4992eedd912b32'
   debug: LMDB validation: Quality-entry lastseen time is 1579695143, current time is 1579695171
    info: Status of '/var/cfengine/state/cf_lastseen.lmdb': OK
    info: All 1 databases healthy
root@ip-172-31-17-94:~# 
```

**Comment by olehermanse** [comment]
Cherry-picks:
https://github.com/cfengine/core/pull/4033
https://github.com/cfengine/core/pull/4034

**Pull request merged**
