### PR TITLE
Added a new --simulate=manifest-full mode

### PR DESCRIPTION
**Pull request by vpodzime**
New simulation mode that manifests all changed files as well as
all other files evaluated by the agent run which were not skipped
(by file selection rules).

Ticket: CFE-3506
Changelog: Commit

### CODE REVIEW

**Comment by olehermanse** [comment]
@vpodzime Not a big deal, but if the manifest includes kept, not kept and repaired, I'd prefer another name, like: `manifest-full` or simply `full`.

@nickanderson what do you think?

**Comment by vpodzime** [comment]
> @vpodzime Not a big deal, but if the manifest includes kept, not kept and repaired, I'd prefer another name, like: `manifest-full` or simply `full`.

Makes sense. And I guess the code should also not refer to `KEPT` when it's all non-skipped files (incl. failed)

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6074/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6074/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6074/

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6075/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6075/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6075/

**Comment by nickanderson** [comment]
> @vpodzime Not a big deal, but if the manifest includes kept, not kept and repaired, I'd prefer another name, like: `manifest-full` or simply `full`.
> 
> @nickanderson what do you think?

I don't think so.

To me, simulate diff is the short report showing just the delta. This one should I think show repaired and I think even not-kept as they are changes that couldn't be completed. They would be attempted during a non-simulation.

Manifest is the full monty. This is what your system should look like at the end. I think it makes sense this includes all the files that cfengine expects to consider. Kept, repaired, and not kept.

Yes, the output could be volumous and include many things that the user doesn't care about.
First thought is that maybe we need to have tags that will prevent promises from getting into this report. Then if we tagged all the stock promises  those could be excluded, but then you might actually want to see some of that and getting them into a report might be difficult. Or perhaps an option to exclude promises  based on a path,e.g. exclude promises for /var/cfenigne/ but that won't help with commands or processes or packages. Not sure exactly.

I don't love adding another manifest-full option. diff-show-full-files sounds more accurate if your only showing promises repaired.

**Comment by vpodzime** [comment]
> Manifest is the full monty.

This is what happens with the stock policy on a hub:
```
[root@hub vagrant]# cf-agent -KI --simulate=manifest-full > /tmp/manifest_full.out
[root@hub vagrant]# ll -h /tmp/manifest_full.out
-rw-r--r--. 1 root root 251M Jan 27 09:12 /tmp/manifest_full.out
```
I don't think this is useful in any way.

**Comment by olehermanse** [comment]
> > @vpodzime Not a big deal, but if the manifest includes kept, not kept and repaired, I'd prefer another name, like: `manifest-full` or simply `full`.
> > @nickanderson what do you think?
> 
> I don't think so.
> 
> To me, simulate diff is the short report showing just the delta. This one should I think show repaired and I think even not-kept as they are changes that couldn't be completed. They would be attempted during a non-simulation.
> 
> Manifest is the full monty. This is what your system should look like at the end. I think it makes sense this includes all the files that cfengine expects to consider. Kept, repaired, and not kept.
> 
> Yes, the output could be volumous and include many things that the user doesn't care about.
> First thought is that maybe we need to have tags that will prevent promises from getting into this report. Then if we tagged all the stock promises those could be excluded, but then you might actually want to see some of that and getting them into a report might be difficult. Or perhaps an option to exclude promises based on a path,e.g. exclude promises for /var/cfenigne/ but that won't help with commands or processes or packages. Not sure exactly.
> 
> I don't love adding another manifest-full option. diff-show-full-files sounds more accurate if your only showing promises repaired.

@nickanderson there are many words and interpretations here. In my opinion, diiff mode and manifest mode are not the same as repaired (changed) only vs everything mode. Diff means to show the changes as diffs. Manifest is to show a manifest of the final state (it can also be only repaired promises, it's just that we want it presented as the full final file contents/state, not diffs). I know the ticket stated that manifest should include the kept promises, but that was because of the particular user/use-case, which I believe does not use masterfiles.

As @vpodzime said, showing kept promises if you are using masterfiles is just not useful currently. (250+MB of logs). Having a separate manifest-full mode, which is essentially only useful for small policy sets / standalone policy files, and keeping the existing manifest mode useful makes perfect sense to me.

**Comment by larsewi** [comment]
[ cf-agent/cf-agent.c:694](https://github.com/cfengine/core/pull/4469/files#diff-a728d21fe93822246ac006cb79a16cf57a2fc501eb713d322dafb42726e042bbR694)

Should it be ...
```C
Log(LOG_LEVEL_ERR, "Missing argument for --simulate, 'manifest', 'manifest-full' or 'diff' required");
```
instead of ...
```C
Log(LOG_LEVEL_ERR, "Missing argument for --simulate, 'manifest' or 'diff' required");
```
?

**Review by larsewi — APPROVED** [review]
Awesome !

**Review by olehermanse — APPROVED** [review]

**Pull request merged**
