### PR TITLE
libntech bump and WriterWriteHelp()/ManPageWrite() backports

### PR DESCRIPTION
**Pull request by olehermanse**
Merge together:
https://github.com/cfengine/core/pull/4190
https://github.com/cfengine/nova/pull/1676

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5153/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5153/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5153/

**Comment by craigcomstock** [comment]
fr-tests failure is a bash error in FR_basic_setup.test, I will fix.

shellcheck shows the error:

```
/northern.tech/cfengine/system-testing/deployment_tests/new_tests$ shellcheck -x FR_tests/all_platforms/FR_basic_setup.test

In FR_tests/all_platforms/FR_basic_setup.test line 76:
if grep -P '(err|fail)' .$$.install.log >/dev/null; then
                                                    ^-- SC1009: The mentioned parser error was in this then clause.


In FR_tests/all_platforms/FR_basic_setup.test line 79:
  if grep -P 'scriptlet failed' .$$.install.log >/dev/null;
  ^-- SC1049: Did you forget the 'then' for this 'if'?
  ^-- SC1073: Couldn't parse this if expression.


In FR_tests/all_platforms/FR_basic_setup.test line 84:
  fi
  ^-- SC1050: Expected 'then'.
    ^-- SC1072: Unexpected keyword/token. Fix any mentioned problems and try again.
```

**Comment by craigcomstock** [comment]
Retrying fr-tests with my fix.
[Build Status](https://ci.cfengine.com/job/fr-tests/1364/)

**Pull request merged**
