### PR TITLE
Make sure program name is used as identifier in syslog

### PR DESCRIPTION
**Pull request by vpodzime**
Merge together:
https://github.com/cfengine/core/pull/4693
https://github.com/cfengine/enterprise/pull/661
https://github.com/cfengine/nova/pull/1766

### CODE REVIEW

**Comment by vpodzime** [comment]
jenkins: [Build Status](https://ci.cfengine.com/job/pr-pipeline/6653/)

**Comment by vpodzime** [comment]
jenkins: [Build Status](https://ci.cfengine.com/job/pr-pipeline/6655/)

**Comment by vpodzime** [comment]
jenkins: [Build Status](https://ci.cfengine.com/job/pr-pipeline/6668/)

**Review by olehermanse — APPROVED** [review]
Good job, thanks :)

**Pull request merged**
