### PR TITLE
ENT-5986: LMDB files are now created with correct permissions and group ownership (3.12)

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5155/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5155/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5155/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5156/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5156/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5156/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5157/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5157/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5157/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5165/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5165/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5165/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5167/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5167/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5167/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins exotics, I learned that `__Solaris__` is no such macro on gcc on Solaris. Instead need to use `sun || __sun`.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5169/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5169/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5169/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5176/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5176/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5176/

**Comment by craigcomstock** [comment]
will not use this strategy, instead wait for results of https://github.com/cfengine/masterfiles/pull/1768 and will cherry-pick.

**Pull request closed without merging**
