### PR TITLE
Use LMDB NOSYNC mode during test runs to improve performance.

### PR DESCRIPTION
**Pull request by kacfengine**

### CODE REVIEW

**Comment by kacfengine** [comment]
Don't bother reviewing this just yet, I'd like to see if it improves running time first, if not, then a review is wasted.

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
Nah, no difference, must be CPU or network bound.

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
This still made no difference.

**Comment by jimis** [comment]
reopening to send some tests run a bit later

**Comment by jimis** [comment]
Let's see if now it makes any difference!

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
HP-UX: 70 min
AIX:       67 min
Solaris10: 49 min

**Comment by kacfengine** [comment]
Master last finished in 58 min on HP-UX, IOW this has no effect.

**Comment by jimis** [comment]
HP-UX: 73 min
AIX: 62 min
Solaris10: 44 min

You're right, I guess the effect is minor.

**Comment by jimis** [comment]
I don't really believe that SYNC is as fast as NOSYNC, it should be much slower. 

I'd just explain that as our most frequent offender (cf_lock) is already NOSYNC, and the rest of the databases are seldom accessed.

**Pull request closed without merging**
