### PR TITLE
ENT-4653 ifelse() not evaluated in case of unresolved vars (3.12.x)

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5069/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5069/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5069/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5076/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5076/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5076/

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5101/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5101/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5101/

**Comment by craigcomstock** [comment]
unrelated test failure: https://tracker.mender.io/browse/ENT-5729

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5109/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5109/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5109/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please, with exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5115/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5115/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5115/

**Comment by craigcomstock** [comment]
Stopped the CI build. Problems with C unit tests on centos-5-x32. Investigating.

**Comment by craigcomstock** [comment]
Just re-ran pr-pipeline (https://ci.cfengine.com/job/pr-pipeline/5129/) on redhat 5 i386 and it passed:

```
09:15:37 testing-pr » PACKAGES_i386_linux_redhat_5 completed with result SUCCESS
```

To double-check I will run with exotics one more time since this is a C/evaluator change.

@cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5130/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5130/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5130/

**Pull request merged**
