### PR TITLE
CFE-3198: Added maximum_version and else macros

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4539/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4539/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4539/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4541/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4541/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4541/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4546/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4546/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4546/

**Comment by nickanderson** [comment]
I would pick to 3.15.x but maybe not 3.12.x

**Comment by basvandervlies** [comment]
looks good and very useful. Fot me it make sense to backport it to 3.12.x.  The macros are mostly used to prevent new code to ruin on old versions. The code is only to ignore or include the lines.

**Pull request merged**
