### PR TITLE
Reviewed and enabled/removed unit tests which were not running

### PR DESCRIPTION
**Pull request by olehermanse**
The TLS test has been disabled because it's written in a non-portable way, relies on openssl internals, and doesn't do mocking in a good way. The redirection test was mainly intended for hub platforms, but let's see if it works elsewhere. (I had to fix a few issues to get it running.)

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2724/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2724/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2724/

**Comment by vpodzime** [comment]
> Sure, I triggered a build:
> 
> [Build Status](https://ci.cfengine.com//job/pr-pipeline/2724/)

```
17:29:57   CC       map.lo
17:29:57 In file included from ./../../libntech/libutils/set.h:30:0,
17:29:57                  from ./../../libntech/libutils/file_lib.h:30,
17:29:57                  from ../../libntech/libutils/known_dirs.c:27:
17:29:57 ./../../libntech/libutils/json.h:176:5: error: unknown type name ‘pcre’
17:29:57      pcre *pattern, const char *regex, const char *data);
17:29:57      ^
```

**Comment by olehermanse** [comment]
Since the mingw build failed, I split out some changes to this PR: https://github.com/cfengine/core/pull/3824

**Comment by olehermanse** [comment]
@cf-bottom let's do another jenkins build

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2728/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2728/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2728/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2729/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2729/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2729/

**Comment by olehermanse** [comment]
@vpodzime I disabled `redirection_test` for windows builds. (There were other issues than just the include order that you pointed out). Seems to be green now. Please re-review.

**Comment by olehermanse** [comment]
@cf-bottom I'd like a jenkins build with exotics as well, please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2732/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2732/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2732/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2733/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2733/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2733/

**Pull request merged**
