### PR TITLE
ENT-4921: Removed stime_range and ttime_range constraints from promise hash (3.12)

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins packages please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2808/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2808/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2808/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2971/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2971/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2971/

**Comment by craigcomstock** [comment]
5 hours and no results. Killed that and restart.
@cf-bottom jenkins again please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2974/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2974/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2974/

**Comment by olehermanse** [comment]
@cf-bottom Try one more time in jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2979/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2979/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2979/

**Pull request merged**
