### PR TITLE
cf-remote fixes

### PR DESCRIPTION
**Pull request by vpodzime**
The first couple commits are from #3513, the rest are fixes for issues I encountered when trying to use *cf-remote* with DO droplets.

Wait for #3513.

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @olehermanse can review this?

**Comment by olehermanse** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging dabd29ca531c96da60214d11b4ef444d23bd93c1 into 2bb6a28c23678b27e4667ac1f0d1b9b101bc5e51 - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-829527735d6491e3941c1bdd86280a3db9cc7387)

**new alerts:**

* 1 for Cyclic import

**fixed alerts:**

* 1 for Cyclic import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by olehermanse** [comment]
@vpodzime #3513 is merged, please rebase.

**Comment by olehermanse** [comment]
Closing in favor of #3522

**Pull request closed without merging**
