### PR TITLE
[3.12.x] win pkg module support

### PR DESCRIPTION
**Pull request by vpodzime**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @olehermanse can review this?

**Comment by Lex-2008** [comment]
testbuild: https://ci.cfengine.com/job/pr-pipeline/2370/

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2397/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2397/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2397/

**Comment by vpodzime** [comment]
> Wait for green in jenkins.

I believe it is as green as it can be.

**Comment by vpodzime** [comment]
@Lex-2008 merge this once the other windows package module pieces are ready.

**Comment by Lex-2008** [comment]
merged together with https://github.com/cfengine/masterfiles/pull/1368

**Pull request merged**
