### PR TITLE
readdata() also auto-detects .yml files as YAML

### PR DESCRIPTION
**Pull request by cobaugh**
.yml seems to be slightly preferred over .yaml for yaml files these days. This change makes readdata() auto-detect .yml files as YAML.

### CODE REVIEW

**Comment by tzz** [comment]
This looks great.

**Comment by jimis** [comment]
Looks good, thanks! Please squash the two commits and add a `Changelog: title` tag in the commit message, so that the change is visible in the changelog. (See `HACKING.md` for details on how this works)

**Comment by cobaugh** [comment]
Rebased and added Changelog: Title

**Comment by jimis** [comment]
Thanks! Merging manually because a foreign commit crept in this pull request.

**Comment by jimis** [comment]
Superseded by #2850.

**Pull request closed without merging**
