### PR TITLE
CFE-3365/master: Extended strftime example to use more templates

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
I considered re-ordering the lines to match order of output, but then decided it didn't matter. If you want me to re-order them, I willl, else, I won't.

All that same information is listed on the doc page currently, and i would delete it, leaving just the example which has the added benefit of showing actual examples of each, which i find quite handy when i am looking things up.

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5158/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5158/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5158/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5159/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5159/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5159/

**Pull request merged**
