### PR TITLE
CFE-3006: Moved known_dirs to libutils - 3.12.x

### PR DESCRIPTION
**Pull request by karlhto**
Also moved some windows-only things out from `cf-windows-functions`. `known_dirs` should not depend on something that uses `libpromises`-specific things.

Ticket: CFE-3006
Changelog: None

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @olehermanse can review this?

**Comment by karlhto** [comment]
@cf-bottom Jenkins with exotics

**Comment by karlhto** [comment]
@cf-bottom Jenkins with exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2267/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2267/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2267/

**Comment by karlhto** [comment]
@cf-bottom Jenkins with exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2268/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2268/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2268/

**Comment by karlhto** [comment]
@cf-bottom Jenkins with exotics again

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2269/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2269/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2269/

**Comment by karlhto** [comment]
@cf-bottom Jenkins with exotics
Maybe I should learn to compile before committing..

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2270/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2270/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2270/

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2274/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2274/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2274/

**Pull request merged**
