### PR TITLE
Change: Log level for keeping verbatim JSON to DEBUG

### PR DESCRIPTION
**Pull request by nickanderson**
Jira #CFE-2141
Changelog: Title

### CODE REVIEW

**Comment by nickanderson** [comment]
ping @jimis and or @kacf

**Comment by kacf** [comment]
Agree, it doesn't seem like an error to keep the value, but rather expected behavior.

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
Cherry-picked to 3.9.x as well.

**Pull request merged**
