### PR TITLE
Update libntech to latest

### PR DESCRIPTION
**Pull request by larsewi**
Ticket: None
Changelog: None
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

### CODE REVIEW

**Comment by larsewi** [comment]
@cf-bottom Jenkins please !

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6364/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6364/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6364/

**Review by olehermanse — APPROVED** [review]
Good, thanks.

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
