### PR TITLE
ENT-6042 Wait for background processes before generating reports

### PR DESCRIPTION
**Pull request by craigcomstock**
Reports generation only happens if there is exactly one
'cf-agent' process running (to avoid corruptions in the reporting
data). If some promise in the policy uses an action policy with
'background => true', there might still be a forked child process
evaluating the promise when the main process reaches the point
when it wants to generate reports. In such cases, it is important
that the main process waits for the forked child processes.

Ticket: ENT-6042
Changelog: Promises with 'action => bg()' no longer break reporting data
(cherry picked from commit 3d9abd5cb4a21a920d5c6c9c6e25946533e132e9)

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5374/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5374/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5374/

**Comment by nickanderson** [comment]
Actually, I found a small issue while testing this. Please see ticket for details.

**Comment by vpodzime** [comment]
Duplicate of #4252

**Pull request closed without merging**
