### PR TITLE
ENT-8824: Adjust selinux policy for RHEL 9

### PR DESCRIPTION
**Pull request by craigcomstock**
Needed for redhat 9 but maybe will break redhat 8?

Ticket: ENT-8824
Changelog: title

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @vpodzime can review this?

**Comment by craigcomstock** [comment]
retry rhel8 and rhel9 without deployment tests:

[Build Status](https://ci.cfengine.com/job/pr-pipeline/8791/)

**Comment by craigcomstock** [comment]
retry with a bit less fixes, to debug bootstrap issues [Build Status](https://ci.cfengine.com/job/pr-pipeline/8806/)

**Comment by craigcomstock** [comment]
@cf-bottom lets test this in jenkins. thanks.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8808/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8808/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8808/

**Comment by craigcomstock** [comment]
@vpodzime I did some more testing today and found that this more minimal set of changes seems to work fine on both rhel9 agent and rhel8 hub.

**Review by vpodzime — APPROVED** [review]
ACK

**Comment by craigcomstock** [comment]
Summary of pending issues in CI:

- fr-tests and sequential-tests failed with flaky ssh connections (known flakes)
- redhat 6 and suse 11 testing-pr failed due to `Bad configuration option: PubkeyAcceptedKeyTypes` during retrieval of lcov in `pkg-get-src`
- redhat 9 testing-pr failed in `./17_packages/10_new/unsafe/the_great_package_test.cf`

Will work on resolving these issues.

**Comment by craigcomstock** [comment]
debug great package test: CI run to see results of this change: [Build Status](https://ci.cfengine.com/job/pr-pipeline/8819/)

**Comment by vpodzime** [comment]
> * redhat 9 testing-pr failed in `./17_packages/10_new/unsafe/the_great_package_test.cf`
> 
> 
> merge together:

I would actually vote for merging this right away. It doesn't break anything so no need to hold it off.

**Comment by craigcomstock** [comment]
> > * redhat 9 testing-pr failed in `./17_packages/10_new/unsafe/the_great_package_test.cf`
> > 
> > merge together:
> 
> I would actually vote for merging this right away. It doesn't break anything so no need to hold it off.

Cool. I just ran with some pointed debug for the great package test and saw that the local repo is properly setup so not sure where the failure is now. :(

```
2022-11-01T18:12:43+0000     info: Linked files "/home/jenkins/workspace/testing-pr/label/PACKAGES_x86_64_linux_redhat_9/cfengine-masterfiles-3.21.0a.28c90e96e/tests/acceptance/workdir/__17_packages_10_new_unsafe_the_great_package_test_cf/bin/cfengine-selected-python" -> "/usr/bin/python3"
R: /test-repos dir exists
R: /etc/yum.repos.d/test-repository.repo exists
R: -------------------------------------
R: 0.2631578947368421%: Starting test case "from_absent_to_absent___promise_policy_absent"
R: -------------------------------------
2022-11-01T18:12:43+0000     info: Executing "no timeout" ... "/bin/rpm -e --allmatches test-package-alpha "
2022-11-01T18:12:43+0000    error: Finished command related to promiser "/bin/rpm -e --allmatches test-package-alpha " -- an error occurred, returned 1
2022-11-01T18:12:43+0000   notice: Q: ".../bin/rpm -e --a": error: package test-package-alpha is not installed
```

I will see about merging. :+1:

**Comment by craigcomstock** [comment]
cherry picked back to 3.18.x: https://github.com/cfengine/core/pull/5092
and 3.15.x: https://github.com/cfengine/core/pull/5091

But not exactly sure if we should. @vpodzime ?

**Pull request merged**
