### PR TITLE
Redmine#6480: skip url_get acceptance tests when !feature_curl

### PR DESCRIPTION
**Pull request by tzz**
@jimis as requested in #2352

### CODE REVIEW

**Comment by tzz** [comment]
Fortunately `@if` was not necessary...

**Comment by jimis** [comment]
Thanks Ted, a nice example of the new feature!

**Comment by jimis** [comment]
Works like a charm, thanks Ted!

**Comment by jimis** [comment]
Cherry-picked to 3.8.x.

**Comment by tzz** [comment]
AND NOW WE DANCE

:dancer:

**Comment by nickanderson** [comment]
Who ha!

**Comment by jimis** [comment]
I'm sensing some over-excitement in the air ...

**Pull request merged**
