### PR TITLE
ENT-5125 Changed cf-hub.service to 'Wants' cf-postgres.service

### PR DESCRIPTION
**Pull request by craigcomstock**
Requires in this dependency breaks HA because there systemd will
not be responsible for postgres start/stop and so postgres service
will fail.

Ticket: ENT-5125 (follow-up)
Changelog: title

Added related PR to masterfiles to sync between here and there (here being the master/good copy). https://github.com/cfengine/masterfiles/pull/1699

### CODE REVIEW

**Comment by vpodzime** [comment]
The *wip...* commit suggests this is a WIP PR. Please squash/reword the commit for a review.

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4982/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4982/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4982/

**Comment by craigcomstock** [comment]
@vpodzime I just tried the pr build of this with cfe-ent-ha setup and such and things worked "fine". But I wasn't sure exactly how to test.

I also noticed that at least 3.15.x has the "wrong" code:

https://github.com/cfengine/core/commit/fa179e118f3026854ca4240f64c3decd3c2bcf78

3.15.1 tag has Requires and not Wants as it seems should be correct.

https://github.com/cfengine/core/blob/3.15.1/misc/systemd/cf-hub.service.in

**Comment by vpodzime** [comment]
I can retest, but it didn't work for me previously on systemd-based systems.

**Comment by vpodzime** [comment]
If I run the setup script, I get this on the passive node:
```
● cf-apache.service - CFEngine Enterprise Webserver
   Loaded: loaded (/usr/lib/systemd/system/cf-apache.service; enabled; vendor preset: disabled)
   Active: inactive (dead)

Apr 23 13:39:41 node2 systemd[1]: Dependency failed for CFEngine Enterprise Webserver.
Apr 23 13:39:41 node2 systemd[1]: Job cf-apache.service/start failed with result 'dependency'.
Apr 23 13:40:23 node2 systemd[1]: Dependency failed for CFEngine Enterprise Webserver.
Apr 23 13:40:23 node2 systemd[1]: Job cf-apache.service/start failed with result 'dependency'.
Apr 23 13:40:33 node2 systemd[1]: Dependency failed for CFEngine Enterprise Webserver.
Apr 23 13:40:33 node2 systemd[1]: Job cf-apache.service/start failed with result 'dependency'.
```
There seems to be no functional problem because `httpd` is still running for some reason (started by `cf-agent` I guess? And also the `cf-postgres` service is reported as `running` even in the HA setup, I guess the cluster resource agent uses the service properly.

**Comment by vpodzime** [comment]
So I think both this and the related JIRA ticket can be closed. We may get back to it in the future.

**Comment by vpodzime** [comment]
So I think both this and the related JIRA ticket can be closed. We may get back to it in the future.

**Comment by craigcomstock** [comment]
> So I think both this and the related JIRA ticket can be closed. We may get back to it in the future.

Ok. Will close this PR then. Thanks. :)

**Pull request closed without merging**
