### PR TITLE
Fixed memory leak in users promises

### PR DESCRIPTION
**Pull request by olehermanse**
Found by running valgrind agent run on a demo hub.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Review by vpodzime — APPROVED** [review]
ACK

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5713/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5713/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5713/

**Comment by olehermanse** [comment]
Cherry-pick: https://github.com/cfengine/core/pull/4355

**Comment by olehermanse** [comment]
Introduced in: https://github.com/cfengine/core/pull/4126

**Pull request merged**
