### PR TITLE
CFE-2886: Pass large structs by pointer, not value

### PR DESCRIPTION
**Pull request by olehermanse**
Large structs like TransactionContext, DefineClasses
and stat should be passed by pointer.

Reported by LGTM:
https://lgtm.com/rules/2163210742/

Merge together:
https://github.com/cfengine/core/pull/3310
https://github.com/cfengine/enterprise/pull/440

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1327/)

https://ci.cfengine.com/job/pr-pipeline/1327/

**Comment by olehermanse** [comment]
This pull request **introduces 1 alert** when merging ee3a9adfab5b7f65f4ca8b5bba2fc3085b535a8b into 93428bfec557c23c1b977940a73713ad3687cd36 - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-e6caf98845db568b16065e22d0cbeecee96b15a8)

**new alerts:**

* 1 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1329/)

https://ci.cfengine.com/job/pr-pipeline/1329/

**Comment by olehermanse** [comment]
This pull request **introduces 1 alert** when merging 99f892e46cd637f3bfa1355c279793fdb802d5de into 93428bfec557c23c1b977940a73713ad3687cd36 - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-777e7d1578be5f19ba6b4390602f08d3464586a2)

**new alerts:**

* 1 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1331/)

https://ci.cfengine.com/job/pr-pipeline/1331/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1332/)

https://ci.cfengine.com/job/pr-pipeline/1332/

**Pull request merged**
