### PR TITLE
ENT-4777: Added function to trim trailing CRLF from a line of CSV data

### PR DESCRIPTION
**Pull request by olehermanse**
Will be used in reporting.

### CODE REVIEW

**Comment by olehermanse** [comment]
@vpodzime I think we can review and merge this one, and hold off on the related nova PR until 3.14 is out.

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2699/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2699/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2699/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2700/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2700/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2700/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2701/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2701/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2701/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2702/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2702/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2702/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2704/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2704/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2704/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2705/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2705/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2705/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2706/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2706/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2706/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2707/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2707/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2707/

**Pull request merged**
