### PR TITLE
Use stdout in LogToConsole

### PR DESCRIPTION
**Pull request by amousset**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @olehermanse can review this?

**Comment by karlhto** [comment]
I think removing `output_file` and explicitly using `stdout` is more descriptive. Doesn't seem like it was intended that the value would change, at least according to this:
```
    FILE *output_file = stdout; // Messages should ALL go to stdout else they are disordered
```

@olehermanse @vpodzime Either of you know? Seems like the variable was added by Mark in 2014.

**Comment by vpodzime** [comment]
> @olehermanse @vpodzime Either of you know?

No idea. Looks like over-engineering to me. Let's get rid of it.

**Comment by nickanderson** [comment]
Ping @olehermanse. @amousset has pushed since your last comment.

**Pull request merged**
