### PR TITLE
CFE-3297: Make the 'Variable' struct private

### PR DESCRIPTION
**Pull request by vpodzime**
Merge together:
https://github.com/cfengine/core/pull/4124
https://github.com/cfengine/enterprise/pull/607

### CODE REVIEW

**Comment by vpodzime** [comment]
> **new alerts:**
> 
>     * 2 for Pointer argument is dereferenced without checking for NULL

Just a piece of code I moved around.

**Comment by olehermanse** [comment]
@cf-bottom can you try to build this in jenkins, please?

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4952/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4952/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4952/

**Comment by vpodzime** [comment]
> [Build Status](https://ci.cfengine.com//job/pr-pipeline/4952/)

As green as it could be now. :disappointed:

**Pull request merged**
