### PR TITLE
redmine#7113: agent_expireafter

### PR DESCRIPTION
**Pull request by jimis**
Change from one week, down to two hours, see redmine#7113 for more
details.

Also changed LOG_LEVEL_ERR to LOG_LEVEL_NOTICE since this isn't some
kind of failure.

### CODE REVIEW

**Comment by kacfengine** [comment]
Really!? It was one week? This could have a dramatic impact on agent pileup situations. I always thought that it was two hours and the expireafter functionality which is supposed to kill stuck agents simply didn't work. At least with this change it will have a chance of working.

**Comment by kacfengine** [comment]
Ah, wait this is ``agent_expireafter``, not the one for promises. But still.

**Comment by kacfengine** [comment]
trigger build

**Comment by jimis** [comment]
Dammit a bunch of platforms failed in jenkins!

**Comment by jimis** [comment]
Actually one platform failed, and it seems unrelated. Merging!

**Pull request merged**
