### PR TITLE
Use Fedora 34 as a base image for static checks

### PR DESCRIPTION
**Pull request by vpodzime**
Revealed some new issues in our code right away:
https://github.com/cfengine/core/commit/acef0163ba8bdab1a8d13ea0ce7527acfee9d288
https://github.com/cfengine/libntech/pull/132
https://github.com/cfengine/libntech/pull/133

### CODE REVIEW

**Comment by vpodzime** [comment]
Unfortunately, containers suck so this cannot be merged yet. Details:

**Comment by vpodzime** [comment]
> IOW, the container behaves differently depending on where I run it. And `test -x /` is one of the things `./configure` does to make sure it has a sane environment.

For those curious: https://bugzilla.redhat.com/show_bug.cgi?id=1900021
(but *The workaround has been categorically rejected by kernel developers and glibc developers alike. Work is under way to address this in runc and potentially libseccomp.* so... :man_shrugging:)

**Review by olehermanse — CHANGES_REQUESTED** [review]
LGTM, but we cannot merge it until it passes in Jenkins.

**Comment by vpodzime** [comment]
Superseded by #4872

**Pull request closed without merging**
