### PR TITLE
Add: Test for bundlesmatching tags in params 3-n

### PR DESCRIPTION
**Pull request by nickanderson**
Ref: https://dev.cfengine.com/issues/7192

### CODE REVIEW

**Comment by kacfengine** [comment]
The docs are not 100% clear on this, but my take on it is that the tag search is ANDed, hence you should only find one bundle, the one marked with both tags. Your test case implies that the results are ORed together, IOW find bundles that have *any* of the tags.

Perhaps @tzz has an opinion on this.

**Comment by kacfengine** [comment]
Relevant section in the docs: "When any tags are given, only the bundles with those tags are returned."

**Comment by tzz** [comment]
It's AND, because otherwise there would be no way to specify AND (except by calling `intersection`).

To get OR, call `bundlesmatching` again and merge the results.

**Comment by tzz** [comment]
The docs should probably clarify this...

**Comment by kacfengine** [comment]
Sounds like the test case is wrong then. Does the bug really exist in that case? Closing for now, discussion can continue in the ticket.

**Pull request closed without merging**
