### PR TITLE
Associate comments with variables and classes

### PR DESCRIPTION
**Pull request by vpodzime**
Missing bits:
- [x] trivial acceptance tests checking the `comment` attribute propagation from `vars` and `classes` promises

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6601/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6601/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6601/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6636/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6636/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6636/

**Review by larsewi — DISMISSED** [review]
Awesome stuff! Many nice improvements :100:

**Review by olehermanse — APPROVED** [review]
Great! 🚀

**Review by larsewi — APPROVED** [review]
ACK

**Pull request merged**
