### PR TITLE
GH Actions: Add CIFuzz integration

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz, on which cfengine already runs (although there is only a single fuzzer for now)

### CODE REVIEW

**Comment by vpodzime** [comment]
> ** CIFuzz / Fuzzing (pull_request) ** Successful in 7m

Well, it seems to be triggering. But I see this in the details:
```
 ==21==ERROR: AddressSanitizer: stack-overflow on address 0x7fffd6877ff8 (pc 0x00000054c989 bp 0x7fc18ee75000 sp 0x7fffd6878000 T0)
SCARINESS: 10 (stack-overflow)
    <empty stack>

SUMMARY: AddressSanitizer: stack-overflow
==21==ABORTING
```
which brings two questions:
1. Why the status says *success* when it actually failed?
2. And how do I actually find the exact case that triggered the failure so that I can reproduce it locally and fix it?

Thanks for this!

**Comment by DavidKorczynski** [comment]
> > ** CIFuzz / Fuzzing (pull_request) ** Successful in 7m
> 
> Well, it seems to be triggering. But I see this in the details:
> 
> ```
>  ==21==ERROR: AddressSanitizer: stack-overflow on address 0x7fffd6877ff8 (pc 0x00000054c989 bp 0x7fc18ee75000 sp 0x7fffd6878000 T0)
> SCARINESS: 10 (stack-overflow)
>     <empty stack>
> 
> SUMMARY: AddressSanitizer: stack-overflow
> ==21==ABORTING
> ```
> 
> which brings two questions:
> 
> 1. Why the status says _success_ when it actually failed?
> 2. And how do I actually find the exact case that triggered the failure so that I can reproduce it locally and fix it?
> 
> Thanks for this!

I was also under the impression the check would fail when a crash happens - @jonathanmetzman can you advice here?

**Comment by jonathanmetzman** [comment]
> > > ** CIFuzz / Fuzzing (pull_request) ** Successful in 7m
> > 
> > 
> > Well, it seems to be triggering. But I see this in the details:
> > ```
> >  ==21==ERROR: AddressSanitizer: stack-overflow on address 0x7fffd6877ff8 (pc 0x00000054c989 bp 0x7fc18ee75000 sp 0x7fffd6878000 T0)
> > SCARINESS: 10 (stack-overflow)
> >     <empty stack>
> > 
> > SUMMARY: AddressSanitizer: stack-overflow
> > ==21==ABORTING
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which brings two questions:
> > 
> > 1. Why the status says _success_ when it actually failed?
> > 2. And how do I actually find the exact case that triggered the failure so that I can reproduce it locally and fix it?
> > 
> > Thanks for this!
> 
> I was also under the impression the check would fail when a crash happens - @jonathanmetzman can you advice here?

CIFuzz only reports novel crashes. Crashes that reproduce on a build that is already running on OSS-Fuzz are not reported (because they were not introduced by the PR).
We might be able to make this behavior configurable if you need, but i think it makes sense for most cases even if it is a bit confusing some times.

I can tell this is what happened, because of the log line:
```
The crash is reproducible on previous build. Code change (pr/commit) did not introduce crash.

**Comment by DavidKorczynski** [comment]
Thanks a lot for the clarification @jonathanmetzman !

**Comment by vpodzime** [comment]
Makes sense, thanks!

**Comment by vpodzime** [comment]
I'm still interested in the answer to this question, though:
> And how do I actually find the exact case that triggered the failure so that I can reproduce it locally and fix it?

TBH, I don't even know where to find the reproducer for the crash that's already present.

**Comment by DavidKorczynski** [comment]
Your email need to be in the `project.yaml` of cfengine at oss-fuzz, which it is: https://github.com/google/oss-fuzz/blob/master/projects/cfengine/project.yaml

Then, you need to visit "https://oss-fuzz.com" where the interface will direct you. You need to log on with your email from the `project.yaml` by way of Google auth so the email must be linked to a Google account.

Alterntatively, you will have received an email at some point with the subject "Issue XXXXX  in oss-fuzz: cfengine:XXXXX" which will have information on the issue as well

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
