### PR TITLE
Redmine#5646: add "enable" to service_policy menu

### PR DESCRIPTION
**Pull request by tzz**
Trivial change.  See https://dev.cfengine.com/issues/5646

### CODE REVIEW

**Comment by tzz** [comment]
ping

**Comment by tzz** [comment]
ping?

**Comment by tzz** [comment]
ping?  This is very safe.

**Comment by tzz** [comment]
Docs are in https://github.com/cfengine/core/pull/2161

**Comment by kacfengine** [comment]
Yes, sorry I don't know how I managed to overlook this for so long!

**Comment by tzz** [comment]
Thank you!

**Pull request merged**
