### PR TITLE
CFE-4023: Updated libntech submodule for autotools fix

### PR DESCRIPTION
**Pull request by craigcomstock**
Fixed --with-libxml2=no case in configure.ac

Ticket: CFE-4023
Changelog: none

### CODE REVIEW

**Comment by larsewi** [comment]
@cf-bottom Jenkins please :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9208/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9208/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9208/

**Review by olehermanse — APPROVED** [review]
LGTM, as long as it passes CI.

**Review by larsewi — APPROVED** [review]

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9255/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9255/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9255/

**Pull request merged**
