### PR TITLE
redmine#7242: Avoid writing hundreds of megabytes by preserving sparse areas in LMDB files.

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
Do not merge, it's only opened to check jenkins.

**Comment by jimis** [comment]
trigger build

**Comment by kacfengine** [comment]
+1!

**Comment by kacfengine** [comment]
It shaves almost 25 min off the testing time on HP-UX, nice!

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
@kacfengine the total test time was 3:14, even slower for some reason, before even reaching the acceptance tests!

**Comment by kacfengine** [comment]
?

On HP-UX the test time was 67 min, better than ever before. This is the one I'm looking at: http://jenkins.usdc.cfengine.com/view/Pull%20requests/job/testing-enterprise-pr_core/149/label=PACKAGES_ia64_hpux_11.23/consoleFull

**Comment by jimis** [comment]
Here are the last lines of that log for me:
```
03:14:30.538 
03:14:30.538 Deleting project workspace... 
03:14:30.735 done
03:14:30.735 
03:14:30.755 Finished: UNSTABLE
```

It's probably different from what you're seeing because I've set Jenkins to display *elapsed time*. But looking a bit better it seems that it started the run at 2:07 so total time is indeed about one hour! The initial delay is probably because of already queued jobs.

**Comment by kacfengine** [comment]
Yep, so this looks pretty good then!

**Comment by jimis** [comment]
@kacfengine then if you can review the code and merge at will!

**Comment by jimis** [comment]
BTW I was hoping to put `memcchr()` in libcompat, since it exists on some BSDs, but would prefer to avoid spending more time.

**Comment by kacfengine** [comment]
Yeah, let's merge it for now, we really need the speed optimization. Looks good to me!

**Comment by kacfengine** [comment]
Cherry-picked to 3.7.x as well.

**Comment by jimis** [comment]
YES!

**Comment by jimis** [comment]
Cherry-picking to 3.6.x

**Pull request merged**
