### PR TITLE
CFE-2724: The `arglist` attribute now preserves spaces in arguments

### PR DESCRIPTION
**Pull request by larsewi**
Merge together with:
- https://github.com/cfengine/enterprise/pull/775
- https://github.com/cfengine/masterfiles/pull/2804

### CODE REVIEW

**Comment by larsewi** [comment]
@cf-bottom Jenkins please :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10068/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10068/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10068/

**Comment by larsewi** [comment]
@cf-bottom jenkins please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10121/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10121/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10121/

**Review by vpodzime — COMMENTED** [review]
Looks good to me otherwise, just small things.

**Review by vpodzime — APPROVED** [review]
Looks good to me now. :crossed_fingers: for the tests to pass

**Comment by larsewi** [comment]
@cf-bottom Jenkins please :)

**Comment by larsewi** [comment]
@cf-bottom Jenkins please :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10149/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10149/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10149/

**Comment by larsewi** [comment]
@cf-bottom Jenkins please :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10155/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10155/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10155/

**Review by nickanderson — DISMISSED** [review]
I thought I heard you say that preservation of white-space only works for commands that are not executed with a shell. Is that true? If so, can you amend your 4th commit to say so?

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10160/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10160/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10160/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10162/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10162/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10162/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10164/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10164/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10164/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10169/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10169/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10169/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10171/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10171/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10171/

**Comment by larsewi** [comment]
@cf-bottom Jenkins please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10176/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10176/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10176/

**Comment by larsewi** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/10202/)

**Comment by larsewi** [comment]
Ping @vpodzime, @nickanderson

**Review by vpodzime — APPROVED** [review]
Looks good to me. @nickanderson may disagree, but I believe people should read changelogs and not rely on a clearly buggy behavior.

**Pull request merged**
