### PR TITLE
ENT-4921: Removed stime_range and ttime_range constraints from promise hash

### PR DESCRIPTION
**Pull request by craigcomstock**
This may be causing reporting failures in some cases.

Changelog: title
Ticket: ENT-4921

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2790/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2790/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2790/

**Comment by olehermanse** [comment]
I modified the policy from ticket like this:

```
root@ip-172-31-36-156:~# cat reaper.cf
bundle agent main
{
  meta:
    "description" string => "Try to stop agent pile-ups from happenning.";

  processes:
    "python3"
      signals => { "kill" },
      process_select => old_agents;
}

body process_select old_agents
{
  # Processes started between 1 day ago and 1 second ago,
  # This causes the promise to have a different hash each agent execution
  stime_range => irange(ago(0,0,0,1,0,0), ago(0,0,0,0,0,1));
  process_result => "stime";
}
root@ip-172-31-36-156:~#
```

Master package:

```
root@ip-172-31-38-70:~# python3 -c "import time; time.sleep(300);" &
[1] 21506
root@ip-172-31-38-70:~# python3 -c "import time; time.sleep(300);" &
[2] 21507
root@ip-172-31-38-70:~# python3 -c "import time; time.sleep(300);" &
[3] 21509
root@ip-172-31-38-70:~# python3 -c "import time; time.sleep(300);" &
[4] 21546
root@ip-172-31-38-70:~# python3 -c "import time; time.sleep(300);" &
[5] 21547
root@ip-172-31-38-70:~# python3 -c "import time; time.sleep(300);" &
[6] 21548
root@ip-172-31-38-70:~# python3 -c "import time; time.sleep(300);" &
[7] 21549
root@ip-172-31-38-70:~# cf-agent -KI reaper.cf && cf-agent  && cat /var/cfengine/state/diff/execution_log.diff | grep python
    info: Signalled 'kill' (9) to process 21506 (root                           21506 20480 21506  0.0  0.0  28468   0      9268    1 15:37       01:08 00:00:00 python3 -c import time; time.sleep(300);)
    info: Signalled 'kill' (9) to process 21507 (root                           21507 20480 21507  0.0  0.0  28468   0      9476    1 15:37       01:06 00:00:00 python3 -c import time; time.sleep(300);)
    info: Signalled 'kill' (9) to process 21509 (root                           21509 20480 21509  0.0  0.0  28468   0      9268    1 15:37       01:05 00:00:00 python3 -c import time; time.sleep(300);)
    info: Signalled 'kill' (9) to process 21546 (root                           21546 20480 21546  0.0  0.0  28468   0      9268    1 15:37       01:03 00:00:00 python3 -c import time; time.sleep(300);)
    info: Signalled 'kill' (9) to process 21547 (root                           21547 20480 21547  0.0  0.0  28468   0      9544    1 15:37       01:03 00:00:00 python3 -c import time; time.sleep(300);)
    info: Signalled 'kill' (9) to process 21548 (root                           21548 20480 21548  0.0  0.0  28468   0      9472    1 15:37       01:02 00:00:00 python3 -c import time; time.sleep(300);)
    info: Signalled 'kill' (9) to process 21549 (root                           21549 20480 21549  0.0  0.0  28468   0      9460    1 15:37       01:01 00:00:00 python3 -c import time; time.sleep(300);)
[1]   Killed                  python3 -c "import time; time.sleep(300);"
[2]   Killed                  python3 -c "import time; time.sleep(300);"
[3]   Killed                  python3 -c "import time; time.sleep(300);"
[4]   Killed                  python3 -c "import time; time.sleep(300);"
[5]   Killed                  python3 -c "import time; time.sleep(300);"
[6]-  Killed                  python3 -c "import time; time.sleep(300);"
[7]+  Killed                  python3 -c "import time; time.sleep(300);"
1569425785,1,78654660a48d047eaf5ce940b070c12db5514d880fa89c22648971032288996d,reaper.cf,b15bbb63bd4f95f15e528e11d7a4c10d3d0b6b7e,99,default,main,processes,python3,/default/main/processes/'python3'[1],,[],[],7,SHA=6653141935468ee23874c0df09bf939d6a4ec3a86bd0be0a50384aadae2585f0
1569425797,2,78654660a48d047eaf5ce940b070c12db5514d880fa89c22648971032288996d,reaper.cf,b15bbb63bd4f95f15e528e11d7a4c10d3d0b6b7e,99,default,main,processes,python3,/default/main/processes/'python3'[1],,[],[],7,SHA=6653141935468ee23874c0df09bf939d6a4ec3a86bd0be0a50384aadae2585f0
1569425797,1,7adb278f621686b6127aee533248735e81aecbe931cfc5bd1bdb9f196b6498ee,reaper.cf,b15bbb63bd4f95f15e528e11d7a4c10d3d0b6b7e,99,default,main,processes,python3,/default/main/processes/'python3'[1],,[],[],7,SHA=6653141935468ee23874c0df09bf939d6a4ec3a86bd0be0a50384aadae2585f0
1569425804,2,7adb278f621686b6127aee533248735e81aecbe931cfc5bd1bdb9f196b6498ee,reaper.cf,b15bbb63bd4f95f15e528e11d7a4c10d3d0b6b7e,99,default,main,processes,python3,/default/main/processes/'python3'[1],,[],[],7,SHA=6653141935468ee23874c0df09bf939d6a4ec3a86bd0be0a50384aadae2585f0
1569425804,1,38e73b0364cbbfb3b0096da6cc067648f29edb42e5a8af138d6453f1cb4994ee,reaper.cf,b15bbb63bd4f95f15e528e11d7a4c10d3d0b6b7e,99,default,main,processes,python3,/default/main/processes/'python3'[1],,[],[],7,SHA=6653141935468ee23874c0df09bf939d6a4ec3a86bd0be0a50384aadae2585f0
1569425932,2,38e73b0364cbbfb3b0096da6cc067648f29edb42e5a8af138d6453f1cb4994ee,reaper.cf,b15bbb63bd4f95f15e528e11d7a4c10d3d0b6b7e,99,default,main,processes,python3,/default/main/processes/'python3'[1],,[],[],7,SHA=6653141935468ee23874c0df09bf939d6a4ec3a86bd0be0a50384aadae2585f0
1569425932,1,b614f5cf141e4db78028158405f72369ae7a47b08d015dce43c7a1cdac0a8b7c,reaper.cf,b15bbb63bd4f95f15e528e11d7a4c10d3d0b6b7e,114,default,main,processes,python3,/default/main/processes/'python3'[1],,[],"[""Signalled 'kill' (9) to process 21509 (root                           21509 20480 21509  0.0  0.0  28468   0      9268    1 15:37       01:05 00:00:00 python3 -c import time; time.sleep(300);)"",""Signalled 'kill' (9) to process 21546 (root                           21546 20480 21546  0.0  0.0  28468   0      9268    1 15:37       01:03 00:00:00 python3 -c import time; time.sleep(300);)"",""Signalled 'kill' (9) to process 21547 (root                           21547 20480 21547  0.0  0.0  28468   0      9544    1 15:37       01:03 00:00:00 python3 -c import time; time.sleep(300);)"",""Signalled 'kill' (9) to process 21548 (root                           21548 20480 21548  0.0  0.0  28468   0      9472    1 15:37       01:02 00:00:00 python3 -c import time; time.sleep(300);)"",""Signalled 'kill' (9) to process 21549 (root                           21549 20480 21549  0.0  0.0  28468   0      9460    1 15:37       01:01 00:00:00 python3 -c import time; time.sleep(300);)""]",7,SHA=6653141935468ee23874c0df09bf939d6a4ec3a86bd0be0a50384aadae2585f0
root@ip-172-31-38-70:~#
```


Package from this PRs Jenkins job:

```
root@ip-172-31-36-156:~# python3 -c "import time; time.sleep(300);" &
[1] 21362
root@ip-172-31-36-156:~# python3 -c "import time; time.sleep(300);" &
[2] 21363
root@ip-172-31-36-156:~# python3 -c "import time; time.sleep(300);" &
[3] 21364
root@ip-172-31-36-156:~# python3 -c "import time; time.sleep(300);" &
[4] 21365
root@ip-172-31-36-156:~# python3 -c "import time; time.sleep(300);" &
[5] 21366
root@ip-172-31-36-156:~# cf-agent -KI reaper.cf && cf-agent  && cat /var/cfengine/state/diff/execution_log.diff | grep python
    info: Signalled 'kill' (9) to process 21362 (root                           21362 20253 21362  0.1  0.0  28468   0      9320    1 15:38       00:11 00:00:00 python3 -c import time; time.sleep(300);)
    info: Signalled 'kill' (9) to process 21363 (root                           21363 20253 21363  0.1  0.0  28468   0      9412    1 15:38       00:09 00:00:00 python3 -c import time; time.sleep(300);)
    info: Signalled 'kill' (9) to process 21364 (root                           21364 20253 21364  0.2  0.0  28468   0      9328    1 15:38       00:08 00:00:00 python3 -c import time; time.sleep(300);)
    info: Signalled 'kill' (9) to process 21365 (root                           21365 20253 21365  0.2  0.0  28468   0      9220    1 15:38       00:07 00:00:00 python3 -c import time; time.sleep(300);)
    info: Signalled 'kill' (9) to process 21366 (root                           21366 20253 21366  0.1  0.0  28468   0      9300    1 15:38       00:06 00:00:00 python3 -c import time; time.sleep(300);)
[1]   Killed                  python3 -c "import time; time.sleep(300);"
[2]   Killed                  python3 -c "import time; time.sleep(300);"
[3]   Killed                  python3 -c "import time; time.sleep(300);"
[4]-  Killed                  python3 -c "import time; time.sleep(300);"
[5]+  Killed                  python3 -c "import time; time.sleep(300);"
1569425824,1,789fc364777672d151be8a281409c013cf8abb9d9b57525a288b6c7dacf0d2ba,reaper.cf,b15bbb63bd4f95f15e528e11d7a4c10d3d0b6b7e,99,default,main,processes,python3,/default/main/processes/'python3'[1],,[],[],7,SHA=6653141935468ee23874c0df09bf939d6a4ec3a86bd0be0a50384aadae2585f0
1569425880,3,789fc364777672d151be8a281409c013cf8abb9d9b57525a288b6c7dacf0d2ba,reaper.cf,b15bbb63bd4f95f15e528e11d7a4c10d3d0b6b7e,114,default,main,processes,python3,/default/main/processes/'python3'[1],,[],"[""Signalled 'kill' (9) to process 21261 (root                           21261 20253 21261  1.0  0.0  28468   0      9244    1 15:37       00:01 00:00:00 python3 -c import time; time.sleep(300);)""]",7,SHA=6653141935468ee23874c0df09bf939d6a4ec3a86bd0be0a50384aadae2585f0
1569425901,3,789fc364777672d151be8a281409c013cf8abb9d9b57525a288b6c7dacf0d2ba,reaper.cf,b15bbb63bd4f95f15e528e11d7a4c10d3d0b6b7e,114,default,main,processes,python3,/default/main/processes/'python3'[1],,[],"[""Signalled 'kill' (9) to process 21362 (root                           21362 20253 21362  0.1  0.0  28468   0      9320    1 15:38       00:11 00:00:00 python3 -c import time; time.sleep(300);)"",""Signalled 'kill' (9) to process 21363 (root                           21363 20253 21363  0.1  0.0  28468   0      9412    1 15:38       00:09 00:00:00 python3 -c import time; time.sleep(300);)"",""Signalled 'kill' (9) to process 21364 (root                           21364 20253 21364  0.2  0.0  28468   0      9328    1 15:38       00:08 00:00:00 python3 -c import time; time.sleep(300);)"",""Signalled 'kill' (9) to process 21365 (root                           21365 20253 21365  0.2  0.0  28468   0      9220    1 15:38       00:07 00:00:00 python3 -c import time; time.sleep(300);)"",""Signalled 'kill' (9) to process 21366 (root                           21366 20253 21366  0.1  0.0  28468   0      9300    1 15:38       00:06 00:00:00 python3 -c import time; time.sleep(300);)""]",7,SHA=6653141935468ee23874c0df09bf939d6a4ec3a86bd0be0a50384aadae2585f0
root@ip-172-31-36-156:~# cf-agent -KI reaper.cf && cf-agent  && cat /var/cfengine/state/diff/execution_log.diff | grep python
1569425824,1,789fc364777672d151be8a281409c013cf8abb9d9b57525a288b6c7dacf0d2ba,reaper.cf,b15bbb63bd4f95f15e528e11d7a4c10d3d0b6b7e,99,default,main,processes,python3,/default/main/processes/'python3'[1],,[],[],7,SHA=6653141935468ee23874c0df09bf939d6a4ec3a86bd0be0a50384aadae2585f0
1569425880,3,789fc364777672d151be8a281409c013cf8abb9d9b57525a288b6c7dacf0d2ba,reaper.cf,b15bbb63bd4f95f15e528e11d7a4c10d3d0b6b7e,114,default,main,processes,python3,/default/main/processes/'python3'[1],,[],"[""Signalled 'kill' (9) to process 21261 (root                           21261 20253 21261  1.0  0.0  28468   0      9244    1 15:37       00:01 00:00:00 python3 -c import time; time.sleep(300);)""]",7,SHA=6653141935468ee23874c0df09bf939d6a4ec3a86bd0be0a50384aadae2585f0
1569425901,3,789fc364777672d151be8a281409c013cf8abb9d9b57525a288b6c7dacf0d2ba,reaper.cf,b15bbb63bd4f95f15e528e11d7a4c10d3d0b6b7e,114,default,main,processes,python3,/default/main/processes/'python3'[1],,[],"[""Signalled 'kill' (9) to process 21362 (root                           21362 20253 21362  0.1  0.0  28468   0      9320    1 15:38       00:11 00:00:00 python3 -c import time; time.sleep(300);)"",""Signalled 'kill' (9) to process 21363 (root                           21363 20253 21363  0.1  0.0  28468   0      9412    1 15:38       00:09 00:00:00 python3 -c import time; time.sleep(300);)"",""Signalled 'kill' (9) to process 21364 (root                           21364 20253 21364  0.2  0.0  28468   0      9328    1 15:38       00:08 00:00:00 python3 -c import time; time.sleep(300);)"",""Signalled 'kill' (9) to process 21365 (root                           21365 20253 21365  0.2  0.0  28468   0      9220    1 15:38       00:07 00:00:00 python3 -c import time; time.sleep(300);)"",""Signalled 'kill' (9) to process 21366 (root                           21366 20253 21366  0.1  0.0  28468   0      9300    1 15:38       00:06 00:00:00 python3 -c import time; time.sleep(300);)""]",7,SHA=6653141935468ee23874c0df09bf939d6a4ec3a86bd0be0a50384aadae2585f0
1569425914,3,789fc364777672d151be8a281409c013cf8abb9d9b57525a288b6c7dacf0d2ba,reaper.cf,b15bbb63bd4f95f15e528e11d7a4c10d3d0b6b7e,99,default,main,processes,python3,/default/main/processes/'python3'[1],,[],[],7,SHA=6653141935468ee23874c0df09bf939d6a4ec3a86bd0be0a50384aadae2585f0
root@ip-172-31-36-156:~#
```

(Note that all the entries now have the 789 promise hash).

**Comment by olehermanse** [comment]
@cf-bottom test this again in jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2832/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2832/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2832/

**Comment by olehermanse** [comment]
Cherry-pick: https://github.com/cfengine/core/pull/3854

**Pull request merged**
