### PR TITLE
Travis fixes

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@jimis This is important

**Comment by olehermanse** [comment]
@kacf @Lex-2008 Can this be merged? As it is now, travis will not fail even though some tests fail. The `set +e` and `set -e` should fix this.

**Comment by Lex-2008** [comment]
Looks good to me! Although in buildscrips we usually add `set -x` to see what command failed, too

**Comment by jimis** [comment]
@olehermanse IIRC travis will show FAIL is any command in the main script returns error. Does it not honour that for some test? Which one? Can you also add this info to the commit message?

Doing `set -e` will cause early exit, skipping all subsequent tests. I'm OK with that, but lets note specifically what led to this decision.

**Comment by jimis** [comment]
This has been superseded by #2911. Close?

**Pull request closed without merging**
