### PR TITLE
ENT-5406/3.15.x: Fixed selection of standard_services when used from non-default namespace

### PR DESCRIPTION
**Pull request by nickanderson**
When no service_method was specified the standard_services services bundle
should be used. This default only worked if you were already in the default
namespace. This change makes sure that the standard_services method used is from
the default namespace and fixes the case where services promises are used from
non default namespaces expecting to leverage the standard_services
implementation.

### CODE REVIEW

**Comment by nickanderson** [comment]
Test failed as expected before the C fix: https://travis-ci.org/github/cfengine/core/jobs/661645233#L16691

**Comment by nickanderson** [comment]
And with the C fix, the test passes: https://travis-ci.org/github/cfengine/core/jobs/661674578#L3646

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4837/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4837/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4837/

**Pull request merged**
