### PR TITLE
Use safe_fopen() instead of fopen()

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom I'd like to test this with packages from jenkins.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2273/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2273/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2273/

**Comment by olehermanse** [comment]
This pull request **fixes 2 alerts** when merging c727e6a925f2a30b913b42226f553b92d55a05bc into c512c833234d163f50aa940c0577328b59ba6d72 - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-92bdea4c84ffa32afc02c157fe0fbd77510ca6c6)

**fixed alerts:**

* 2 for File created without restricting permissions

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by olehermanse** [comment]
**Before:**

```
ubuntu@ip-172-31-45-101:~$ sudo bash
root@ip-172-31-45-101:~# cf-check backup
    info: No filenames specified, defaulting to .lmdb files in /var/cfengine/state/
    info: Backing up to '/var/cfengine/backups/1554326271/'
    info: Copying: '/var/cfengine/state/nova_static.lmdb' -> '/var/cfengine/backups/1554326271/nova_static.lmdb'
    info: Copying: '/var/cfengine/state/cf_lastseen.lmdb' -> '/var/cfengine/backups/1554326271/cf_lastseen.lmdb'
    info: Copying: '/var/cfengine/state/packages_installed_apt_get.lmdb' -> '/var/cfengine/backups/1554326271/packages_installed_apt_get.lmdb'
    info: Copying: '/var/cfengine/state/packages_installed_$(package_module_knowledge.platform_default).lmdb' -> '/var/cfengine/backups/1554326271/packages_installed_$(package_module_knowledge.platform_default).lmdb'
    info: Copying: '/var/cfengine/state/cf_observations.lmdb' -> '/var/cfengine/backups/1554326271/cf_observations.lmdb'
    info: Copying: '/var/cfengine/state/nova_measures.lmdb' -> '/var/cfengine/backups/1554326271/nova_measures.lmdb'
    info: Copying: '/var/cfengine/state/cf_lock.lmdb' -> '/var/cfengine/backups/1554326271/cf_lock.lmdb'
    info: Copying: '/var/cfengine/state/packages_updates_apt_get.lmdb' -> '/var/cfengine/backups/1554326271/packages_updates_apt_get.lmdb'
    info: Copying: '/var/cfengine/state/nova_agent_execution.lmdb' -> '/var/cfengine/backups/1554326271/nova_agent_execution.lmdb'
    info: Copying: '/var/cfengine/state/nova_track.lmdb' -> '/var/cfengine/backups/1554326271/nova_track.lmdb'
    info: Copying: '/var/cfengine/state/cf_state.lmdb' -> '/var/cfengine/backups/1554326271/cf_state.lmdb'
    info: Copying: '/var/cfengine/state/cf_changes.lmdb' -> '/var/cfengine/backups/1554326271/cf_changes.lmdb'
    info: Copying: '/var/cfengine/state/history.lmdb' -> '/var/cfengine/backups/1554326271/history.lmdb'
    info: Copying: '/var/cfengine/state/performance.lmdb' -> '/var/cfengine/backups/1554326271/performance.lmdb'
root@ip-172-31-45-101:~# ls -al /var/cfengine/backups/
total 12
drwx------  3 root root 4096 Apr  3 21:17 .
drwxr-xr-x 22 root root 4096 Apr  3 21:17 ..
drwx------  2 root root 4096 Apr  3 21:17 1554326271
root@ip-172-31-45-101:~# ls -al /var/cfengine/backups/1554326271/
total 684
drwx------ 2 root root   4096 Apr  3 21:17  .
drwx------ 3 root root   4096 Apr  3 21:17  ..
-rw-r--r-- 1 root root  32768 Apr  3 21:17  cf_changes.lmdb
-rw-r--r-- 1 root root  12288 Apr  3 21:17  cf_lastseen.lmdb
-rw-r--r-- 1 root root  57344 Apr  3 21:17  cf_lock.lmdb
-rw-r--r-- 1 root root  28672 Apr  3 21:17  cf_observations.lmdb
-rw-r--r-- 1 root root   8192 Apr  3 21:17  cf_state.lmdb
-rw-r--r-- 1 root root  16384 Apr  3 21:17  history.lmdb
-rw-r--r-- 1 root root  28672 Apr  3 21:17  nova_agent_execution.lmdb
-rw-r--r-- 1 root root   8192 Apr  3 21:17  nova_measures.lmdb
-rw-r--r-- 1 root root   8192 Apr  3 21:17  nova_static.lmdb
-rw-r--r-- 1 root root  12288 Apr  3 21:17  nova_track.lmdb
-rw-r--r-- 1 root root 409600 Apr  3 21:17  packages_installed_apt_get.lmdb
-rw-r--r-- 1 root root   8192 Apr  3 21:17 'packages_installed_$(package_module_knowledge.platform_default).lmdb'
-rw-r--r-- 1 root root  28672 Apr  3 21:17  packages_updates_apt_get.lmdb
-rw-r--r-- 1 root root  32768 Apr  3 21:17  performance.lmdb
root@ip-172-31-45-101:~# ls -al /var/cfengine/bootstrap_id.dat 
-rw-r--r-- 1 root root 41 Apr  3 21:17 /var/cfengine/bootstrap_id.dat
root@ip-172-31-45-101:~# 
```

**Pull request merged**
