### PR TITLE
Fix parser for lists larger than 4994 items

### PR DESCRIPTION
**Pull request by jimis**
Redmine#6672

### CODE REVIEW

**Comment by jimis** [comment]
@kacfengine feel free to review if you feel comfortable with yacc, else I'll just go ahead and merge. The important commit is only a28b28e.

**Comment by kacfengine** [comment]
Nice!

And +1 for using single characters.

**Comment by kacfengine** [comment]
trigger build

**Comment by jimis** [comment]
Please don't merge yet, I'll amend a commit with acceptance test.

**Comment by kacfengine** [comment]
Ok, the build queue is quite long right now, so I cancelled the build so you can run it with the acceptance test instead.

**Comment by jimis** [comment]
Done, dear jenkins please trigger build.

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
You need a plain string. I tried that before.

**Comment by kacfengine** [comment]
PS! You might want to make the list considerably longer actually. I'm assuming that 4994 items is tied specifically to Linux with a certain stack setting in the kernel. It could easily be different.

**Comment by jimis** [comment]
> You need a plain string. I tried that before.

Strange, I've seen that Jenkins source code uses ```String.contains()``` (or something like that), at least the way I configured it two months ago (previously it didn't work anyway).

**Comment by jimis** [comment]
> PS! You might want to make the list considerably longer actually. I'm assuming that 4994 items is tied specifically to Linux with a certain stack setting in the kernel. It could easily be different.

Indeed, but I wouldn't know what size to choose. This (stack size) is a tweakable knob in Bison and /probably/ tweakable via `ulimit()` as well, but I'm not sure about other exotic yacc implementations. And the file size and slowness (parsing is way too slow!) made me go with this size.

**Comment by kacfengine** [comment]
Ok, sounds wise.

**Comment by kacfengine** [comment]
Jenkins looks good. Merge?

**Comment by jimis** [comment]
yes please :-)

**Pull request merged**
