### PR TITLE
ENT-7452: Use ts_key file for measurement names in cf-check dump (3.18)

### PR DESCRIPTION
**Pull request by craigcomstock**
Without using ts_key we can't dump custom measurements.

Ticket: ENT-7452
Changelog: title
(cherry picked from commit 418aa12f13e3fa5f4edd07c5fea55806e39b3f14)

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6963/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6963/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6963/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins again now that CI is more stable

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7030/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7030/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7030/

**Comment by craigcomstock** [comment]
@cf-bottom lets try jenkins again

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7042/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7042/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7042/

**Comment by craigcomstock** [comment]
Only failure in last run is lmdb related. Sadly it is not possible to workaround this issue for 3.12.x series, see https://tracker.mender.io/browse/ENT-7500

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
