### PR TITLE
Systemd hardclass redmine6995

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
Tested with custom, almost empty policy, and "systemd" hard class is correctly set. 

@kacfengine this could be useful for your policy rewriting.

**Comment by kacfengine** [comment]
Nice! Will definitely come in handy! Should we deprecate the one in masterfiles? I suppose old clients still need it...

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
Cherry-picked to 3.6.x.

**Pull request merged**
