### PR TITLE
CFE-2824: Eliminated noisy error message - 3.10.x

### PR DESCRIPTION
**Pull request by karlhto**

### CODE REVIEW

**Comment by karlhto** [comment]
Managed to introduce an error with passing pointers. Fixed now.

**Comment by olehermanse** [comment]
@cf-bottom Please trigger a build for this in jenkins :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com/job/pr-pipeline/818/)

https://ci.cfengine.com/job/pr-pipeline/818/

**Comment by karlhto** [comment]
This build is running.
https://ci.cfengine.com/job/pr-pipeline/820/

**Pull request merged**
