### PR TITLE
CFE-2887: Canonify class names set by module protocol

### PR DESCRIPTION
**Pull request by tzz**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @vpodzime can review this?

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1190/)

https://ci.cfengine.com/job/pr-pipeline/1190/

**Comment by olehermanse** [comment]
@tzz Yes, if you have the time, feel free to provide it. Otherwise we'll look at it some time next week.

**Comment by olehermanse** [comment]
@tzz Can you add this to the end of the commit message:

```
Changelog: Title
```

So it is picked up by the changelog generator.

**Comment by nickanderson** [comment]
@tzz I have a changelog keyword and a test up in pr #3277 no need to worry about it

**Comment by olehermanse** [comment]
@nickanderson Thanks! Do you want to merge or close this PR then?

**Comment by tzz** [comment]
@olehermanse please feel free to close in favor of @nickanderson 

(and you will know how jimis felt with many of my PRs :)

**Comment by olehermanse** [comment]
Closed in favor of: https://github.com/cfengine/core/pull/3277

**Pull request closed without merging**
