### PR TITLE
Fixed default size bug in readfile() (CFE-2661)

### PR DESCRIPTION
**Pull request by olehermanse**
Introduced in https://github.com/cfengine/core/pull/2858, 6 days ago.

No changelog added, the changelog entry from last commit is fine.

### CODE REVIEW

**Comment by olehermanse** [comment]
@jimis Please review/merge asap.

**Comment by jimis** [comment]
Makes sense, thanks. Does it need cherry-picking to any branches?

**Comment by olehermanse** [comment]
Yes, same branches as: https://github.com/cfengine/core/pull/2858 : c76c46db77d81ba3e3ce4525e7f8c521b6f8c9af

**Comment by olehermanse** [comment]
@jimis
> Yes, same branches as: #2858 : c76c46d

**Comment by jimis** [comment]
Cherry-picked to 3.11.x and 3.10.x.

**Pull request merged**
