### PR TITLE
CFE-3417: Updated libntech to latest upstream master

### PR DESCRIPTION
**Pull request by KotzaBoss**

### CODE REVIEW

**Comment by KotzaBoss** [comment]
@cf-bottom please test this in jenkins

**Comment by cf-bottom** [comment]
@KotzaBoss : I'm sorry, I cannot do that. @olehermanse please help.

**Comment by olehermanse** [comment]
@cf-bottom please test this in Jenkins, I will make sure you trust him next time

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6455/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6455/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6455/

**Review by olehermanse — APPROVED** [review]
Thanks!

**Pull request merged**
