### PR TITLE
Added make list to list all make targets

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @olehermanse can review this?

**Comment by craigcomstock** [comment]
This might be interesting in case it catches some cases yours does not: https://github.com/scop/bash-completion/blob/master/completions/make

**Comment by olehermanse** [comment]
@nickanderson Do you have an example of when/why this is useful?

**Comment by nickanderson** [comment]
I couldn't remember the name of the target I was looking for (it was make check). I thought having a target to list the targets was useful. If you don't like then we can just reject.

**Comment by olehermanse** [comment]
> I couldn't remember the name of the target I was looking for (it was make check). I thought having a target to list the targets was useful. If you don't like then we can just reject.

It's good, I just like to see some reasoning/motivation for making changes.

**Pull request merged**
