### PR TITLE
CFE-2383: Use a dynamic buffer to escape json strings

### PR DESCRIPTION
**Pull request by amousset**

### CODE REVIEW

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
Thanks! The code looks good, but 2 extra things are missing:
* Changelog tag in the commit message
* Would be nice to use the policy from CFE-2383 as acceptance test.

**Comment by amousset** [comment]
Updated with the test and a commit message.

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
Merged and cherry-picked to 3.9.x and 3.7.x. Thanks!

**Pull request merged**
