### PR TITLE
CFE-3874: cf-secret encrypt now encrypts for localhost if no key or host is specified (3.15.x)

### PR DESCRIPTION
**Pull request by larsewi**

### CODE REVIEW

**Comment by larsewi** [comment]
back-ported from #4892

**Comment by larsewi** [comment]
@cf-bottom, Jenkins please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7466/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7466/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7466/

**Comment by larsewi** [comment]
@cf-bottom Jenkins again please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7469/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7469/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7469/

**Comment by larsewi** [comment]
The cherry-picked acceptance test was not compatible with 3.15, thus I had to rework it. Please review again.

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
