### PR TITLE
Backports: libntech, nt_static_assert, pcre, etc. (3.15)

### PR DESCRIPTION
**Pull request by olehermanse**
Merge together:
https://github.com/cfengine/core/pull/4356
https://github.com/cfengine/enterprise/pull/640

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, with exotics, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5809/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5809/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5809/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5810/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5810/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5810/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5811/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5811/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5811/

**Pull request merged**
