### PR TITLE
CFE-3320/master: Fixed typos in test

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by vpodzime** [comment]
Travis is green, not sure why the status on the PR is still *pending*.

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5416/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5416/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5416/

**Comment by nickanderson** [comment]
Applied fix to this test similarly to that done for CFE-3319

**Comment by nickanderson** [comment]
@cf-bottom jenkins please, with exotics.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5438/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5438/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5438/

**Comment by nickanderson** [comment]
so much green.

**Pull request merged**
