### PR TITLE
Bump libntech version

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
macos says

```
./lib/autoconf/headers.m4:702: AC_HEADER_TIME is expanded from...
configure.ac:415: the top level
configure.ac:101: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:102: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: error: /opt/homebrew/Cellar/autoconf/2.72/bin/autoconf failed with exit status: 1
```

**Comment by craigcomstock** [comment]
> Maybe libtool is missing?

That makes some sense to be sure.

I changed the workflows to focus on this and got

```
Run command -v libtool && libtool -V && false
/usr/bin/libtool
Apple Inc. version cctools-1009.2
```

locally I have
```
/usr/bin/libtool
Apple Inc. version cctools-1010.6
```

So not too different.

**Comment by craigcomstock** [comment]
maybe libtool isn't quite installed right? no libtool.m4 anywhere?

```
Run sudo find / -name 'libtool.m4' 2>/dev/null
```

nothing.

But on my system I have
```
$ sudo find / -name 'libtool.m4' 2>/dev/null
/usr/local/Cellar/libtool/2.4.7/share/aclocal/libtool.m4
/usr/local/Cellar/php/8.3.6/lib/php/build/libtool.m4
/usr/local/share/aclocal/libtool.m4
/System/Volumes/Data/usr/local/Cellar/libtool/2.4.7/share/aclocal/libtool.m4
/System/Volumes/Data/usr/local/Cellar/php/8.3.6/lib/php/build/libtool.m4
/System/Volumes/Data/usr/local/share/aclocal/libtool.m4
```

and I imagine those two groups are really the "same" somehow.

Will try installing libtool and autoconf with brew to see if that works...

**Comment by larsewi** [comment]
```
configure: error: Cannot find Lightning MDB
checking for mdb_dbi_open in -llmdb... no
```
Maybe you need to export `LDFLAGS` to where lmdb is installed by brew?

It seems to be installed in `/opt/homebrew/Cellar/lmdb/0.9.32`
```
==> Pouring lmdb--0.9.32.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/lmdb/0.9.32: 15 files, 681.2KB
```

**Comment by olehermanse** [comment]
> ```
> configure: error: Cannot find Lightning MDB
> checking for mdb_dbi_open in -llmdb... no
> ```
> 
> Maybe you need to export `LDFLAGS` to where lmdb is installed by brew?
> 
> It seems to be installed in `/opt/homebrew/Cellar/lmdb/0.9.32`
> 
> ```
> ==> Pouring lmdb--0.9.32.arm64_sonoma.bottle.tar.gz
> 🍺  /opt/homebrew/Cellar/lmdb/0.9.32: 15 files, 681.2KB
> ```

You don't have to use this path directly, there is a symlink and also `brew --prefix`:

```
$ brew --prefix lmdb
/usr/local/opt/lmdb
$ ls -al /usr/local/opt/lmdb
lrwxr-xr-x  1 olehermanse  admin  21 Feb  2 20:15 /usr/local/opt/lmdb -> ../Cellar/lmdb/0.9.32
```

**Comment by larsewi** [comment]
Never ending story 😆 
```
configure: error: Cannot find OpenSSL
```

**Comment by larsewi** [comment]
```
configure: error: Cannot find PCRE2
checking for pcre2.h... no
```

**Comment by larsewi** [comment]
Failure (see https://github.com/microsoft/linux-package-repositories/issues/130)

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10641/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10641/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10641/

**Review by olehermanse — CHANGES_REQUESTED** [review]
I think this one should be ready now, just need to wait for CI and squash commits. Also, it could be merged without the nova PR, which is why I started a separate pipeline.

**Comment by olehermanse** [comment]
Superseded by: https://github.com/cfengine/core/pull/5486

**Pull request closed without merging**
