### PR TITLE
Add options to cf-net to set minimum TLS version and ciphers

### PR DESCRIPTION
**Pull request by vpodzime**
Useful for testing and debugging issues with the TLS-related
aspects of our network connections.

Ticket: ENT-4617
Changelog: Title

### CODE REVIEW

**Comment by vpodzime** [comment]
I want to extend this to allow specifying exact TLS version instead of just minimum version, but that will require some extra changes in *libcfnet*.

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2618/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2618/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2618/

**Comment by olehermanse** [comment]
LGTM alerts are mostly false positive, have to fix the query.

**Pull request merged**
