### PR TITLE
CFE-2994: cf-check directories can now be controlled from ENV vars

### PR DESCRIPTION
**Pull request by olehermanse**
Should also make it respect `--with-statedir` configure option.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom build this in jenkins please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2715/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2715/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2715/

**Comment by olehermanse** [comment]
Restarted travis build - timeouts in transfer.sh.

**Comment by olehermanse** [comment]
Tested `CFENGINE_TEST_OVERRIDE_WORKDIR`:

```
$ cf-agent -B 192.168.100.10
R: Bootstrapping from host '192.168.100.10' via built-in policy '/var/cfengine/inputs/failsafe.cf'
R: This host assumes the role of policy server
R: Updated local policy from policy server
R: Triggered an initial run of the policy
R: Started the server
R: Started the scheduler
  notice: Bootstrap to '192.168.100.10' completed successfully!
$ cf-check backup
    info: No filenames specified, defaulting to .lmdb files in /var/cfengine/state
    info: Backing up to '/var/cfengine/backups/1561452386/'
    info: Copying: '/var/cfengine/state/cf_state.lmdb' -> '/var/cfengine/backups/1561452386/cf_state.lmdb'
    info: Copying: '/var/cfengine/state/history.lmdb' -> '/var/cfengine/backups/1561452386/history.lmdb'
    info: Copying: '/var/cfengine/state/packages_installed_apt_get.lmdb' -> '/var/cfengine/backups/1561452386/packages_installed_apt_get.lmdb'
    info: Copying: '/var/cfengine/state/nova_measures.lmdb' -> '/var/cfengine/backups/1561452386/nova_measures.lmdb'
    info: Copying: '/var/cfengine/state/nova_static.lmdb' -> '/var/cfengine/backups/1561452386/nova_static.lmdb'
    info: Copying: '/var/cfengine/state/packages_updates_apt_get.lmdb' -> '/var/cfengine/backups/1561452386/packages_updates_apt_get.lmdb'
    info: Copying: '/var/cfengine/state/cf_lastseen.lmdb' -> '/var/cfengine/backups/1561452386/cf_lastseen.lmdb'
    info: Copying: '/var/cfengine/state/cf_observations.lmdb' -> '/var/cfengine/backups/1561452386/cf_observations.lmdb'
    info: Copying: '/var/cfengine/state/cf_lock.lmdb' -> '/var/cfengine/backups/1561452386/cf_lock.lmdb'
    info: Copying: '/var/cfengine/state/packages_installed_$(package_module_knowledge.platform_default).lmdb' -> '/var/cfengine/backups/1561452386/packages_installed_$(package_module_knowledge.platform_default).lmdb'
$ pkill -f 'cf-*'
$ ps aux | grep cf
root     25196  0.0  0.0  12836  1004 pts/0    R+   08:46   0:00 grep --color=auto cf
$ mv /var/cfengine/ /home/vagrant/cfengine
$ CFENGINE_TEST_OVERRIDE_WORKDIR="/home/vagrant/cfengine" /home/vagrant/cfengine/bin/cf-check backup
    info: No filenames specified, defaulting to .lmdb files in /home/vagrant/cfengine/state
    info: Backing up to '/home/vagrant/cfengine/backups/1561452493/'
    info: Copying: '/home/vagrant/cfengine/state/cf_state.lmdb' -> '/home/vagrant/cfengine/backups/1561452493/cf_state.lmdb'
    info: Copying: '/home/vagrant/cfengine/state/history.lmdb' -> '/home/vagrant/cfengine/backups/1561452493/history.lmdb'
    info: Copying: '/home/vagrant/cfengine/state/packages_installed_apt_get.lmdb' -> '/home/vagrant/cfengine/backups/1561452493/packages_installed_apt_get.lmdb'
    info: Copying: '/home/vagrant/cfengine/state/nova_measures.lmdb' -> '/home/vagrant/cfengine/backups/1561452493/nova_measures.lmdb'
    info: Copying: '/home/vagrant/cfengine/state/nova_static.lmdb' -> '/home/vagrant/cfengine/backups/1561452493/nova_static.lmdb'
    info: Copying: '/home/vagrant/cfengine/state/packages_updates_apt_get.lmdb' -> '/home/vagrant/cfengine/backups/1561452493/packages_updates_apt_get.lmdb'
    info: Copying: '/home/vagrant/cfengine/state/cf_lastseen.lmdb' -> '/home/vagrant/cfengine/backups/1561452493/cf_lastseen.lmdb'
    info: Copying: '/home/vagrant/cfengine/state/cf_observations.lmdb' -> '/home/vagrant/cfengine/backups/1561452493/cf_observations.lmdb'
    info: Copying: '/home/vagrant/cfengine/state/cf_lock.lmdb' -> '/home/vagrant/cfengine/backups/1561452493/cf_lock.lmdb'
    info: Copying: '/home/vagrant/cfengine/state/packages_installed_$(package_module_knowledge.platform_default).lmdb' -> '/home/vagrant/cfengine/backups/1561452493/packages_installed_$(package_module_knowledge.platform_default).lmdb'
```

**Comment by olehermanse** [comment]
Tested with built packages as well:

```
$ cf-remote install --hub 34.242.96.11 --hub-package ./cfengine-nova-hub_3.14.0a.51edf32f2_4199_amd64.deb --bootstrap 172.31.47.56 --demo

ubuntu@34.242.96.11
OS            : ubuntu (debian)
Architecture  : x86_64
CFEngine      : Not installed
Policy server : None
Binaries      : dpkg, apt

Copying: './cfengine-nova-hub_3.14.0a.51edf32f2_4199_amd64.deb' to '34.242.96.11'
Installing: 'cfengine-nova-hub_3.14.0a.51edf32f2_4199_amd64.deb' on '34.242.96.11'
CFEngine 3.14.0a.51edf32f2 was successfully installed on '34.242.96.11'
Bootstrapping: '34.242.96.11' -> '172.31.47.56'
Bootstrap successful: '34.242.96.11' -> '172.31.47.56'
Transferring def.json to hub: '34.242.96.11'
Copying: '/Users/olehermanse/.cfengine/cf-remote/json/def.json' to '34.242.96.11'
Triggering an agent run on: '34.242.96.11'
Disabling password change on hub: '34.242.96.11'
Triggering an agent run on: '34.242.96.11'
Your demo hub is ready: https://34.242.96.11/ (Username: admin, Password: password)
$ ssh ubuntu@34.242.96.11
The authenticity of host '34.242.96.11 (34.242.96.11)' can't be established.
ECDSA key fingerprint is SHA256:CKBGHBF+axYnaia5YwAGssrpJfNBrlb4PkQS2J9PHTM.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '34.242.96.11' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-1032-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Tue Jun 25 11:45:23 UTC 2019

  System load:  0.58              Processes:           159
  Usage of /:   18.3% of 7.69GB   Users logged in:     0
  Memory usage: 1%                IP address for eth0: 172.31.47.56
  Swap usage:   0%


  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


Last login: Tue Jun 25 11:44:59 2019 from 195.159.234.190
ubuntu@ip-172-31-47-56:~$ sudo bash
root@ip-172-31-47-56:~# cf-check backup
    info: No filenames specified, defaulting to .lmdb files in /var/cfengine/state
    info: Backing up to '/var/cfengine/backups/1561463137/'
    info: Copying: '/var/cfengine/state/nova_static.lmdb' -> '/var/cfengine/backups/1561463137/nova_static.lmdb'
    info: Copying: '/var/cfengine/state/cf_lastseen.lmdb' -> '/var/cfengine/backups/1561463137/cf_lastseen.lmdb'
    info: Copying: '/var/cfengine/state/packages_installed_apt_get.lmdb' -> '/var/cfengine/backups/1561463137/packages_installed_apt_get.lmdb'
    info: Copying: '/var/cfengine/state/packages_installed_$(package_module_knowledge.platform_default).lmdb' -> '/var/cfengine/backups/1561463137/packages_installed_$(package_module_knowledge.platform_default).lmdb'
    info: Copying: '/var/cfengine/state/cf_observations.lmdb' -> '/var/cfengine/backups/1561463137/cf_observations.lmdb'
    info: Copying: '/var/cfengine/state/nova_measures.lmdb' -> '/var/cfengine/backups/1561463137/nova_measures.lmdb'
    info: Copying: '/var/cfengine/state/cf_lock.lmdb' -> '/var/cfengine/backups/1561463137/cf_lock.lmdb'
    info: Copying: '/var/cfengine/state/packages_updates_apt_get.lmdb' -> '/var/cfengine/backups/1561463137/packages_updates_apt_get.lmdb'
    info: Copying: '/var/cfengine/state/nova_agent_execution.lmdb' -> '/var/cfengine/backups/1561463137/nova_agent_execution.lmdb'
    info: Copying: '/var/cfengine/state/nova_track.lmdb' -> '/var/cfengine/backups/1561463137/nova_track.lmdb'
    info: Copying: '/var/cfengine/state/cf_state.lmdb' -> '/var/cfengine/backups/1561463137/cf_state.lmdb'
    info: Copying: '/var/cfengine/state/cf_changes.lmdb' -> '/var/cfengine/backups/1561463137/cf_changes.lmdb'
    info: Copying: '/var/cfengine/state/history.lmdb' -> '/var/cfengine/backups/1561463137/history.lmdb'
    info: Copying: '/var/cfengine/state/performance.lmdb' -> '/var/cfengine/backups/1561463137/performance.lmdb'
root@ip-172-31-47-56:~# systemctl stop cfengine3
root@ip-172-31-47-56:~# cp -r /var/cfengine /home/ubuntu/cfengine
root@ip-172-31-47-56:~# CFENGINE_TEST_OVERRIDE_WORKDIR=/home/ubuntu/cfengine cf-check backup 
    info: No filenames specified, defaulting to .lmdb files in /home/ubuntu/cfengine/state
    info: Backing up to '/home/ubuntu/cfengine/backups/1561463316/'
    info: Copying: '/home/ubuntu/cfengine/state/nova_static.lmdb' -> '/home/ubuntu/cfengine/backups/1561463316/nova_static.lmdb'
    info: Copying: '/home/ubuntu/cfengine/state/cf_lastseen.lmdb' -> '/home/ubuntu/cfengine/backups/1561463316/cf_lastseen.lmdb'
    info: Copying: '/home/ubuntu/cfengine/state/packages_installed_apt_get.lmdb' -> '/home/ubuntu/cfengine/backups/1561463316/packages_installed_apt_get.lmdb'
    info: Copying: '/home/ubuntu/cfengine/state/packages_installed_$(package_module_knowledge.platform_default).lmdb' -> '/home/ubuntu/cfengine/backups/1561463316/packages_installed_$(package_module_knowledge.platform_default).lmdb'
    info: Copying: '/home/ubuntu/cfengine/state/cf_observations.lmdb' -> '/home/ubuntu/cfengine/backups/1561463316/cf_observations.lmdb'
    info: Copying: '/home/ubuntu/cfengine/state/nova_measures.lmdb' -> '/home/ubuntu/cfengine/backups/1561463316/nova_measures.lmdb'
    info: Copying: '/home/ubuntu/cfengine/state/cf_lock.lmdb' -> '/home/ubuntu/cfengine/backups/1561463316/cf_lock.lmdb'
    info: Copying: '/home/ubuntu/cfengine/state/packages_updates_apt_get.lmdb' -> '/home/ubuntu/cfengine/backups/1561463316/packages_updates_apt_get.lmdb'
    info: Copying: '/home/ubuntu/cfengine/state/nova_agent_execution.lmdb' -> '/home/ubuntu/cfengine/backups/1561463316/nova_agent_execution.lmdb'
    info: Copying: '/home/ubuntu/cfengine/state/nova_track.lmdb' -> '/home/ubuntu/cfengine/backups/1561463316/nova_track.lmdb'
    info: Copying: '/home/ubuntu/cfengine/state/cf_state.lmdb' -> '/home/ubuntu/cfengine/backups/1561463316/cf_state.lmdb'
    info: Copying: '/home/ubuntu/cfengine/state/cf_changes.lmdb' -> '/home/ubuntu/cfengine/backups/1561463316/cf_changes.lmdb'
    info: Copying: '/home/ubuntu/cfengine/state/history.lmdb' -> '/home/ubuntu/cfengine/backups/1561463316/history.lmdb'
    info: Copying: '/home/ubuntu/cfengine/state/performance.lmdb' -> '/home/ubuntu/cfengine/backups/1561463316/performance.lmdb'
root@ip-172-31-47-56:~# 
```

**Comment by olehermanse** [comment]
Tested `--with-statedir` configure option:

```
$ ./autogen.sh --with-statedir=/state
./autogen.sh: Running determine-version.py ...
determine-version.py: REV        = HEAD
determine-version.py: full_rev   = fdd9eea60ce7ea008ceec229d96f7e5fd34e350e
determine-version.py: abbrev_rev = fdd9eea
determine-version.py: exact_tag  = not found
determine-version.py: recent_rev = 5d2dc63b32d89d9e44b1a54e027b5a61541e7c7d
determine-version.py: recent_tag = 3.13.0
determine-version.py: recent_version =  ('3', '13', '0', '')
determine-version.py: all_tags   = [('3', '13', '0', ''), ('3', '13', '0', '-build2')]
determine-version.py: SUCCESS, version detected is: 3.14.0a.fdd9eea
./autogen.sh: Running autoreconf ...
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'

[...]
root@dev core $ make -j4
  SED      libpromises/enterprise_extension.c
  SED      libpromises/enterprise_extension.h
Making all in libcompat
  CC       generic_at.lo
  CC       getopt1.lo
  CC       getopt.lo
  CC       strlcat.lo
  CC       strlcpy.lo
  CC       memdup.lo
  CC       closefrom.lo
  CC       rpl_ctime.lo
  CC       strrstr.lo
  CCLD     libcompat.la
Making all in libutils
  CC       alloc.lo
  CC       array_map.lo
  CC       buffer.lo
  CC       cleanup.lo
  CC       csv_writer.lo

[...]
root@dev core $ make install
Making install in libcompat
Making install in libutils
Making install in libcfnet
Making install in libenv
Making install in libpromises
 /bin/mkdir -p '/var/cfengine/lib'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   libpromises.la '/var/cfengine/lib'
libtool: install: /usr/bin/install -c .libs/libpromises.so.3.0.6 /var/cfengine/lib/libpromises.so.3.0.6
libtool: install: (cd /var/cfengine/lib && { ln -s -f libpromises.so.3.0.6 libpromises.so.3 || { rm -f libpromises.so.3 && ln -s libpromises.so.3.0.6 libpromises.so.3; }; })
libtool: install: (cd /var/cfengine/lib && { ln -s -f libpromises.so.3.0.6 libpromises.so || { rm -f libpromises.so && ln -s libpromises.so.3.0.6 libpromises.so; }; })
libtool: install: /usr/bin/install -c .libs/libpromises.lai /var/cfengine/lib/libpromises.la
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/lib/postgresql/10/bin:/home/vagrant/.dotfiles_olehermanse/bin:/var/cfengine/bin/:/sbin" ldconfig -n /var/cfengine/lib

[...]
 /bin/mkdir -p '/var/cfengine/share/doc/cfengine'
 /usr/bin/install -c -m 644 README.md ChangeLog '/var/cfengine/share/doc/cfengine'
root@dev core $ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:74:61:f3 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe74:61f3/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:61:11:1f brd ff:ff:ff:ff:ff:ff
    inet 192.168.56.101/24 brd 192.168.56.255 scope global eth1
       valid_lft forever preferred_lft forever
root@dev core $ cf-key
root@dev core $ cd ../masterfiles/
$ make install
Making install in modules/packages
make[1]: Entering directory `/home/vagrant/cfe/masterfiles/modules/packages'
make[2]: Entering directory `/home/vagrant/cfe/masterfiles/modules/packages'
make[2]: Nothing to be done for `install-exec-am'.
 /bin/mkdir -p '/var/cfengine/modules/packages'
 /usr/bin/install -c apt_get yum pkg nimclient pkgsrc freebsd_ports zypper slackpkg msiexec.bat WiRunSQL.vbs '/var/cfengine/modules/packages'
make[2]: Leaving directory `/home/vagrant/cfe/masterfiles/modules/packages'
make[1]: Leaving directory `/home/vagrant/cfe/masterfiles/modules/packages'

[...]
make[2]: Leaving directory `/home/vagrant/cfe/masterfiles'
make[1]: Leaving directory `/home/vagrant/cfe/masterfiles'
$ cf-agent -B 192.168.56.101
R: Bootstrapping from host '192.168.56.101' via built-in policy '/var/cfengine/inputs/failsafe.cf'
R: This host assumes the role of policy server
R: Updated local policy from policy server
R: Triggered an initial run of the policy
  notice: Bootstrap to '192.168.56.101' completed successfully!
$ ls /state/
am_policy_hub		  cf_incoming.netbiosssn  cf_lock.lmdb-lock	     cf_outgoing.microsoft_ds  cf_procs		       inventory-cfe_autorun_inventory_dmidecode-total-physical-memory-MB.txt	  packages_updates_apt_get.lmdb
cf_incoming.cfengine	  cf_incoming.nfsd	  cf_lock.lmdb.lock	     cf_outgoing.mongo	       cf_promises_release_id  nova_measures.lmdb							  packages_updates_apt_get.lmdb-lock
cf_incoming.ftp		  cf_incoming.postgresql  cf_observations.lmdb	     cf_outgoing.mysql	       cf_promises_validated   nova_measures.lmdb-lock							  packages_updates_apt_get.lmdb.lock
cf_incoming.imap	  cf_incoming.smtp	  cf_observations.lmdb-lock  cf_outgoing.netbiosdgm    cf_rootprocs	       nova_measures.lmdb.lock							  previous_state
cf_incoming.imaps	  cf_incoming.ssh	  cf_observations.lmdb.lock  cf_outgoing.netbiosns     cf_state.lmdb	       nova_static.lmdb								  static_data
cf_incoming.ipp		  cf_incoming.www	  cf_otherprocs		     cf_outgoing.netbiosssn    cf_state.lmdb-lock      nova_static.lmdb-lock							  ts_key
cf_incoming.ldap	  cf_incoming.www-alt	  cf_outgoing.cfengine	     cf_outgoing.nfsd	       cf_state.lmdb.lock      nova_static.lmdb.lock							  untracked
cf_incoming.ldaps	  cf_incoming.wwws	  cf_outgoing.ftp	     cf_outgoing.postgresql    cf_users		       packages_installed_apt_get.lmdb
cf_incoming.microsoft_ds  cf_lastseen.lmdb	  cf_outgoing.imap	     cf_outgoing.smtp	       diff		       packages_installed_apt_get.lmdb-lock
cf_incoming.mongo	  cf_lastseen.lmdb-lock   cf_outgoing.imaps	     cf_outgoing.ssh	       env_data		       packages_installed_apt_get.lmdb.lock
cf_incoming.mysql	  cf_lastseen.lmdb.lock   cf_outgoing.ipp	     cf_outgoing.www	       history.lmdb	       packages_installed_$(package_module_knowledge.platform_default).lmdb
cf_incoming.netbiosdgm	  cf_lock.lmdb		  cf_outgoing.ldap	     cf_outgoing.www-alt       history.lmdb-lock       packages_installed_$(package_module_knowledge.platform_default).lmdb-lock
cf_incoming.netbiosns	  cf_lock.lmdb.backup	  cf_outgoing.ldaps	     cf_outgoing.wwws	       history.lmdb.lock       packages_installed_$(package_module_knowledge.platform_default).lmdb.lock
$ ls /var/cfengine/state/
$ cf-check backup
    info: No filenames specified, defaulting to .lmdb files in /state
    info: Backing up to '/var/cfengine/backups/1561463975/'
    info: Copying: '/state/cf_state.lmdb' -> '/var/cfengine/backups/1561463975/cf_state.lmdb'
    info: Copying: '/state/history.lmdb' -> '/var/cfengine/backups/1561463975/history.lmdb'
    info: Copying: '/state/packages_installed_apt_get.lmdb' -> '/var/cfengine/backups/1561463975/packages_installed_apt_get.lmdb'
    info: Copying: '/state/nova_measures.lmdb' -> '/var/cfengine/backups/1561463975/nova_measures.lmdb'
    info: Copying: '/state/nova_static.lmdb' -> '/var/cfengine/backups/1561463975/nova_static.lmdb'
    info: Copying: '/state/packages_updates_apt_get.lmdb' -> '/var/cfengine/backups/1561463975/packages_updates_apt_get.lmdb'
    info: Copying: '/state/cf_lastseen.lmdb' -> '/var/cfengine/backups/1561463975/cf_lastseen.lmdb'
    info: Copying: '/state/cf_observations.lmdb' -> '/var/cfengine/backups/1561463975/cf_observations.lmdb'
    info: Copying: '/state/cf_lock.lmdb' -> '/var/cfengine/backups/1561463975/cf_lock.lmdb'
    info: Copying: '/state/packages_installed_$(package_module_knowledge.platform_default).lmdb' -> '/var/cfengine/backups/1561463975/packages_installed_$(package_module_knowledge.platform_default).lmdb'
$
```

**Comment by olehermanse** [comment]
Cherry-pick: https://github.com/cfengine/core/pull/3715

**Pull request merged**
