### PR TITLE
ENT-4136: Fixed remaining bugs found by running unit tests with ASAN

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1666/)

https://ci.cfengine.com/job/pr-pipeline/1666/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1667/)

https://ci.cfengine.com/job/pr-pipeline/1667/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1669/)

https://ci.cfengine.com/job/pr-pipeline/1669/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1670/)

https://ci.cfengine.com/job/pr-pipeline/1670/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1671/)

https://ci.cfengine.com/job/pr-pipeline/1671/

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Pull request merged**
