### PR TITLE
CFE-2211 3.7.x cherry-pick

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by Lex-2008** [comment]
PR build in Jenkins: https://ci.cfengine.com/job/testing-enterprise-pr/378/

**Comment by jimis** [comment]
Thanks @Lex-2008. I'm wondering if the [solaris 10 great_expectations.cf test failure](https://ci.cfengine.com/job/testing-enterprise-pr/378/label=PACKAGES_x86_64_solaris_10/testReport/junit/._compliance_great_expectations/cf/great_expectations_cf/) is spurious or not. Did you see it in other builds of 3.7.x?

**Comment by Lex-2008** [comment]
Wait a sec, I think I saw great_expectations.cf failing somewhere else, indeed...

**Comment by Lex-2008** [comment]
Note that there is no PACKAGES_x86_64_solaris_10 configuration in https://ci.cfengine.com/job/testing-enterprise-3.7.x/ job. Are we supposed to build it at all? We are not releasing it at https://cfengine.com/product/cfengine-enterprise-free-25/#3.7.5%20LTS

**Comment by jimis** [comment]
You are right, I'm not sure why Solaris 10 x86 is in the testing-3.7.x pipeline but we definitely don't ship such a package. Merged pull request, thanks!

**Comment by jimis** [comment]
I just verified that this architecture is not built at all in the release pipeline.

**Comment by Lex-2008** [comment]
Oh right, well, because we have only one testing-enterprise-pr job, which is one-for-all-branches. If we had separate testing-enterprise-pr-master, testing-enterprise-pr-3.7.x, etc pipelines, then we wouldn't have such collisions.

**Pull request merged**
