### PR TITLE
Do not evaluate unsafe functions in audit mode(s)

### PR DESCRIPTION
**Pull request by vpodzime**
Functions with side effects (potentially making changes in the
system) should not be evaluated in audit mode(s) because these
are supposed to make no changes in the system.

Ticket: ENT-5290
Changelog: None

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by vpodzime** [comment]
> Changelog: None

Because the audit mode(s) only exist internally and will have proper changelog entry/ies on their own later.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5618/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5618/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5618/

**Review by olehermanse — APPROVED** [review]
Great!

**Pull request merged**
