### PR TITLE
ENT-3970: Fix sys.flavor on AIX to not include minor version 3.7.x

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom can you test on Jenkins, with exotics, please?

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1771/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1771/

**Comment by olehermanse** [comment]
@nickanderson Do you know why these tests are failing? 

https://ci.cfengine.com/job/testing-pr/1651/label=PACKAGES_HUB_x86_64_linux_ubuntu_16/testReport/junit/._diff_reporting_diff_reporting_large_file/cf/diff_reporting_large_file_cf/

**Comment by nickanderson** [comment]
the earths magnetic field shifted

**Pull request merged**
