### PR TITLE
cf-agent now checks that promise module logs expected errors

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
> 2 for Commented-out code

Yes, will be fixed by:

https://tracker.mender.io/browse/ENT-7245

**Comment by olehermanse** [comment]
@cf-bottom test this in Jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6694/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6694/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6694/

**Review by craigcomstock — DISMISSED** [review]

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6695/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6695/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6695/

**Review by craigcomstock — APPROVED** [review]

**Pull request merged**
