### PR TITLE
CFE-3409: Fixed truncation issues / warnings

### PR DESCRIPTION
**Pull request by olehermanse**
Still some more warnings remaining, but this should be okay to merge as is.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5579/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5579/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5579/

**Comment by olehermanse** [comment]
@vpodzime I am still not done with all the warnings, but since I am running into some interesting code I think this PR can be reviewed and merged as-is. I actually want to ask @nickanderson some questions about database promises tomorrow 😈

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5581/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5581/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5581/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5583/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5583/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5583/

**Comment by olehermanse** [comment]
Failing commit split out to separate PR: https://github.com/cfengine/core/pull/4303

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5586/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5586/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5586/

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
