### PR TITLE
Redmine #7399: Define result classes when package is already up to date

### PR DESCRIPTION
**Pull request by amousset**
Ref: https://dev.cfengine.com/issues/7399

### CODE REVIEW

**Comment by estenberg** [comment]
Thanks, @kacfengine can probably review the code. 

There are several known issues (like this) with the old packages promise, though, so I'd suggest looking at 3.7 for a smoother experience in general (https://docs.cfengine.com/latest/reference-promise-types-packages.html).

**Comment by kacfengine** [comment]
Looks good! Will run it through Jenkins soon.

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
Thanks, merged manually.

**Pull request closed without merging**
