### PR TITLE
Update libntech to latest

### PR DESCRIPTION
**Pull request by larsewi**
Ticket: None
Changelog: None
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

### CODE REVIEW

**Comment by larsewi** [comment]
@cf-bottom Jenkins please !

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6997/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6997/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6997/

**Review by olehermanse — CHANGES_REQUESTED** [review]
Looks good, but CI is red due to an unrelated issue: https://tracker.mender.io/browse/ENT-7506

**Comment by larsewi** [comment]
@cf-bottom Jenkins please !

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7037/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7037/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7037/

**Review by olehermanse — APPROVED** [review]

**Pull request merged**
