### PR TITLE
Redmine #4309: Body inheritance

### PR DESCRIPTION
**Pull request by kacfengine**
See original pull request https://github.com/cfengine/core/pull/2153. This contains a couple of extra fixes on top.

### CODE REVIEW

**Comment by tzz** [comment]
Seems good.  I hate string boundaries.

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
Let's cross our fingers then!

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
Perfect, everything is green now! This can be merged as soon as there is documentation. Will you take care of that?

**Comment by tzz** [comment]
OK, documentation PR is in https://github.com/cfengine/documentation/pull/1166

**Comment by nickanderson** [comment]
The docs look good to me are we merging this?

**Comment by nickanderson** [comment]
I saw you would merge when docs are ready. I just merged the docs.

**Comment by kacfengine** [comment]
Yep, merged!

**Pull request merged**
