### PR TITLE
ENT-4653 ifelse() not evaluated in case of unresolved vars (3.15.x)

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5068/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5068/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5068/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5075/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5075/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5075/

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5100/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5100/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5100/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5108/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5108/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5108/

**Comment by craigcomstock** [comment]
bootstrap-tests and sequential-tests are failing due to group/permissions errors, not related to this change. Will restart with exotics and make sure those work.

@cf-bottom jenkins with exotics please, thanks.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5144/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5144/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5144/

**Pull request merged**
