### PR TITLE
Fix determine_version.py to deal with the 3.12.2-2 re-release

### PR DESCRIPTION
**Pull request by vpodzime**
Merge together:
https://github.com/cfengine/enterprise/pull/522
https://github.com/cfengine/nova/pull/1430
https://github.com/cfengine/masterfiles/pull/1413

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2622/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2622/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2622/

**Comment by vpodzime** [comment]
Let's see what jenkins thinks about this little trick.

**Comment by vpodzime** [comment]
@cf-bottom jenkins again, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2627/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2627/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2627/

**Pull request merged**
