### PR TITLE
CFE-3737 fix tokyocabinet and qdbm DBPrivRead() argument type (3.18)

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins again please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7113/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7113/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7113/

**Comment by craigcomstock** [comment]
jenkins failures are unrelated I think, logged a ticket for the sequential-tests 01-triple-upgrade failure: https://tracker.mender.io/browse/ENT-7581

**Comment by craigcomstock** [comment]
@cf-bottom jenkins again please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7117/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7117/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7117/

**Review by olehermanse — APPROVED** [review]

**Pull request merged**
