### PR TITLE
CFE-954: Add test for lsdir

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by jimis** [comment]
soffail it?

**Comment by olehermanse** [comment]
Ping @nickanderson.

**Comment by nickanderson** [comment]
Humm, this is working for me. Trying re-base.

**Comment by nickanderson** [comment]
I dont get it

```
> $ cf-agent -KIf ./CFE-954.cf --define AUTO,DEBUG                [±CFE-954]
R: test description: Test that using lsdir on a list where nothing matches does not mess up later iterations
R: Expect files_regex_1_prod contains . and ..
R: Expect files_regex_1_test contains . .. and FR1234.gz
R: regex_1 : prod - .
R: regex_1 : prod - ..
R: regex_1 : test - .
R: regex_1 : test - FR1234.gz
R: regex_1 : test - ..
R: Expect files_regex_2_prod contains nothing
R: Expect files_regex_2_test contains FR1234.gz
R: regex_2 : test - FR1234.gz
R: test.expect_files_regex_2_prod is NOT defined
R: /home/nickanderson/Northern.Tech/CFEngine/core/tests/acceptance/01_vars/02_functions/. Pass

```

**Comment by nickanderson** [comment]
Also lulz that adding a test is decreasing code coverage

**Comment by olehermanse** [comment]
I guess since the test fails other tests are not run, and coverage is down because of this?

**Comment by olehermanse** [comment]
@nickanderson You can also try to run in jenkins, to see if the failure is specific to travis.

**Comment by nickanderson** [comment]
Passed travis, passed PR build in jenkins except for unrelated failure with diffing large files. Merging.

**Pull request merged**
