### PR TITLE
Add: Example illustrating promise with multiple outcomes

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
trigger build

**Comment by nickanderson** [comment]
trigger build

**Comment by nickanderson** [comment]
trigger build

**Comment by nickanderson** [comment]
Blarg, actually having this as an active test is problematic

**Comment by nickanderson** [comment]
@tzz any ideas on how to have this as an automatic test that can show multiple outcomes?

The difference in output between normal and dry-run modes messes it up.

**Comment by tzz** [comment]
Take a look at `great_expectations.cf` it may do what you need.

**Comment by nickanderson** [comment]
Ah thats in another repository, I was wanting to simply add an example I could include in the docs that had the output tested all the time.

Thanks @tzz

**Pull request merged**
