### PR TITLE
Adjusted cf-support for exotic UNIX platforms

### PR DESCRIPTION
**Pull request by craigcomstock**
head -c 8 doesn't work on hpux 11.23 that we test on currently

dd count=1 bs=8 should work on all UNIX systems

tr on solaris needs LC_CTYPE=C as it can't handle binary data.
Silence not found sysctl command where it is not present.

Ticket: ENT-9786
Changelog: title

### CODE REVIEW

**Review by larsewi — DISMISSED** [review]

**Comment by craigcomstock** [comment]
@cf-bottom please run cf-support tests (wish you knew how)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/11489/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/11489/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-11489/

**Comment by craigcomstock** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/11490/)

**Comment by craigcomstock** [comment]
hpux testing-pr failure is fixed with https://github.com/cfengine/buildscripts/pull/1546, retry: [Build Status](https://ci.cfengine.com/job/pr-pipeline/11496/)

**Review by larsewi — APPROVED** [review]

**Review by larsewi — APPROVED** [review]
Maybe squash the two last commits? Otherwise, LGTM :rocket:

**Comment by craigcomstock** [comment]
cherry picks: https://github.com/cfengine/core/pull/5665 and https://github.com/cfengine/core/pull/5664

**Pull request merged**
