### PR TITLE
Do not segfault if policy_server.dat only contains whitespaces and/or line breaks

### PR DESCRIPTION
**Pull request by amousset**

### CODE REVIEW

**Comment by jimis** [comment]
Thanks everyone! Cherry-picked to 3.11.x, I don't think it applies to 3.10.x. @amousset do you agree?

**Comment by amousset** [comment]
We found it on 3.10.2, so I guess it also applies to 3.10.x, probably at least in libpromises/policy_server.c in PolicyServerSet()

**Comment by jimis** [comment]
Alright, since you have it fixed already can you send a pull request against 3.10.x? Thanks in advance!

**Comment by jimis** [comment]
@amousset I could also cherry-pick the commit from your 3.10.x branch, if you point me there.

**Comment by amousset** [comment]
It is not patched in Rudder yet and I did not have time to look at the 3.10 branch, I can probably do it next week.

**Comment by jimis** [comment]
Thanks, much appreciated!

**Comment by amousset** [comment]
@jimis 3.10 version: https://github.com/cfengine/core/pull/2958

**Pull request merged**
