### PR TITLE
Redmine#7119: clarify remote copy_from failure.

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by kacfengine** [comment]
+1 to replace the message, it's a weird expression. But I do think it should include the word "no server *responded*" since with your version it sounds like we didn't even try to connect.

**Comment by kacfengine** [comment]
Or maybe "Not able to connect to any suitable server"?

**Comment by jimis** [comment]
We tried to connect, servers /possibly/ responded, but no *suitable* server was among them.

**Comment by jimis** [comment]
I'm merging it as is, since it's a clear improvement. Feel free to suggest further improvements in the ticket.

**Pull request merged**
