### PR TITLE
Changed host specific data namespace to data

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom test this in jenkins, just in case.

**Review by vpodzime — DISMISSED** [review]
I believe you also need to modify this place:
```
libpromises/cmdb.c:341:        ret = EvalContextClassPutSoftNSTagsSetWithComment(ctx, "cmdb", key,
```
(and ideally use a macro)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6743/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6743/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6743/

**Review by nickanderson — APPROVED** [review]
OK, but I think that you will also need a related change in Mission Portal.

image

**Pull request merged**
