### PR TITLE
Potential overflows cherry-picks by estenberg

### PR DESCRIPTION
**Pull request by jimis**
Cherry-picked the undisputable ones and the ones not conflicting with Enterprise from pull request #2609.

### CODE REVIEW

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
@estenberg even after cherry-picking what shouldn't mess with Enterprise, the unit tests are failing. Please have a look [here](http://jenkins.usdc.cfengine.com/view/Pull%20requests/job/testing-enterprise-pr_core/label=PACKAGES_x86_64_linux_redhat_4/455/console).

**Comment by estenberg** [comment]
These pass on my machine. It looks like there is an issue with the versioning of the enterprise plugin: 

18:05:19 ERROR: enterprise_extension_test.c:13 Failure!
18:05:19 1 out of 2 tests failed!
18:05:19     test_real_extension_library
18:05:19 ==================================================
18:05:19 Starting test: enterprise_extension_test.c
18:05:19 ==================================================
18:05:19 test_real_extension_library: Starting test
18:05:19    error: Could not open shared library: ../../enterprise-plugin/.libs/cfengine-enterprise.so: undefined symbol: TrackValue
18:05:19 test_real_extension_library: Test failed.

**Comment by jimis** [comment]
Removed the commit that touches `TrackValue()`, trigger build.

**Comment by jimis** [comment]
Removed the commit that removes `GetMyHostInfo()`, trigger build.

**Comment by jimis** [comment]
This seems to be passing, except on HP-UX. @kacf can you verify that [this failure](http://jenkins.usdc.cfengine.com/view/Pull%20requests/job/testing-enterprise-pr_core/label=PACKAGES_ia64_hpux_11.23/457/console) is spurious?

**Comment by kacf** [comment]
Yep, it's spurious.

**Comment by eysteins** [comment]
Thanks, did you backport to 3.9 as well?

**Comment by jimis** [comment]
Will do, thanks for reminding. @estenberg is there a ticket for this?

**Comment by jimis** [comment]
All the commits of this pull request have been cherry-picked to 3.9.x and the build is still green, which is a good thing. :-) @estenberg please let me know if there is a ticket after all to track the progress, there are more commits in your queue so we shouldn't lose track.

**Comment by estenberg** [comment]
Thanks. There is no ticket for this.

But I am not sure I have time to discuss back and forth the issues in the remaining commits. I will likely look at it later this week, but let's make sure we're not wasting time discussing things that could be "perfect" but still improves the situation today if merged.

**Pull request merged**
