### PR TITLE
Made classfiltercsv() fail properly on invalid class expression index

### PR DESCRIPTION
**Pull request by olehermanse**
Reported by LGTM:
https://lgtm.com/rules/2165170567/

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4558/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4558/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4558/

**Comment by olehermanse** [comment]
Jenkins failure unrelated. Tried reproducing dpkg failure using package and fresh VM, no dice.

**Comment by olehermanse** [comment]
Cherry-pick: https://github.com/cfengine/core/pull/4067

**Pull request merged**
