### PR TITLE
ENT-6975 Update user/group tests for latest suse

### PR DESCRIPTION
**Pull request by Lex-2008**
----

#

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom: build exotics please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6296/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6296/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6296/

**Comment by Lex-2008** [comment]
rather green on stable platforms incl SUSE ^^

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
