### PR TITLE
CFE-3006: Move known_dirs to libutils

### PR DESCRIPTION
**Pull request by olehermanse**
Took over #3527 since I created a merge conflict by merging something else.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2224/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2224/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2224/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2228/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2228/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2228/

**Comment by olehermanse** [comment]
Tested new packages manually, working.

**Comment by olehermanse** [comment]
@karlhto please cherry-pick this PR. (There are conflicts to resolve).

**Comment by olehermanse** [comment]
@karlhto I see https://github.com/cfengine/core/pull/3579 but no PR for 3.12 ?

**Comment by karlhto** [comment]
@olehermanse That is correct. I delayed creating one for 3.12 since 
I am aware that it needs to be backported to 3.12 :)

**Comment by olehermanse** [comment]
Cherry-pick: https://github.com/cfengine/core/pull/3583

**Pull request merged**
