### PR TITLE
3.12.x cherry-picks

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1534/)

https://ci.cfengine.com/job/pr-pipeline/1534/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1536/)

https://ci.cfengine.com/job/pr-pipeline/1536/

**Comment by olehermanse** [comment]
@craigcomstock @vpodzime Please review if you agree with these cherry-picks. We can remove some if you think they are unnecessary.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1539/)

https://ci.cfengine.com/job/pr-pipeline/1539/

**Pull request merged**
