### PR TITLE
ENT-4885: Switched to top level config.h

### PR DESCRIPTION
**Pull request by olehermanse**
Split out into a separate PR so I can get it merged before doing the libntech switch.

Merge together:
https://github.com/cfengine/core/pull/3785
https://github.com/cfengine/enterprise/pull/538
https://github.com/cfengine/nova/pull/1493

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom let's test this in jenkins, with exotics, please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2546/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2546/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2546/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2547/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2547/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2547/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2548/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2548/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2548/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2550/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2550/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2550/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2557/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2557/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2557/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2565/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2565/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2565/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2577/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2577/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2577/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2578/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2578/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2578/

**Pull request merged**
