### PR TITLE
Fixups after discussion in #7137.

### PR DESCRIPTION
**Pull request by kacf**
https://dev.cfengine.com/issues/7137

```
commit b2ddcccb3867ad8dcd55d25047654f657b59b8c0
Author: Kristian Amlie <kristian.amlie@cfengine.com>
Date:   Mon Mar 14 11:13:42 2016

    Redmine #7137: Change verbosity of variable logging to debug.
    
    This was done because of discussions in named tickets, relating to
    potential length of variable strings as well as security concerns with
    variables containing sensitive data.
    
    Cancel-changelog: 34be1225eabdc845c573e7e7b2ce127e7149537e
    
    Changelog: Log variable definitions in debug output.

commit 80a30d425fcb6b186a5f936edb588fdf3ba113a5
Author: Kristian Amlie <kristian.amlie@cfengine.com>
Date:   Mon Mar 14 11:13:17 2016

    Add missing VarRefDestroy() in LogVariableValue().
```

### CODE REVIEW

**Comment by kacf** [comment]
@jimis: Perhaps you'd like to glance over this one?

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
Fixed! Build hadn't started yet, so no need to trigger again, it will use the fixed version.

**Comment by jimis** [comment]
I would prefer we keep it at VERBOSE for some time and see, check the ticket for the reasoning. It's a new feature anyway, only for master branch for now.

**Comment by kacf** [comment]
> I would prefer we keep it at VERBOSE for some time and see, check the ticket for the reasoning. It's a new feature anyway, only for master branch for now.

It looks like the majority is in favor of debug level, so will leave it there.

**Comment by kacf** [comment]
trigger build

**Comment by jimis** [comment]
If the message stays in DEBUG mode, then we should bring back the line that says "setting variable xxx", it was in VERBOSE and I removed it to avoid duplication.

**Comment by kacf** [comment]
Alright, readded that, and merged!

**Pull request merged**
