### PR TITLE
CFE-4471: General clean-up of tests/unit/Makefile.am

### PR DESCRIPTION
**Pull request by larsewi**

### CODE REVIEW

**Comment by larsewi** [comment]
@cf-bottom Jenkins please :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/11503/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/11503/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-11503/

**Review by craigcomstock — APPROVED** [review]
cool :)

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
