### PR TITLE
Pre eval 3 passes

### PR DESCRIPTION
**Pull request by pasinskim**
Add 3 passes in pre-evaluation for common bundles. This should help with resolving dependencies between classes and variables.

### CODE REVIEW

**Comment by pasinskim** [comment]
Before merging this to not break enterprise builds this is needed: https://github.com/cfengine/enterprise/pull/250

**Comment by pasinskim** [comment]
@jimis the change for pre-evaluation here.

**Comment by jimis** [comment]
You mentioned about tests that are breaking with this change. Are they the ones you remove in this pull request?

**Comment by pasinskim** [comment]
@jimis there are some in enterprise: cfengine/enterprise#250

**Comment by kacfengine** [comment]
This has been shown to cause problems in real installations, and some Enterprise tests are failing as well. We might revisit this later, but close for now.

**Pull request closed without merging**
