### PR TITLE
CFE-2435 Require network before cfengine service units

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
trigger build

**Comment by nickanderson** [comment]
All green except for ultrasparc on solaris 11 which seems spurious.

http://jenkins.usdc.cfengine.com/job/testing-enterprise-pr_core/508/

**Comment by nickanderson** [comment]
ping @kacf or @jimis

**Comment by jimis** [comment]
spurious indeed, merging.

**Comment by jimis** [comment]
Cherry-picked to 3.9.x and 3.7.x.

**Pull request merged**
