### PR TITLE
Redmine #7808: Do not drop privileges when changes permissions on non fifo

### PR DESCRIPTION
**Pull request by amousset**
Avoid dropping privileges when changing permissions on a file which is not a FIFO.

Redmine: https://dev.cfengine.com/issues/7808

### CODE REVIEW

**Comment by amousset** [comment]
There is also a test for this issue in #2428.

**Comment by kacf** [comment]
This looks good to me. @worr might also want to take a look.

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
trigger build

**Comment by worr** [comment]
lgtm

**Comment by kacf** [comment]
This fix has an additional caveat, as the tests revealed: The method doesn't work if the file being operated on is a symlink to a FIFO. This is getting into rather advanced and security sensitive territory. I attempted to solve this myself as you can see in #2482, by following symlinks and opening the "true" parent directory of the file, instead of the parent directory of the symlink that points to it. Luckily the code for following symlinks and opening the true parent directory was already there, so I just refactored to use it.

Would be nice if you could take a look.

**Comment by kacf** [comment]
Superseded by #2482.

**Pull request closed without merging**
