### PR TITLE
ENT-3710 Improved management of secondary groups to avoid intermediary state failures (3.12.x)

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics please, thanks.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5041/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5041/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5041/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5044/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5044/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5044/

**Pull request merged**
