### PR TITLE
ENT-5125: Added cf-postgres requirement to cf-apache and cf-hub systemd units (3.15.x)

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4692/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4692/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4692/

**Comment by craigcomstock** [comment]
failed on ubuntu14 deployment tests only, re-running at https://ci.cfengine.com/job/testing-run-deployment-tests/4902/

**Comment by craigcomstock** [comment]
That run passed. So I will merge.

**Pull request merged**
