### PR TITLE
Added missing include for regex.h

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, with exotics, please.

**Comment by olehermanse** [comment]
AIX specific build: https://ci.cfengine.com/job/pr-pipeline/5805/

[Build Status](https://ci.cfengine.com/job/pr-pipeline/5805/)

**Review by vpodzime — APPROVED** [review]
ACK

**Comment by olehermanse** [comment]
Cherry-pick: https://github.com/cfengine/core/pull/4356

**Pull request merged**
