### PR TITLE
CFE-3160: Changed unless constraint to be more consistent with if

### PR DESCRIPTION
**Pull request by olehermanse**
For any situation where `if` would NOT skip a promise, `unless`
will cause the promise to be skipped. When there are
unresolved variables / function calls, `if` will skip, `unless`
will NOT skip.

Both of these keywords make a determination on whether to SKIP
the promise or not. If used together skipping effectively takes
precedence. In other words, a promise will be evalutated, if
nothing indicates that it should be skipped.

Tests and log messages were also updated.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4064/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4064/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4064/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4065/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4065/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4065/

**Comment by olehermanse** [comment]
@cf-bottom One more jenkins build, please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4068/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4068/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4068/

**Pull request merged**
