### PR TITLE
CFE-2771/master package inventory refresh interval

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2370/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2370/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2370/

**Comment by nickanderson** [comment]
A build from this just segfaults on me removing the lock operation.

**Comment by nickanderson** [comment]
```
   debug: PipeIsReadWriteReady: wait max 1s for data on fd 5
   debug: Data read from application pipe: 62 [Name=gpg-pubkey
Version=c105b9de-4e0fd3a3
Architecture=(none)
]
   debug: PipeIsReadWriteReady: wait max 1s for data on fd 5
   debug: Data read from application pipe: 74 [Name=tcpdump
Version=4.0.0-11.20090921gitdf3cb4.2.el6
Architecture=x86_64
]
   debug: PipeIsReadWriteReady: wait max 1s for data on fd 5
   debug: cf_pwait - waiting for process 13962
   debug: cf_pwait - process 13962 exited with code: 0
   debug: Yielding lock ''
   debug: Entering lock operation in 'RemoveLock()'. lock_id = '', lock_checksum = 'd41d8cd98f00b204e9800998ecf8427e'
   debug: Entry not found: MDB_NOTFOUND: No matching key/data pair found
   debug: Exiting lock operation in 'RemoveLock()'. lock_id = '', lock_checksum = 'd41d8cd98f00b204e9800998ecf8427e'

```

**Pull request closed without merging**
