### PR TITLE
ENT-6062 Added verbose logging of why promises are not actuated (3.15.x)

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-6062
Changelog: Title

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5311/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5311/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5311/

**Comment by craigcomstock** [comment]
> This pull request **introduces 6 alerts** when merging [e535b39](https://github.com/cfengine/core/commit/e535b3902f1dfa9e634a01017c013445c5761f98) into [e368657](https://github.com/cfengine/core/commit/e368657eb19e73a774378cddb8bee047f95849a3) - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-39fe97227bd0a53c836eb6d87b9b83ab12ca2d61)
> 
> **new alerts:**
> 
>     * 6 for Pointer argument is dereferenced without checking for NULL

Yes. I was thinking about that one. ;) Thank you.

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5316/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5316/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5316/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins again please, valgrind should be OK now.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5317/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5317/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5317/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, with exotics, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5319/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5319/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5319/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5324/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5324/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5324/

**Comment by craigcomstock** [comment]
This served a debug purpose and was not intended to be merged. Closing.

**Pull request closed without merging**
