### PR TITLE
Cherry-picks for 3.7.x

### PR DESCRIPTION
**Pull request by olehermanse**
MUST pass jenkins before merge.

### CODE REVIEW

**Comment by olehermanse** [comment]
@nickanderson These were the commits which could be picked cleanly. Please review that we agree on the commits.

**Comment by vpodzime** [comment]
> @vpodzime This PR contains one Hashmap fix from you. Should this fix be applied to old versions? (See commit fa28d35)

This commit is just a code clarity/quality fix and has no impact on the resulting binary. It's safe but the only purpose of it on other branches would be to prevent conflicts if we ever decide to backport all the hash map changes. Which I don't think is going to happen. So NACK for this commit from me.

**Comment by olehermanse** [comment]
@vpodzime Removed hashmap related commit.

**Comment by olehermanse** [comment]
https://ci.cfengine.com/view/all/job/bootstrap-enterprise-pr/566/
https://ci.cfengine.com/view/all/job/testing-enterprise-pr/565/

**Comment by olehermanse** [comment]
1 single failure in Jenkins:
PACKAGES_x86_64_solaris_10 failed on great_expectations test only.

**Comment by olehermanse** [comment]
Restarted to see if solaris 10 can become green:
https://ci.cfengine.com/view/all/job/bootstrap-enterprise-pr/568/

**Comment by nickanderson** [comment]
@olehermanse 
I re-triggered your PR build.

https://ci.cfengine.com/view/all/job/bootstrap-enterprise-pr/575/parameters/
https://ci.cfengine.com/view/all/job/testing-enterprise-pr/574/

**Comment by olehermanse** [comment]
@nickanderson Had to rebase the enterprise PR to get @craigcomstock's changes. Started another build now.

**Comment by nickanderson** [comment]
@olehermanse  I cherry picked a change in core that should fix the autorun tests kicked off https://ci.cfengine.com/view/Enterprise/job/testing-enterprise-pr/577/  using /merge for core.

**Comment by olehermanse** [comment]
@nickanderson Failed on 3 platforms:

Solaris 10 x86:
```
17:47:35 ./promises/autorun-D.cf FAIL (UNEXPECTED FAILURE)
17:47:35 gmake[3]: [promises/autorun-D.cf_rule] Error 1 (ignored)
17:47:36 ./promises/autorun.cf FAIL (UNEXPECTED FAILURE)
17:47:36 gmake[3]: [promises/autorun.cf_rule] Error 1 (ignored)
17:47:37 ./promises/promises.cf Pass
```

RHEL 6:
```
17:20:51 4 is not within the range 5-1051200
17:20:51 ERROR: sysinfo_test.c:14 Failure!
17:20:51 1 out of 1 tests failed!
17:20:51     test_uptime
```

Solaris 10 sparc64:
```
17:38:47 ./compliance/cases/service_running.cf Pass
17:38:47 ./diff_reporting/diff_reporting_large_file.cf Pass
17:39:10 ./diff_reporting/diff_reporting.cf Pass
17:56:58 ./compliance/great_expectations.cf FAIL (UNEXPECTED FAILURE)
17:56:58 Makefile.testall:35: recipe for target 'compliance/great_expectations.cf_rule' failed
17:56:58 gmake[4]: Leaving directory '/home/jenkins/workspace/testing-enterprise-
```

**Comment by jimis** [comment]
This 79d22491b0ca9f8ccdc4697c522d844d0ed7e8ce needs more commits from its pull request to be complete, and was deemed too complicated so do not cherry-pick by itself.

**Comment by jimis** [comment]
This 8c7577c0e41fd75c44e84b23ade13c0958596ae4 is a new feature or intrusive fix so I don't suggest cherry-pick.

**Comment by jimis** [comment]
This dec0ce5f8e6bb6f6d6b7946d77b9f706a4d2d10b says on the ticket that it applies only to 3.10. Is it really a bug on 3.7.x as well? The rule is to **never break stable branches** so cherry-picks should start from an empty set, and include only the ones needed.

**Comment by jimis** [comment]
The rest look minor but they should be OK.

**Comment by olehermanse** [comment]
> This 79d2249 needs more commits from its pull request to be complete, and was deemed too complicated so do not cherry-pick by itself.

@jimis That commit is not a part of this PR, why comment on it here?

**Comment by olehermanse** [comment]
> This 8c7577c is a new feature or intrusive fix so I don't suggest cherry-pick.

Removing

**Comment by olehermanse** [comment]
> This dec0ce5 says on the ticket that it applies only to 3.10. Is it really a bug on 3.7.x as well? The rule is to never break stable branches so cherry-picks should start from an empty set, and include only the ones needed.

Removed mentioned commit

**Comment by olehermanse** [comment]
@jimis Removed 2 commits you mentioned, the third was not in this PR (?)

**Comment by jimis** [comment]
Thanks!

**Pull request merged**
