### PR TITLE
CFE-2886: Renamed variable which was shadowing a parameter

### PR DESCRIPTION
**Pull request by olehermanse**
Reported by LGTM:
https://lgtm.com/rules/2156240606/

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1257/)

https://ci.cfengine.com/job/pr-pipeline/1257/

**Comment by olehermanse** [comment]
@vpodzime Please review, mustache expert ;)

**Comment by olehermanse** [comment]
This pull request **fixes 1 alert** when merging c83a30ad57da9e9e1c2e28e4c438b35ea7678932 into e9bba02a349da978b323d107eafac84ad00b0959 - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-949dcd051f2219def744ee9a5a938b6c6edde81e)

**fixed alerts:**

* 1 for Declaration hides parameter

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1265/)

https://ci.cfengine.com/job/pr-pipeline/1265/

**Comment by olehermanse** [comment]
This pull request **fixes 1 alert** when merging ba522545c237d6bb9ffe34be22b8f5953ef9ba0c into e9bba02a349da978b323d107eafac84ad00b0959 - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-2f2f1c1c903b744240fc4eed0501995460c9db2a)

**fixed alerts:**

* 1 for Declaration hides parameter

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by olehermanse** [comment]
This pull request **fixes 1 alert** when merging ba522545c237d6bb9ffe34be22b8f5953ef9ba0c into cad5f792566a4110172dd19a6974ce0ea0ba6835 - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-95f9d4ec031315b8cd0269d056e9ed3ab0a53587)

**fixed alerts:**

* 1 for Declaration hides parameter

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
