### PR TITLE
CFE-2857: Reload persistent classes and fix related memory errors (3.12)

### PR DESCRIPTION
**Pull request by olehermanse**
Cherry-picks from: #3396

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins with exotics.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1602/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1602/

**Comment by olehermanse** [comment]
This pull request **fixes 1 alert** when merging 1afc4a53d1ad6a749a8290e977ef1baaaadac906 into a14b2d5abb67674e552c657d2970b5616923434e - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-04167c9ce89ea09ea9e49b66c1ae94132b10acbc)

**fixed alerts:**

* 1 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1637/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1637/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1641/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1641/

**Pull request merged**
