### PR TITLE
ENT-5125 Reverted cf-hub systemd Requires cf-postgres in systemd unit (3.18.x)

### PR DESCRIPTION
**Pull request by craigcomstock**
merge together
https://github.com/cfengine/core/pull/4737
https://github.com/cfengine/masterfiles/pull/2017

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6866/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6866/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6866/

**Comment by craigcomstock** [comment]
bootstrap test failure might be a flake, see https://tracker.mender.io/browse/ENT-7275

**Pull request merged**
