### PR TITLE
CFE-3625: Set Filedescriptor Limit to a more practical Size

### PR DESCRIPTION
**Pull request by flynn1973**
Ticket: CFE-3625
Changelog: Title

### CODE REVIEW

**Review by vpodzime — APPROVED** [review]
ACK. Thanks!

**Review by olehermanse — APPROVED** [review]

**Comment by vpodzime** [comment]
@cf-bottom jenkins with exotics, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6486/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6486/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6486/

**Comment by olehermanse** [comment]
Small nitpick: The changelog entry for this should have been rewritten to focus on what the impact of this is to a user.

**Pull request merged**
