### PR TITLE
Fixes #7826: Allow '=' in symbolic modes

### PR DESCRIPTION
**Pull request by zofrex**
My initial stab at this. I'll add tests if it looks good.

### CODE REVIEW

**Comment by kacf** [comment]
This is looking good! Could you also add a test case to https://github.com/cfengine/core/blob/master/tests/acceptance/10_files/01_create/perms-mode.cf, containing the `ugo=rwx` syntax? There are several platforms there, but I think they should all handle it just fine, so just add it everywhere.

**Comment by kacf** [comment]
Any progress here?

**Comment by zofrex** [comment]
Took a swing at the tests last night but I think that test file is going to need some re-jigging to allow for "=" modes. I'll have more time to try again next week, HMU if you're on IRC and want to lend a hand :)

**Comment by zofrex** [comment]
The tests work! Things got pretty ugly, though. And coverage is not impressive. Input welcomed!

**Comment by tzz** [comment]
See below for a proposed patch (I also appended the full test) that uses expected state to simplify the test significantly and handle this new behavior. It's not going to work without some fixes to the JSON files but you should be able to see the intent. If you run it, the test will tell you what in the JSON data was incorrect and then you can adjust accordingly.

```diff
diff --git a/tests/acceptance/10_files/01_create/perms-mode.cf b/tests/acceptance/10_files/01_create/perms-mode.cf
index 36306ce..662e085 100644
--- a/tests/acceptance/10_files/01_create/perms-mode.cf
+++ b/tests/acceptance/10_files/01_create/perms-mode.cf
@@ -13,13 +13,13 @@ body common control
 
 #######################################################
 
-bundle agent test
+bundle agent init
 {
   vars:
     freebsd|solaris::
-      "modes" slist => { "1", "333", "100", "200", "777" };
+      "modes" slist => { "1", "333", "100", "200", "777", "o=x", "ugo=wx", "u=x", "u=w", "ugo=rwx" };
     !freebsd.!solaris::
-      "modes" slist => { "1", "333", "100", "200", "777", "1111", "1010", "13400", "22222" };
+      "modes" slist => { "1", "333", "100", "200", "777", "1111", "1010", "13400", "22222", "o=x", "ugo=wx", "u=x", "u=w", "ugo=rwx" };
 
   files:
       "$(G.testdir)/$(modes)"
@@ -32,71 +32,22 @@ body perms test_mode(m)
       mode => "$(m)";
 }
 
-bundle agent check
+bundle agent test
 {
   vars:
       "modes" slist => { @(test.modes) };
-    windows::
-      "win_r" string => "100444";
-      "win_w" string => "100666";
-      "expected" data => parsejson('
-{
-  "1": "$(win_r)",
-  "333": "$(win_w)",
-  "100": "$(win_r)",
-  "200": "$(win_w)",
-  "777": "$(win_w)",
-  "1111": "$(win_r)",
-  "1010": "$(win_r)",
-  "13400": "$(win_r)",
-  "22222": "$(win_r)",
-}');
-
-    freebsd|solaris::
-      "expected" data => parsejson('
-{
-  "1": "100001",
-  "333": "100333",
-  "100": "100100",
-  "200": "100200",
-  "777": "100777",
-}');
-
-    !freebsd.!solaris.!windows::
-      "expected" data => parsejson('
-{
-  "1": "100001",
-  "333": "100333",
-  "100": "100100",
-  "200": "100200",
-  "777": "100777",
-  "1111": "101111",
-  "1010": "101010",
-  "13400": "103400",
-  "22222": "102222",
-}');
-
-    any::
       "actual[$(modes)]" string => filestat("$(G.testdir)/$(modes)", "modeoct");
+}
 
-  classes:
-      "ok_$(modes)" expression => strcmp("$(expected[$(modes)])", "$(actual[$(modes)])");
-
-      freebsd|solaris::
-      "ok" and => { "ok_1", "ok_333", "ok_100", "ok_200", "ok_777" };
-
-      !freebsd.!solaris::
-      "ok" and => { "ok_1", "ok_333", "ok_100", "ok_200", "ok_777", "ok_1111", "ok_1010", "ok_13400", "ok_22222" };
 
-  reports:
-    DEBUG::
-      "Permission $(modes) worked, got $(expected[$(modes)])" ifvarclass => "ok_$(modes)";
-      "Permission $(modes) failed, expected $(expected[$(modes)]) != actual $(actual[$(modes)])" ifvarclass => "!ok_$(modes)";
-    ok::
-      "$(this.promise_filename) Pass";
-    !ok::
-      "$(this.promise_filename) FAIL";
+bundle agent check
+{
+  vars:
+      "suffix" string => ifelse("freebsd|solaris", "solaris-or-freebsd",
+                               "windows", "windows",
+                               "default");
+  methods:
+      "check"  usebundle => dcs_check_state(test,
+                                           "$(this.promise_filename).expected.$(suffix).json",
+                                           $(this.promise_filename));
 }
-
-### PROJECT_ID: core
-### CATEGORY_ID: 27
diff --git a/tests/acceptance/10_files/01_create/perms-mode.cf.expected.default.json b/tests/acceptance/10_files/01_create/perms-mode.cf.expected.default.json
new file mode 100644
index 0000000..d61bf13
--- /dev/null
+++ b/tests/acceptance/10_files/01_create/perms-mode.cf.expected.default.json
@@ -0,0 +1,16 @@
+{
+  "1": "100001",
+  "333": "100333",
+  "100": "100100",
+  "200": "100200",
+  "777": "100777",
+  "1111": "101111",
+  "1010": "101010",
+  "13400": "103400",
+  "22222": "102222",
+  "o=x": "100001",
+  "ugo=wx": "100333",
+  "u=x": "100100",
+  "u=w": "100200",
+  "ugo=rwx": "100777",
+}
diff --git a/tests/acceptance/10_files/01_create/perms-mode.cf.expected.solaris-or-freebsd.json b/tests/acceptance/10_files/01_create/perms-mode.cf.expected.solaris-or-freebsd.json
new file mode 100644
index 0000000..a6837a4
--- /dev/null
+++ b/tests/acceptance/10_files/01_create/perms-mode.cf.expected.solaris-or-freebsd.json
@@ -0,0 +1,12 @@
+{
+  "1": "100001",
+  "333": "100333",
+  "100": "100100",
+  "200": "100200",
+  "777": "100777",
+  "o=x": "100001",
+  "ugo=wx": "100333",
+  "u=x": "100100",
+  "u=w": "100200",
+  "ugo=rwx": "100777",
+}
diff --git a/tests/acceptance/10_files/01_create/perms-mode.cf.expected.windows.json b/tests/acceptance/10_files/01_create/perms-mode.cf.expected.windows.json
new file mode 100644
index 0000000..23ea6f8
--- /dev/null
+++ b/tests/acceptance/10_files/01_create/perms-mode.cf.expected.windows.json
@@ -0,0 +1,16 @@
+{
+  "1": "100444",
+  "333": "100666",
+  "100": "100444",
+  "200": "100666",
+  "777": "100666",
+  "1111": "100444",
+  "1010": "100444",
+  "13400": "100444",
+  "22222": "100444",
+  "o=x": "100444",
+  "ugo=wx": "100666",
+  "u=x": "100444",
+  "u=w": "100666",
+  "ugo=rwx": "100666",
+}
```

```cfengine3
#######################################################
#
# Redmine #4791: body perms mode
#
#######################################################

body common control
{
      inputs => { "../../default.cf.sub" };
      bundlesequence  => { default("$(this.promise_filename)") };
      version => "1.0";
}

#######################################################

bundle agent init
{
  vars:
    freebsd|solaris::
      "modes" slist => { "1", "333", "100", "200", "777", "o=x", "ugo=wx", "u=x", "u=w", "ugo=rwx" };
    !freebsd.!solaris::
      "modes" slist => { "1", "333", "100", "200", "777", "1111", "1010", "13400", "22222", "o=x", "ugo=wx", "u=x", "u=w", "ugo=rwx" };

  files:
      "$(G.testdir)/$(modes)"
      create => "true",
      perms => test_mode($(modes));
}

body perms test_mode(m)
{
      mode => "$(m)";
}

bundle agent test
{
  vars:
      "modes" slist => { @(test.modes) };
      "actual[$(modes)]" string => filestat("$(G.testdir)/$(modes)", "modeoct");
}


bundle agent check
{
  vars:
      "suffix" string => ifelse("freebsd|solaris", "solaris-or-freebsd",
                               "windows", "windows",
                               "default");
  methods:
      "check"  usebundle => dcs_check_state(test,
                                           "$(this.promise_filename).expected.$(suffix).json",
                                           $(this.promise_filename));
}
```

**Comment by kacf** [comment]
Thanks, @zofrex! Let's run this through the tester to see how it fares. And btw, I am available on IRC as kacfengine_, if you need help.

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
Thanks, @zofrex!

**Pull request merged**
