### PR TITLE
ENT-10206: Added mctp_socket class to selinux policy

### PR DESCRIPTION
**Pull request by craigcomstock**
Needed by rhel-9.2 linux kernel

Ticket: ENT-10206
Changelog: title

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9446/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9446/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9446/

**Review by nickanderson — APPROVED** [review]
Since cf-agent is unconfined, it needs pretty much everything.

**Review by vpodzime — APPROVED** [review]
Please make sure it works on RHEL 8 as well.

**Comment by craigcomstock** [comment]
> Please make sure it works on RHEL 8 as well.

Installing the hub package on rhel-8 it seems to work well:

```
semodule -l | grep cfengine
cfengine
cfengine-enterprise
```

**Pull request merged**
