### PR TITLE
ENT-9340: Fixed cf-support shellcheck check target (3.21)

### PR DESCRIPTION
**Pull request by craigcomstock**
Needed to check shellcheck command differently.

Ticket: ENT-9340
Changelog: none
(cherry picked from commit 999b930e6ba97f17a272d769a08730f05d9c4717)

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9189/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9189/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9189/

**Comment by craigcomstock** [comment]
retry [Build Status](https://ci.cfengine.com/job/pr-pipeline/9191/)

logged ticket ENT-9801 about the previous bootstrap-pr failure.

**Comment by craigcomstock** [comment]
redhat 7 client build passed so will merge.

**Pull request merged**
