### PR TITLE
ENT-11885: Adjusted masterfiles stage script to choose an available locale

### PR DESCRIPTION
**Pull request by craigcomstock**
- **Adjusted local settings in masterfiles stage common script to handle more cases**
- **Add option to use /etc/locale.conf if it is present**

together
https://github.com/cfengine/core/pull/5544
https://github.com/cfengine/nova/pull/2262

### CODE REVIEW

**Review by larsewi — APPROVED** [review]

**Comment by craigcomstock** [comment]
```
3.255.122.34	curl: (22) The requested URL returned error: 422 Unprocessable Entity
```
from the test command
```
6	:	1718670219.768	    61.559	0	25	22	0	curl -k -i --show-error --fail -u admin:admin -H 'content-type: application/json' -X POST -d @.4475.project_info https://63.35.194.52/api/build/projects && echo
```

Looks a bit suspicious. I will test a package manually.

**Comment by craigcomstock** [comment]
Yep, as I suspected, the segfault I found and have a fix for in 

https://github.com/cfengine/nova/pull/2264

was happening and breaking those tests, in one cf-support tarball, core-dump.log had the backtrace for the issue in ENT-11890

```
                #0  0x00007cc6f56a5449 free (libc.so.6 + 0xa5449)
                #1  0x00007cc6f5edf51f ArrayMapClear (libpromises.so.3 + 0xbf51f)
                #2  0x00007cc6f5edf5a8 ArrayMapDestroy (libpromises.so.3 + 0xbf5a8)
                #3  0x00007cc6f5eef651 MapDestroy (libpromises.so.3 + 0xcf651)
                #4  0x00007cc6f5ef4bbd SetDestroy (libpromises.so.3 + 0xd4bbd)
                #5  0x00007cc6f5ef4bd7 StringSetDestroy (libpromises.so.3 + 0xd4bd7)
                #6  0x00005f1c8356483e UpdateHostCMDBDataFile (cf-reactor + 0xf83e)
                #7  0x00005f1c835650b6 CMDBRefreshExecutor (cf-reactor + 0x100b6)
                #8  0x00007cc6f5694ac3 n/a (libc.so.6 + 0x94ac3)
                #9  0x00007cc6f5726850 n/a (libc.so.6 + 0x126850)
```

**Review by vpodzime — APPROVED** [review]
ACK

**Comment by craigcomstock** [comment]
cherry picks

https://github.com/cfengine/core/pull/5548
https://github.com/cfengine/core/pull/5547

**Pull request merged**
