### PR TITLE
Report failure to close the socket.

### PR DESCRIPTION
**Pull request by jimis**
I'm suspecting some CLOSE_WAIT problems, especially on windows, could be related to not properly closed sockets. So with this pull request, such failure is logged in verbose.

### CODE REVIEW

**Comment by jimis** [comment]
Do not merge, lets trigger a test build after the release is out.

**Comment by kacfengine** [comment]
Do you want to merge this now? It should be quite safe, even if it turns out not to be the problem.

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
Cherry-picking to 3.7.x for better debugging.

**Pull request merged**
