### PR TITLE
Fixed string formatting of integer types in several places

### PR DESCRIPTION
**Pull request by olehermanse**
Each commit has a short explanation. Most commits should be easily cherrypicked.

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @vpodzime can review this?

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1079/)

https://ci.cfengine.com/job/pr-pipeline/1079/

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by olehermanse** [comment]
@cf-bottom please trigger a jenkins build with exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1082/)

https://ci.cfengine.com/job/pr-pipeline/1082/

**Comment by olehermanse** [comment]
@cf-bottom test jenkins exotic

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1083/) - with exotics

https://ci.cfengine.com/job/pr-pipeline/1083/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1084/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1084/

**Comment by olehermanse** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/1086/)

**Comment by olehermanse** [comment]
@vpodzime I was more concerned with cherry-picking, them. I think it will be easier to cherry-pick individuals and just skip when there are conflicts.

**Comment by vpodzime** [comment]
> I think it will be easier to cherry-pick individuals and just skip when there are conflicts.

OK

**Pull request merged**
