### PR TITLE
Replaced uses of localtime with the safer localtime_r (3.12)

### PR DESCRIPTION
**Pull request by olehermanse**
Reported by LGTM:
https://lgtm.com/rules/2154840805/

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @vpodzime can review this?

**Comment by olehermanse** [comment]
@cf-bottom jenkins.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2348/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2348/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2348/

**Comment by olehermanse** [comment]
This pull request **fixes 2 alerts** when merging 7ce626358921a2f22dcc0eadac52588f0a62e2f5 into 2f35de22474c6f1a419679b5b5550828b7e394d9 - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-50108c165b2edfc503414f3f785e0a09435eadf5)

**fixed alerts:**

* 2 for Use of potentially dangerous function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
