### PR TITLE
ENT-9878: Added support for building and testing MacOS

### PR DESCRIPTION
**Pull request by craigcomstock**
together:
https://github.com/cfengine/libntech/pull/179
https://github.com/cfengine/core/pull/5204
https://github.com/cfengine/enterprise/pull/719
https://github.com/cfengine/nova/pull/2013

### CODE REVIEW

**Comment by craigcomstock** [comment]
due to our github workflows not yet supporting multi-repo pull request builds (see ENT-9196), let's have @cf-bottom test these changes.

**Review by vpodzime — APPROVED** [review]
ACK

**Comment by craigcomstock** [comment]
ubuntu 18 failure seems to be a fluke, maybe handle it with prohibiting auto upgrades? ([INF-3370](https://northerntech.atlassian.net/browse/INF-3370))

sequential-tests failed with known issue.

**Comment by craigcomstock** [comment]
cherry picked compiler fixes for clang 14 to
3.18.x https://github.com/cfengine/core/pull/5219
and
3.21.x https://github.com/cfengine/core/pull/5218

**Pull request merged**
