### PR TITLE
Support libntech's new efficient file/data copying

### PR DESCRIPTION
**Pull request by vpodzime**
We need to take care of the newly required checks in configure.ac because we are responsible for producing config.h usable for both us and libntech.

Ticket: CFE-4380
Changelog: File copying now uses more efficient implementation on
           Linux platforms

Merge together:
https://github.com/cfengine/core/pull/5490
https://github.com/NorthernTechHQ/libntech/pull/218

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @craigcomstock can review this?

**Review by larsewi — DISMISSED** [review]
🚀

**Comment by vpodzime** [comment]
@cf-bottom jenkins with exotics and no tests, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10689/)

(with exotics) [NO TESTS]

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10689/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10689/

**Comment by vpodzime** [comment]
@olehermanse @larsewi please see https://github.com/cfengine/core/pull/5490/commits/af3dbb762ef7b1c1d67a920f125fd239cf6e14cd and tell me what you think. tl;dr -- the new efficient copy code doesn't create sparse copies of non-sparse files which I believe is the right thing to do. But it is a change. (with no functional difference in CFEngine, of course)

**Comment by vpodzime** [comment]
@cf-bottom jenkins with exotics, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10692/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10692/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10692/

**Review by larsewi — DISMISSED** [review]
LGTM 🚀

**Review by craigcomstock — APPROVED** [review]

**Comment by vpodzime** [comment]
@cf-bottom jenkins with exotics, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10700/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10700/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10700/

**Comment by vpodzime** [comment]
I thought this was done, but something weird is going on on Ubuntu 16. It doesn't have `copy_file_range()`, which is OK, it has `sendfile()` and everything else that is needed here. However, the tests fail so something doesn't work there. I'll have to try to reproduce the issue on some Ubuntu 16 machine and debug it. :roll_eyes: :scream: :tired_face:

**Review by craigcomstock — APPROVED** [review]

**Comment by vpodzime** [comment]
@cf-bottom jenkins with exotics, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10775/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10775/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10775/

**Review by larsewi — APPROVED** [review]

**Pull request merged**
