### PR TITLE
Route parsing

### PR DESCRIPTION
**Pull request by kacf**

### CODE REVIEW

**Comment by kacf** [comment]
Originally from #2245.

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
Fails on the Solarises for so far unidentified reasons. I'll see if I can dig into it.

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
Only the Windows build is broken now. I'll try to get that fixed tomorrow.

**Comment by kacf** [comment]
Attempted fixed in https://github.com/cfengine/enterprise/pull/301.

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
Alright, this build is finally green! Can you update the docs, Ted?

**Comment by tzz** [comment]
Can this be closed or is there something I need to do?

**Comment by kacf** [comment]
No, this should be closed, superseded by the other one.

**Pull request closed without merging**
