### PR TITLE
ENT-6433: junk commit to debug jenkins builds

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6018/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6018/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6018/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins again after fixing static checks

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6019/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6019/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6019/

**Comment by craigcomstock** [comment]
@cf-bottom as daft punk says... "one more time..." ;)

**Comment by cf-bottom** [comment]
I'm not sure I understand, @craigcomstock.

**Comment by craigcomstock** [comment]
@cf-bottom I guess I need to teach you that if I say "one more time" then you do the last thing I asked you to do. #TODO ;) jenkins again please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6020/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6020/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6020/

**Comment by craigcomstock** [comment]
sorry to be a bother, but @cf-bottom would you please do a jenkins run again for me? thanks.

**Review by cf-bottom — CHANGES_REQUESTED** [review]
Please use a company e-mail instead of c***@unreasonablefarm.org

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6021/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6021/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6021/

**Comment by craigcomstock** [comment]
did not produce any usable information, closing. :)

**Pull request closed without merging**
