### PR TITLE
CFE-2580: fix IPv6 parsing to be un-reversed

### PR DESCRIPTION
**Pull request by tzz**
This will need tests to be adjusted probably but it's definitely wrong in the C code.

@matya thank you

### CODE REVIEW

**Comment by matya** [comment]
@tzz You might want to change the tests' *.expected.json to have the IPv6 address reversed:
```json
{
  "default_gateway": "192.168.2.1",
  "docker": "d7b4:febd:49ff:42:0:0:0:fe80",
```

**Comment by tzz** [comment]
@jimis @kacf rebased and tests fixed, sorry it took me so long. This is a bug fix so I hope it can make it into 3.11.

**Comment by tzz** [comment]
@matya @nickanderson workaround for this for 3.10 and lower is probably to split on `:`, something like `"good" string => join(":", reverse(string_split($(address), ":", 32)))` (broken into stages as needed).

**Comment by jimis** [comment]
Thanks @tzz! Cherry-picking to all maintenance branches.

**Comment by jimis** [comment]
It doesn't cherry-pick cleanly to 3.7.x, the hex parser is completely different. If you can verify that 3.7.x still presents the wrong representation, I would be happy to merge a pull request specifically on the branch, updating the hex parser to the new one.

**Comment by tzz** [comment]
@jimis I wouldn't worry about it.

**Pull request merged**
