### PR TITLE
3.10.x cherry-picks

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1533/)

https://ci.cfengine.com/job/pr-pipeline/1533/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1535/)

https://ci.cfengine.com/job/pr-pipeline/1535/

**Comment by olehermanse** [comment]
@craigcomstock @vpodzime Please review if you agree with these cherry-picks. We can remove some if you think they are unnecessary.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1538/)

https://ci.cfengine.com/job/pr-pipeline/1538/

**Pull request merged**
