### PR TITLE
CFE-3471: Extensive test of and() function

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
Waiting for: https://github.com/cfengine/core/pull/4366

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5859/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5859/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5859/

**Comment by olehermanse** [comment]
@cf-bottom please run this in jenkins again, just in case.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5862/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5862/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5862/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5865/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5865/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5865/

**Review by vpodzime — APPROVED** [review]
Nice! :+1:

**Comment by olehermanse** [comment]
Cherry-picks:
https://github.com/cfengine/core/pull/4378
https://github.com/cfengine/core/pull/4379

**Pull request merged**
