### PR TITLE
Redmine#7211 Fix common bundles evaluation in server.

### PR DESCRIPTION
**Pull request by pasinskim**
Previous fix of server promises evaluation order didn't include
promises in common bundles which are obviously evaluated by cf-serverd.
This fix adds explicit evaluation of promises from common bundles.

### CODE REVIEW

**Comment by pasinskim** [comment]
@jimis @kacfengine can you take a look at this one?

**Comment by kacfengine** [comment]
+1

**Comment by kacfengine** [comment]
trigger build

**Comment by jimis** [comment]
Looks OK, I don't quite understand why it's needed though. A reference to the previous commit that broke things would be nice.

**Comment by kacfengine** [comment]
Cherry-picked to 3.7.x as well.

**Pull request merged**
