### PR TITLE
Define new $(edit.empty_before_use variable) for edit_line bundles

### PR DESCRIPTION
**Pull request by vpodzime**
So that edit_line bundles can make decisions based on whether the
file contents are descarded first or not.

Ticket: ENT-5866
Changelog: edit_line bundles can now use the new
$(edit.empty_before_use) variable mirroring the value of
edit_defaults=>empty_before_use of the related files promise

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom make a build for @nickanderson so that he has something to play with, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8305/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8305/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8305/

**Comment by nickanderson** [comment]
Yeah, i wanna try out: 

```
      # Check to see if this line exists
      "exists_$(ci[$(i)])"
      expression => regline("^\s*($(i)$(bp).*|$(i))$",
                            $(edit.filename)),
      if => strcmp( "true", $(edit.empty_before_use) );


```

**Comment by nickanderson** [comment]
Well, not() or unless => on that

**Review by olehermanse — APPROVED** [review]
Changes look okay to me, but I'll leave it to @nickanderson to finish the masterfiles PR and test this.

**Review by nickanderson — APPROVED** [review]
It works for me.

**Pull request merged**
