### PR TITLE
Moved seteuid implementation to libcompat

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins with exotics please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1864/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1864/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1865/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1865/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1867/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1867/

**Comment by olehermanse** [comment]
Cherry-picks: 

https://github.com/cfengine/core/pull/3477
https://github.com/cfengine/core/pull/3478

**Pull request merged**
