### PR TITLE
CFE-2997 Fix cf-key help output to indicate ability to delete by key digest (3.10.x)

### PR DESCRIPTION
**Pull request by nickanderson**
(cherry picked from commit 18d73537ebcbb99e428705b25c5187f44e4b67a6)

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2152/)

https://ci.cfengine.com/job/pr-pipeline/2152/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2157/)

https://ci.cfengine.com/job/pr-pipeline/2157/

**Pull request merged**
