### PR TITLE
missing_ok basvandervlies gh2679 cfe2365

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
DO NOT MERGE, it's only for testing in Jenkins.

**Comment by basvandervlies** [comment]
@jimis I am with the changes, thanks for looking into it.

**Comment by jimis** [comment]
Tests in Jenkins came out green, besides the usual spurious failures.

@Lex-2008 do you understand if something is wrong with the Travis "old versions" test? The two new tests say "unknown results" in the summary, but in the detailed listing they show up as "pass".

**Comment by jimis** [comment]
@Lex-2008 you may want to review the changes in serverd_multi_versions.sh script.

**Comment by jimis** [comment]
OK looks good, squashing into one commit and merging!

**Comment by basvandervlies** [comment]
yes :-D

**Comment by jimis** [comment]
Took a while, but was worth it. ;-)

**Comment by jimis** [comment]
@basvandervlies can you also submit a pull request in docs?

**Comment by atsaloli** [comment]
Woo-hoo!  Great!  👍 😎 🥇

**Comment by basvandervlies** [comment]
@jimis i will submit a pull request for the docs when I am back from holidays

**Pull request merged**
