### PR TITLE
CFE-2084: Load multiple augments from "augments" string array in def.json.

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
Running it through jenkins.

**Comment by jimis** [comment]
@tzz can you approve the changes to the json and cf test files? I believe Travis will give us the green light shortly.

**Comment by jimis** [comment]
Ugh Travis still disagrees. Investigating...

**Comment by Lex-2008** [comment]
Yes it's an issue with the tests - I'll investigate it

**Pull request merged**
