### PR TITLE
ENT-6098 fix init_script_test.sh failure of suse 12 and 15

### PR DESCRIPTION
**Pull request by Lex-2008**
fixes suse 12.

merge together:
https://github.com/cfengine/buildscripts/pull/762

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom: build it please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5488/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5488/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5488/

**Comment by Lex-2008** [comment]
next time, only suse build is needed :)

**Comment by Lex-2008** [comment]
@cf-bottom green build, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5498/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5498/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5498/

**Comment by Lex-2008** [comment]
retry of the above failed build: https://ci.cfengine.com/job/pr-pipeline/5500/

**Pull request merged**
