### PR TITLE
Add: Acceptance test for abortbundleclasses

### PR DESCRIPTION
**Pull request by nickanderson**
Test that the agent aborts the current bundle when an exact abortclass is
matched and that the agent continues on to the next bundle.

Test that the agent aborts the current bundle when a regular expression is
matched and that the agent continues on to the next bundle.

### CODE REVIEW

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
I'm a bit confused, all tests have ``"test_soft_fail" string => "!any"``, which means that they all need to pass (note "!any"). Does that mean that the bug is fixed? In that case the ticket should be closed, and ``test_soft_fail`` should be removed entirely.

The build was green, btw.

**Comment by kacfengine** [comment]
Ping.

**Comment by nickanderson** [comment]
Sorry didnt see the ping.

This was just a test to prove that abortbundleclasses work (it does, but there was no test).

I can remove the test_soft_fail. I just set it to !any, because it should fail softly nowhere, basically a no-op.

**Comment by kacfengine** [comment]
I guess it's ok to leave the soft_fail in, it's actually a nice way to document which ticket is associated with the test case. But the ticket is still open, shouldn't it be closed if the test passes?

**Comment by kacfengine** [comment]
@pasinskim said he found the "!any" soft failures confusing, so maybe they should be removed instead. It's easy to miss that it says "!any".

**Comment by nickanderson** [comment]
yeah I kind of liked the documentation aspect of the !any, but I will remove it since you ask.

It could be !cfengine instead of !any but i don't suppose that would be very different.

**Comment by nickanderson** [comment]
UGH! will re-open

**Comment by nickanderson** [comment]
Replaced by https://github.com/cfengine/core/pull/2359

**Pull request closed without merging**
