### PR TITLE
Changed occurences of `(f)open` to `safe_(f)open`

### PR DESCRIPTION
**Pull request by karlhto**
Should be the last ones in core.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins with exotics, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4120/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4120/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4120/

**Comment by olehermanse** [comment]
@cf-bottom one more run in jenkins, with exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4129/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4129/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4129/

**Comment by olehermanse** [comment]
@cf-bottom It looks like this breaks fr-tests somehow? Let's try one more time in Jenkins, with exotics.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4132/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4132/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4132/

**Comment by vpodzime** [comment]
> Alright, I triggered a build:
> 
> [Build Status](https://ci.cfengine.com//job/pr-pipeline/4132/)
> 
> (with exotics)
> 
> **Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4132/

Looks reasonably green:tm:  to me.

**Pull request merged**
