### PR TITLE
CFE-2438: Allow editing fields in lines longer than 4k

### PR DESCRIPTION
**Pull request by amousset**
Replace the `CF_BUFSIZE` buffer by a Writer in `Rlist2String` to allow writing long lines.

### CODE REVIEW

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
The new test fails in all the buildslaves.

**Comment by amousset** [comment]
Indeed, wrong version of the test, I updated it.

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
Strange, still failed, let me try once again: trigger build

**Comment by amousset** [comment]
Sorry, I did not actually update the test... Should be ok now.

**Comment by amousset** [comment]
@jimis This test should pass now.

**Comment by jimis** [comment]
@amousset Our CI is having issues, will check once it's back up.

**Comment by amousset** [comment]
@jimis Rebased, Travis build passed.

**Comment by jimis** [comment]
Thanks @amousset, merged and cherry-picked to all maintainance branches.

**Pull request merged**
