### PR TITLE
libntech: CFE-3415: Fixed some sign-compare warnings

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
This was merged: https://github.com/cfengine/libntech/pull/109

**Comment by nickanderson** [comment]
sorry, thought the pr was stale, re-opened.

**Review by craigcomstock — APPROVED** [review]

**Review by nickanderson — APPROVED** [review]

**Review by vpodzime — APPROVED** [review]
ACK

**Comment by larsewi** [comment]
@olehermanse should we not close this one and instead try to merge this one #4448 ?

**Comment by olehermanse** [comment]
> @olehermanse should we not close this one and instead try to merge this one #4448 ?

@larsewi yes.

**Pull request closed without merging**
