### PR TITLE
Open custom measurements in cf-monitord

### PR DESCRIPTION
**Pull request by jimis**
To be merged together with cfengine/enterprise#328

### CODE REVIEW

**Comment by jimis** [comment]
@nickanderson how do you like it?

**Comment by jimis** [comment]
tested [here](https://ci.cfengine.com/job/testing-enterprise-pr/590/)

**Comment by vpodzime** [comment]
@jimis, I think a more elaborate commit message would make things a lot clearer.

**Comment by jimis** [comment]
@vpodzime I can't elaborate more, unfortunately. This is functionality unknown for years, with a lot of undocumented corners. @nickanderson will elaborate with a couple of followup blog posts and hopefully documentation. As details unravel, followup changelogs can come later with empty commits. Overall, this is what it says:  a new promise type, specifically for cf-monitord, called "measurements".

**Comment by jimis** [comment]
@nickanderson let us know here if your tests are succesful, the build is looking good! :-)

**Comment by vpodzime** [comment]
> Overall, this is what it says: a new promise type, specifically for cf-monitord, called "measurements".

Thanks for the summary!

**Pull request merged**
