### PR TITLE
libntech: nt_static_assert() and int64_t functions

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom please test this in jenkins, with exotics.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5756/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5756/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5756/

**Review by craigcomstock — APPROVED** [review]

**Comment by olehermanse** [comment]
HPUX failure seems unrelated.

**Comment by olehermanse** [comment]
Aborted build since it was stuck waiting for offline node. Seems green enough.

**Pull request merged**
