### PR TITLE
CFE-3210: Fixed memory leaks found by AddressSanitizer (ASAN)

### PR DESCRIPTION
**Pull request by olehermanse**
Found using AddressSanitizer (ASAN). To compile with ASAN:

```
make CFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address"
```

To run all examples:

```
find /northern.tech/cfengine/core/examples -name '*.cf' | xargs -n 1 "/var/cfengine/bin/cf-agent" 2>&1 1>/dev/null | tee output.txt
```

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4237/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4237/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4237/

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4245/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4245/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4245/

**Pull request merged**
