### PR TITLE
Assertions and range checks

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2315/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2315/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2315/

**Comment by olehermanse** [comment]
This pull request **fixes 2 alerts** when merging 77d69e552a55f41776b6970a4cf053f7879b3197 into a598a5209ac756d6f88be3a588ddf325ddea37bd - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-b5d4845f2d33a3f2526171444732ea2ff40026a1)

**fixed alerts:**

* 2 for Array offset used before range check

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2317/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2317/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2317/

**Comment by olehermanse** [comment]
Cherry-picks: https://github.com/cfengine/core/pull/3614 https://github.com/cfengine/core/pull/3615

**Pull request merged**
