### PR TITLE
Select fix

### PR DESCRIPTION
**Pull request by jimis**
Switched all select() code with poll().

TODO create libcompat poll() wrapper for old OS.

### CODE REVIEW

**Comment by jimis** [comment]
Must include in 3.7, will try to update.

**Comment by ediosyncratic** [comment]
On Fri, Mar 20, 2015 at 3:00 PM, Dimitrios Apostolou <
notifications@github.com> wrote:

> Must include in 3.7, will try to update.
>

Let me know when it's time to review the updated fix ...

    Eddy.

**Comment by kacfengine** [comment]
Closing for now. We should do this at some point, since ``poll()`` is both safer and faster, but we will need more code here to cater to the handicapped platforms.

**Comment by worr** [comment]
Hey, before I go ahead and submit a new PR for this, could we import libressl's `poll(2)` wrapper? This would solve this problem, without having to reinvent the wheel. It's public domain, so licensing shouldn't be a problem.

https://github.com/libressl-portable/portable/blob/a7f031ba55ac4a69263000357eb7f6d7fb88101a/apps/openssl/compat/poll_win.c

**Comment by jimis** [comment]
@worr nice find! Yes feel free to import it.

**Pull request closed without merging**
