### PR TITLE
CFE-3457 CFE-3489: Added warning when trying to use {{.}} to expand containers in mustache templates

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5918/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5918/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5918/

**Comment by olehermanse** [comment]
Cherry-pick: https://github.com/cfengine/core/pull/4393

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5921/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5921/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5921/

**Review by craigcomstock — APPROVED** [review]

**Pull request merged**
