### PR TITLE
ENT-3970: Fix sys.flavor on AIX to not include minor version 3.10.x

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom can you test on Jenkins, with exotics, please?

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1772/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1772/

**Comment by olehermanse** [comment]
@nickanderson any idea why this failed? 

```
./diff_reporting/diff_reporting_large_file.cf.diff_reporting_large_file.cf
```

**Comment by nickanderson** [comment]
solar flare

**Pull request merged**
