### PR TITLE
Make sort() and eval() mode arguments default to lex and math/infix and adjust tests

### PR DESCRIPTION
**Pull request by tzz**
I think this is a nice cleanup.

* `eval(x)` is now the same as `eval(x, "math", "infix")` and `eval(x, y)` is now the same as `eval(x, y, "infix")`
* `sort(x)` is now the same as `sort(x, "lex")`
* tests have been adjusted
* the `sort()` test was vastly simplified by using `expected.json` but it needs a full check. It looked OK to me but it's a lot of data. @nickanderson if you feel up to it?

### CODE REVIEW

**Comment by nickanderson** [comment]
Regarding the usability improvements YES.
Regarding sort test, i will take a look.

**Comment by nickanderson** [comment]
trigger build

**Comment by nickanderson** [comment]
trigger build

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
Superseded by #2559.

**Pull request closed without merging**
