### PR TITLE
Redmine #6442: Revert branches that were prematurely merged.

### PR DESCRIPTION
**Pull request by kacfengine**
* Network promises
* Reworked guest_environments promise with Docker support
* SQLite backend for database promise.

They are untested and their readiness have not been verified by any
developers in CFEngine. We may revisit them in the future, but for now
keep them out of mainline, since we can't support them and we want to
reduce risk of breakage.

### CODE REVIEW

**Comment by kacfengine** [comment]
@jimis: Let me know if you see anything that shouldn't be removed here.

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
Build is green.

**Comment by jimis** [comment]
Will review the networking part.

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
I'm going to merge this if it passes, since we need to start testing, and this branch needs to be rebased quite often. We can review the network changes after the fact.

**Pull request merged**
