### PR TITLE
Redmine #7297: Make sure systemd is detected if PID 1 is a symlink

### PR DESCRIPTION
**Pull request by jimis**
(E.g. on Debian).

### CODE REVIEW

**Comment by kacfengine** [comment]
Good idea to use ``realpath``. It is simpler indeed.

**Comment by jimis** [comment]
> Good idea to use realpath. It is simpler indeed

And it will follow all possible symlinks, for example you might need two dereferences to reach the goal.

**Comment by kacfengine** [comment]
Indeed.

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
Cherry-picked to both 3.6.x and 3.7.x.

**Comment by jrobeson** [comment]
isn't it best to use /proc/1/comm to detect systemd ?

**Comment by kacfengine** [comment]
Both are good ways I think.

**Comment by jimis** [comment]
@jrobeson `/proc/1/comm` doesn't exist on old kernels.

**Comment by jrobeson** [comment]
and those old kernels can't run systemd either.

**Pull request merged**
