### PR TITLE
ENT-4858: sys.interfaces now contains IPv6-only network interfaces

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2648/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2648/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2648/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2649/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2649/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2649/

**Comment by olehermanse** [comment]
Posted new PR because GitHub was bugged: https://github.com/cfengine/core/pull/3801

**Pull request closed without merging**
