### PR TITLE
3.10.x: Update travis files to master

### PR DESCRIPTION
**Pull request by olehermanse**
I noticed that 3.10.x was very outdated compared to master, builds were failing because of issues fixed in master.

### CODE REVIEW

**Comment by olehermanse** [comment]
@jimis : Some of the commits missing are here: https://github.com/cfengine/core/pull/2911

But that's not all of them. Of course cherry picking is nicer than just overwriting, but I have no good way to find all the commits missing, maybe you can work your `git magic` ;)

**Comment by olehermanse** [comment]
Damn editor updates

**Comment by olehermanse** [comment]
@jimis Fixed

**Comment by jimis** [comment]
Thanks!

**Pull request merged**
