### PR TITLE
Updated libntech to latest upstream master

### PR DESCRIPTION
**Pull request by KotzaBoss**

### CODE REVIEW

**Comment by KotzaBoss** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6649/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6649/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6649/

**Review by olehermanse — APPROVED** [review]
Goodie, just wait a little bit for tests to finish.

**Comment by olehermanse** [comment]
Looks green enough to me.

**Pull request merged**
