### PR TITLE
CFE-3719: Fixed some memory leaks in cf-key (3.15.x)

### PR DESCRIPTION
**Pull request by larsewi**
cherry-picked from master - https://github.com/cfengine/core/pull/4749

### CODE REVIEW

**Comment by larsewi** [comment]
@cf-bottom Jenkins please !

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7005/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7005/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7005/

**Review by olehermanse — APPROVED** [review]
ACK, awaiting CI.

**Comment by larsewi** [comment]
@cf-bottom Jenkins please !

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7035/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7035/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7035/

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
