### PR TITLE
ENT-10699: Fixed windows acceptance test workflow

### PR DESCRIPTION
**Pull request by craigcomstock**
- Improve and re-enable windows acceptance test workflow
- Adjust expectations of windows acceptance tests

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @larsewi can review this?

**Comment by craigcomstock** [comment]
trying a rebuild of last night's master win-acceptance job in jenkins: [Build Status](https://ci.cfengine.com/job/win-acceptance/757/)

**Review by larsewi — APPROVED** [review]
🚀

**Comment by craigcomstock** [comment]
not sure I want to cherry-pick, but will try
https://github.com/cfengine/core/pull/5502
https://github.com/cfengine/core/pull/5501

**Pull request merged**
