### PR TITLE
CFE-623 Promise is KEPT when copy_from compare exits is true

### PR DESCRIPTION
**Pull request by nickanderson**
Changelog: Title

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @vpodzime can review this?

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2193/)

https://ci.cfengine.com/job/pr-pipeline/2193/

**Comment by nickanderson** [comment]
didnt work.

**Pull request closed without merging**
