### PR TITLE
Windows mustache rendering fixes

### PR DESCRIPTION
**Pull request by vpodzime**
See commit message for details.

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @olehermanse can review this?

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1224/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1224/

**Comment by vpodzime** [comment]
@cf-bottom jenkins with exotics, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1234/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1234/

**Comment by vpodzime** [comment]
> Good. There is a small merge conflict with my recently merged PR.

Rebased.

**Pull request merged**
