### PR TITLE
Enable TLS protocol by default, for outgoing connections.

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
So simple! I'm wondering who implemented this so beautifully! ;-)

@kacfengine I'll let the merge button for you :-)

**Comment by jimis** [comment]
trigger build

**Comment by kacfengine** [comment]
> So simple! I'm wondering who implemented this so beautifully! ;-)

Hehehe.

Just so we are clear about the consequences, the only thing that will stop working after this is bootstrapping a 3.7 client to a 3.5 hub right?

**Comment by kacfengine** [comment]
(Although you can bootstrap manually)

**Comment by jimis** [comment]
Rebased because of conflicts.

@kacfengine you are right about the consequences, I've described them in more detail in [redmine#5434](https://dev.cfengine.com/issues/5434).

**Pull request merged**
