### PR TITLE
ENT-10206: Added mctp_socket class to selinux policy (3.21)

### PR DESCRIPTION
**Pull request by craigcomstock**
Needed by rhel-9.2 linux kernel

Ticket: ENT-10206
Changelog: title
(cherry picked from commit f3ef17c3ec2d8afb35a73ced6938750aefb84a5f)

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9449/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9449/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9449/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins again please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9454/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9454/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9454/

**Comment by craigcomstock** [comment]
green enough, sequential-tests failure is ssh flake

**Pull request merged**
