### PR TITLE
Removed unneeded cfengine3-web.service.in (3.12.x)

### PR DESCRIPTION
**Pull request by craigcomstock**
The cfengine3-web service was removed from packaging in the following
buildscripts commit and should not be needed here in core anymore.

https://github.com/cfengine/buildscripts/commit/fdbe42f4b54e02230602a4d76b0a50aad4efe23c

Changelog: None
(cherry picked from commit 755f3cec3bc25f832f6403eaaa679e48e38df841)

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5143/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5143/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5143/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins try this again. PR should be fine to merge if you wish to ignore CI. It is merged in master and 3.15.x with no issues.

**Comment by craigcomstock** [comment]
Might try this PR in CI again tomorrow but we could probably merge if we wished. The same change is present in master and 3.15.x with no bad effects. @olehermanse @vpodzime

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5145/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5145/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5145/

**Comment by craigcomstock** [comment]
Merging this since the most recent CI failure was only a flaky/bad php selenium test run.

**Pull request merged**
