### PR TITLE
CF-2951: ps command can handle longer usernames

### PR DESCRIPTION
**Pull request by basvandervlies**
Increased it to 30 chars instead of 8

Changelog: title

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @olehermanse can review this?

**Comment by vpodzime** [comment]
@cf-bottom jenkins with exotics, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1709/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1709/

**Comment by vpodzime** [comment]
@basvandervlies this seems to be braking one process related unit test on some older Debian/Ubuntu systems. I think the [`GetSysUsers()` function in that test](https://github.com/cfengine/core/blob/master/tests/unit/mon_processes_test.c#L29) needs to be changed too.

**Comment by olehermanse** [comment]
@cf-bottom let's try in jenkins with exotics.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1905/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1905/

**Comment by vpodzime** [comment]
Looks good to me too. @basvandervlies could you please squash the commits? Thanks!

**Comment by basvandervlies** [comment]
I have squashed the commits @vpodzime

**Comment by olehermanse** [comment]
Cherry-picks:
https://github.com/cfengine/core/pull/3490
https://github.com/cfengine/core/pull/3491

**Pull request merged**
