### PR TITLE
ENT-9340: Fixed cf-support shellcheck check target (3.18)

### PR DESCRIPTION
**Pull request by craigcomstock**
Needed to check shellcheck command differently.

Ticket: ENT-9340
Changelog: none
(cherry picked from commit 999b930e6ba97f17a272d769a08730f05d9c4717)

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9188/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9188/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9188/

**Comment by craigcomstock** [comment]
retry [Build Status](https://ci.cfengine.com/job/pr-pipeline/9192/)

**Comment by craigcomstock** [comment]
redhat 7 client build worked, so merging for nightly CI

**Pull request merged**
