### PR TITLE
ENT-10258: Bring needed selinux fixes from master for RHEL 8 (3.18)

### PR DESCRIPTION
**Pull request by craigcomstock**
We didn't cherry pick all the needed fixes on master for RHEL 8 to 3.18.x branch.

Ticket: ENT-10258
Changelog: title

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9508/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9508/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9508/

**Review by vpodzime — APPROVED** [review]
ACK

**Comment by craigcomstock** [comment]
missed `type ssh_exec_t` due to it being involved in a cfbs change that we didn't cherry pick to 3.18.x because cfbs is not present there but then it was needed by a later change in master.

```
09:46:17 cfengine-enterprise.te:255:ERROR 'unknown type ssh_exec_t' at token ';' on line 3174:
```

@cf-bottom jenkins again please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9512/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9512/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9512/

**Comment by craigcomstock** [comment]
Looks green enough and I tested a few things manually with this latest PR build on rhel-8 and things look generally good. A few denied messages left in /var/log/audit/audit.log but nothing that seems to be preventing functionality.

**Pull request merged**
