### PR TITLE
Made the log messages for files content attribute a bit easier to read

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by nickanderson** [comment]
Nice.

**Review by nickanderson — APPROVED** [review]

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7725/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7725/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7725/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7727/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7727/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7727/

**Review by craigcomstock — APPROVED** [review]

**Review by larsewi — APPROVED** [review]
✅

**Comment by olehermanse** [comment]
@cf-bottom jenkins again, please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7756/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7756/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7756/

**Pull request merged**
