### PR TITLE
ENT-4022: Fixed segfault in policy parser

### PR DESCRIPTION
**Pull request by olehermanse**
Found using AFL:
https://github.com/olehermanse/dotfiles/blob/6498b3872a803ce89c13033375dde655fb926dd6/cfengine/fuzz.sh

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom Let's test this in jenkins, even on exotics!

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2200/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2200/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2200/

**Comment by olehermanse** [comment]
Deployment test failure seems unrelated.

**Comment by olehermanse** [comment]
Confirmed fix in the generated packages.

**Pull request merged**
