### PR TITLE
CFE-2857: Fix reloading persistent classes on config reload

### PR DESCRIPTION
**Pull request by nickanderson**
Changelog: Title

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1577/)

https://ci.cfengine.com/job/pr-pipeline/1577/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1581/)

https://ci.cfengine.com/job/pr-pipeline/1581/

**Comment by olehermanse** [comment]
Closing this in favor of: https://github.com/cfengine/core/pull/3396

**Pull request closed without merging**
