### PR TITLE
ENT-9685: Enabled install-time selinux policy compiling

### PR DESCRIPTION
**Pull request by craigcomstock**
by installing the .te and .fc files as well as the build .pp file

buildscripts repo will need install scripts changes to take advantage of this change.

Ticket: ENT-9685
Changelog: title

https://github.com/cfengine/core/pull/5146
https://github.com/cfengine/buildscripts/pull/1187

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @vpodzime can review this?

**Review by vpodzime — COMMENTED** [review]
install-time policy compilation would require the tools from the `selinux-devel` package on the host, right?

**Comment by craigcomstock** [comment]
> install-time policy compilation would require the tools from the `selinux-devel` package on the host, right?

Absolutely. I was thinking we could bomb out at that stage with a message saying: "You must install selinux-devel and re-try the install/upgrade".

**Comment by craigcomstock** [comment]
try [Build Status](https://ci.cfengine.com/job/pr-pipeline/9134/)

**Comment by craigcomstock** [comment]
oops, forgot I needed to do `+=` on the `selinux_DATA` lines in `Makefile.am`

try again: [Build Status](https://ci.cfengine.com/job/pr-pipeline/9135/)

**Comment by craigcomstock** [comment]
With this green build above, trying to install the hub package on an un-upgraded rhel-9 hub I get:

```
[root@rhel9 ~]# rpm -i cfengine-nova-hub-3.22.0a.5be81e70d-24799.el9.x86_64.rpm
A previous version of CFEngine Mission Portal was found,
creating a backup of it at /tmp/cfengine-htdocs.tar.gz
Purging old version from /var/cfengine/httpd/htdocs
Keeping only what's listed in preserve_during_upgrade.txt file
libsemanage.semanage_pipe_data: Child process /usr/libexec/selinux/hll/pp failed with code: 255. (No such file or directory).
cfengine-enterprise: libsepol.policydb_read: policydb module version 21 does not match my version range 4-20
cfengine-enterprise: libsepol.sepol_module_package_read: invalid module in module package (at section 0)
cfengine-enterprise: Failed to read policy package
libsemanage.semanage_direct_commit: Failed to compile hll files into cil files.
 (No such file or directory).
```

Considering the output there I think the "examine /var/log/CFE*log" is not really needed since all the information is coming out during the install command.

**Comment by craigcomstock** [comment]
This strategy of failing in postinstall I think is wrong. It's already too late. When I try to follow my instructions from the previous message here I get another failure, presumably because the install is already "done" and in an odd state.

So. I will try inserting the cfengine-enterprise selinux module during preinstall instead, and error out quickly with a similar message of "install selinux-policy-devel  package and retry" and see how that goes.

**Comment by craigcomstock** [comment]
Best I can figure, the kernel package will define the policydb version, but maybe also the build of selinux tools as well. So I will see if keeping the failure in postinstall script but not `exit 1` and instead let other things happen anyway and hope that re-building selinux policy locally and restarting cfengine3 umbrella service will put things right.

**Comment by craigcomstock** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/9136/)

**Comment by vpodzime** [comment]
I still think the cleanest solution is to add a proper dependency on the required `policydb` version.

**Comment by craigcomstock** [comment]
@cf-bottom how about a build?

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9141/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9141/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9141/

**Comment by craigcomstock** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/9144/)

**Comment by craigcomstock** [comment]
cherry picked
3.18.x https://github.com/cfengine/core/pull/5161
3.21.x https://github.com/cfengine/core/pull/5160

**Pull request merged**
