### PR TITLE
ENT-3806: Masterfiles stage readme was changed.

### PR DESCRIPTION
**Pull request by aleksandrychev**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @vpodzime can review this?

**Comment by olehermanse** [comment]
Maybe our org-mode expert @nickanderson can review this? :)

**Comment by aleksandrychev** [comment]
@nickanderson  please review

**Comment by nickanderson** [comment]
I merged this, then I reverted it because the doc changes should be made in the same PR as any actual code changes. Has the tooling already been updated?

**Comment by aleksandrychev** [comment]
>Has the tooling already been updated?

Nope, I hope these days it should be merged.

**Comment by nickanderson** [comment]
@Lex-2008 When you make the updates to the scripts, can you please tie this documentation change in with it? I don't want to merge this unless the tools are actually updated as well.

**Comment by Lex-2008** [comment]
Yup, I will, but after workshop

**Pull request merged**
