### PR TITLE
Upgraded contrib-vagrant to centos-7

### PR DESCRIPTION
**Pull request by craigcomstock**
CentOS 6 is EOL November 30th, 2020.
The main repositories are moved to https://vault.centos.org/centos/6.10/

Ticket: none
Changelog: none

### CODE REVIEW

**Review by vpodzime — APPROVED** [review]
Looks good to me.

**Comment by craigcomstock** [comment]
There are some errors during provisioning and I forgot to fixup configure.ac (done now).

**Comment by craigcomstock** [comment]
and the reason I did this in the first place: 

```
The box 'centos/6' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/centos/6"]
Error: The requested URL returned error: 404 Not Found
```

**Comment by craigcomstock** [comment]
@vpodzime looks like the errors I saw (red text) were really just yum update working through some things (like updating keys and such). no-deps-build is working fine now.

Am running both vm-check and vm-check-full now just to be sure it all works and hopefully passes tests. :)

**Comment by vpodzime** [comment]
> @vpodzime looks like the errors I saw (red text) were really just yum update working through some things (like updating keys and such). no-deps-build is working fine now.

Yeah, the stderr output from `vagrant up` and `vagrant provision` is in red.

**Review by vpodzime — APPROVED** [review]
ACK

**Review by vpodzime — COMMENTED** [review]
Please squash the commits. Looks good to me otherwise.

**Comment by craigcomstock** [comment]
@vpodzime ran full-build with these changes and all tests passed! :+1: 

```
    full-build: Testsuite finished at 2020-12-29 20:35:37 (843 seconds)
    full-build:                                                        
    full-build: Passed tests:  40                                      
    full-build: Failed tests:  0                                       
    full-build: Skipped tests: 5                                       
    full-build: Soft failures: 2                                       
    full-build: Total tests:   47     
```

:tada: :pizza:

**Review by vpodzime — APPROVED** [review]
Nice! Thanks!

**Comment by craigcomstock** [comment]
No need to cherry-pick. I checked and contrib-vagrant-ci is not present in 3.15.x. So only in master and done. :)

**Pull request merged**
