### PR TITLE
CFE-3639: Moved litem logic to ParserHandleListItem function

### PR DESCRIPTION
**Pull request by KotzaBoss**
Ticket: CFE-3639
Changelog: None

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6843/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6843/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6843/

**Comment by KotzaBoss** [comment]
Summary:
- Grep is affected by the un-expansion of the ints.
- Filter is not.
- Multiplication with eval is not.
```
bundle agent ints_in_commands
{
  vars:
    # With or without quotes should be the same:
    "mylist"
        ilist => {"56k", 56k};

  commands:
    # What should happen when an ilist element is expanded into a string
    "/usr/bin/grep -m $(mylist) cf testfile"
        inform => "true";

    # I think, ideally, this should be:
    "/usr/bin/grep -m 5600 cf testfile";
}
```
Output:
```
    info: Executing 'no timeout' ... '/usr/bin/grep -m 56k cf testfile'
   error: Finished command related to promiser '/usr/bin/grep -m 56k cf testfile' -- an error occurred, returned 2
  notice: Q: "...r/bin/grep -m 5": /usr/bin/grep: invalid max count
    info: Last 1 quoted lines were generated by promiser '/usr/bin/grep -m 56k cf testfile'
    info: Completed execution of '/usr/bin/grep -m 56k cf testfile'
    info: Executing 'no timeout' ... '/usr/bin/grep -m 5600 cf testfile'
  notice: Q: "...r/bin/grep -m 5": cf
Q: "...r/bin/grep -m 5": cf
Q: "...r/bin/grep -m 5": cf
Q: "...r/bin/grep -m 5": cf
Q: "...r/bin/grep -m 5": cf
Q: "...r/bin/grep -m 5": cf
Q: "...r/bin/grep -m 5": cf
Q: "...r/bin/grep -m 5": cf
Q: "...r/bin/grep -m 5": cf
Q: "...r/bin/grep -m 5": cf
    info: Last 10 quoted lines were generated by promiser '/usr/bin/grep -m 5600 cf testfile'
    info: Completed execution of '/usr/bin/grep -m 5600 cf testfile'
```
---
```
bundle agent ints_in_function_calls
{
  vars:
    # With or without quotes should be the same:
    "src1"
        ilist => {"1k", 1k};  # naked numbers work only for ints
    "src2"
        ilist => {2k, "2k"};

    "filtered_from_list"
        slist => filter(".*", src1, true, false, "${src1}"); # Should return max 1000
    "filtered_from_hard_int"
        slist => filter(".*", src2, true, false, "2k"); # Should return max 1000

  reports:
    "${with}" with => join(" ", @{filtered_from_list});
    "${with}" with => join(" ", @{filtered_from_hard_int});
}
```
Output:
```
R: 1k 1k
R: 2k 2k
```
---
```
bundle agent multiplying_floats
{
  vars:
    # naked reals not working currently
    "myarray[0]" rlist => { "0.0000003" };
    "myarray[1]" rlist => { "2.0" };
    "myarray[2]" rlist => { "10000.0k" };

    "product_from_lists"
      string => eval("($(myarray[0]) * $(myarray[1])) * $(myarray[2])");
    "product_from_hard_nums"
      string => eval("(0.0000003 * 2.0) * 10000.0k");

  reports:
    "expected 6.000000 got $(product_from_lists) from product_from_lists"; # Should print 6.0 or something
    "expected 6.000000 got $(product_from_hard_nums) from product_from_hard_nums"; # Should print 6.0 or something
}
```
Output
```
R: expected 6.000000 got 6.000000 from product_from_lists
R: expected 6.000000 got 6.000000 from product_from_hard_nums
```

**Comment by olehermanse** [comment]
@KotzaBoss Thanks for testing and summarizing. Since this PR is just a small refactoring, I don't think this is the right place to post it though, maybe you can put it in your JIRA ticket, instead?

**Comment by KotzaBoss** [comment]
@olehermanse moved test results to jira [ticket](https://tracker.mender.io/browse/CFE-3639)

**Review by olehermanse — APPROVED** [review]

**Pull request merged**
