### PR TITLE
CFE-3471: Extensive test of or() function

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
Waiting for: https://github.com/cfengine/core/pull/4370

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5860/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5860/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5860/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5861/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5861/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5861/

**Review by vpodzime — APPROVED** [review]
ACK

**Comment by olehermanse** [comment]
Cherry-picks:
https://github.com/cfengine/core/pull/4376
https://github.com/cfengine/core/pull/4377

**Pull request merged**
