### PR TITLE
ENT-8817: Use the current namespace as the default in ExpandDeRefPromise()

### PR DESCRIPTION
**Pull request by vpodzime**
So that bundle-qualified references of the form "$(bundle.var)"
resolve to values of variables from the particular bundle from
the current namespace.

Ticket: ENT-8817
Changelog: Bundle-qualified references (of the form
"$(bundle.var)") now properly resolve to variables from bundles
from the current namespace

Merge together:
https://github.com/cfengine/core/pull/4994
https://github.com/cfengine/masterfiles/pull/2435

### CODE REVIEW

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8318/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8318/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8318/

**Comment by vpodzime** [comment]
> [vpodzime](/vpodzime) [force-pushed](/cfengine/core/compare/846f3f9aa197958da58581766121af0d013c05ee..882192708d9c6659a428108da578c10ff6d4bfa2) the master-expand_current_ns branch from [ `846f3f9` ](/cfengine/core/commit/846f3f9aa197958da58581766121af0d013c05ee) to [ `8821927` ](/cfengine/core/commit/882192708d9c6659a428108da578c10ff6d4bfa2)

Just moved the tests into a new directory with a proper name.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8319/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8319/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8319/

**Review by olehermanse — DISMISSED** [review]
Cool, looks good to me! 🚀 (Just make sure tests pass)

**Comment by vpodzime** [comment]
> Cool, looks good to me! rocket (Just make sure tests pass)

Yeah, that's the tricky part. :sweat_smile:

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8341/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8341/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8341/

**Review by olehermanse — APPROVED** [review]

**Comment by vpodzime** [comment]
This actually revealed a bug in our *federation.cf* policy file: https://github.com/cfengine/masterfiles/pull/2435

**Comment by vpodzime** [comment]
@cf-bottom let's try it in jenkins again, now with the related fix in MPF.

**Pull request merged**
