### PR TITLE
CFE-951: Change the default for 'rxdirs'

### PR DESCRIPTION
**Pull request by vpodzime**

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7642/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7642/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7642/

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7648/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7648/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7648/

**Review by nickanderson — DISMISSED** [review]

**Comment by nickanderson** [comment]
@vpodzime https://github.com/cfengine/documentation/pull/2652

**Review by larsewi — DISMISSED** [review]
ACK

**Review by larsewi — APPROVED** [review]
RE-ACK

**Pull request merged**
