### PR TITLE
Redmine #7400: Don't limit CSV line length to 4096 bytes.

### PR DESCRIPTION
**Pull request by kacfengine**

### CODE REVIEW

**Comment by kacfengine** [comment]
Depends on https://github.com/cfengine/enterprise/pull/280 and https://github.com/cfengine/nova/pull/938.

Being tested here: http://jenkins.usdc.cfengine.com/view/Enterprise%20private%20branches/job/testing-kristian-privateBranch/55/

**Comment by kacfengine** [comment]
I made an error in the Jenkins setup, being tested again here: http://jenkins.usdc.cfengine.com/view/Enterprise%20private%20branches/job/testing-kristian-privateBranch/56/

**Comment by jimis** [comment]
+1

**Comment by kacfengine** [comment]
Tests are green (except for some unrelated details).

**Comment by maciejmrowiec** [comment]
Added comments in the ticket.

**Pull request merged**
