### PR TITLE
CFE-2950: Moved files functions to libutils

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1705/)

https://ci.cfengine.com/job/pr-pipeline/1705/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1706/)

https://ci.cfengine.com/job/pr-pipeline/1706/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1707/)

https://ci.cfengine.com/job/pr-pipeline/1707/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1711/)

https://ci.cfengine.com/job/pr-pipeline/1711/

**Comment by olehermanse** [comment]
Replaced by https://github.com/cfengine/core/pull/3449

**Pull request closed without merging**
