### PR TITLE
make mail_exclude_filter test more verbose - 3.12.x

### PR DESCRIPTION
**Pull request by Lex-2008**

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom can you build it, please?

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4030/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4030/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4030/

**Comment by Lex-2008** [comment]
commit message amended!

**Comment by Lex-2008** [comment]
looks like this is not needed anymore

**Pull request closed without merging**
