### PR TITLE
ENT-4885: Replaced libutils and libcompat with libntech submodule

### PR DESCRIPTION
**Pull request by olehermanse**
Merge together: 
https://github.com/cfengine/core/pull/3783
https://github.com/cfengine/enterprise/pull/541
https://github.com/cfengine/nova/pull/1502

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2521/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2521/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2521/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2524/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2524/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2524/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2525/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2525/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2525/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2526/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2526/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2526/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2527/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2527/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2527/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2528/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2528/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2528/

**Comment by olehermanse** [comment]
@cf-bottom one more jenkins build, with exotics, please :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2529/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2529/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2529/

**Comment by olehermanse** [comment]
@cf-bottom jenkins with exotics, one more time, please :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2530/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2530/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2530/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2531/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2531/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2531/

**Comment by olehermanse** [comment]
@cf-bottom jenkins with exotics, again please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2535/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2535/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2535/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2536/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2536/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2536/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2537/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2537/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2537/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2538/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2538/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2538/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2541/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2541/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2541/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2542/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2542/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2542/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2543/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2543/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2543/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2544/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2544/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2544/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2582/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2582/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2582/

**Comment by olehermanse** [comment]
@cf-bottom one more jenkins build, with exotics :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2583/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2583/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2583/

**Pull request merged**
