### PR TITLE
CFE-2886: Updated verify_services to use Attributes *

### PR DESCRIPTION
**Pull request by olehermanse**
Reported by LGTM:
https://lgtm.com/rules/2163210742/

Merge together:
https://github.com/cfengine/core/pull/3298
https://github.com/cfengine/enterprise/pull/436

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1272/)

https://ci.cfengine.com/job/pr-pipeline/1272/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1274/)

https://ci.cfengine.com/job/pr-pipeline/1274/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1276/)

https://ci.cfengine.com/job/pr-pipeline/1276/

**Pull request merged**
