### PR TITLE
CFE-2886: Changed functions in several files to use Attributes *

### PR DESCRIPTION
**Pull request by olehermanse**
Merge together:
https://github.com/cfengine/core/pull/3304
https://github.com/cfengine/enterprise/pull/438

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1298/)

https://ci.cfengine.com/job/pr-pipeline/1298/

**Comment by olehermanse** [comment]
This pull request **introduces 1 alert** when merging 211289090b7489f7a04fb6f7d3a66d6ceca40120 into cd46c45125b394af549cdca90d862da1aae4b40c - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-c274bb38fd82cc57a74da8fe055dec3b097ee534)

**new alerts:**

* 1 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1302/)

https://ci.cfengine.com/job/pr-pipeline/1302/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1303/)

https://ci.cfengine.com/job/pr-pipeline/1303/

**Comment by olehermanse** [comment]
This pull request **introduces 1 alert** when merging 6e2a5a5a2d234422651866262c729f90ca35a03b into cd46c45125b394af549cdca90d862da1aae4b40c - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-1f36e482e4b2087d3830cfe218ab77e74a6d14c6)

**new alerts:**

* 1 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1304/)

https://ci.cfengine.com/job/pr-pipeline/1304/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1306/)

https://ci.cfengine.com/job/pr-pipeline/1306/

**Comment by olehermanse** [comment]
This pull request **introduces 1 alert** when merging 174ff4268de64071c366e0dffe148f9e99749f83 into d6c2a8e04ea2b42c038ffd34cb296eb704607bba - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-d071a3e30c97da65cc4b5951121006267e0aedb1)

**new alerts:**

* 1 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1307/)

https://ci.cfengine.com/job/pr-pipeline/1307/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1308/)

https://ci.cfengine.com/job/pr-pipeline/1308/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1309/)

https://ci.cfengine.com/job/pr-pipeline/1309/

**Comment by olehermanse** [comment]
This pull request **introduces 1 alert** when merging c588174e788aa1c6ae213c5e01976e464299f3fb into d6c2a8e04ea2b42c038ffd34cb296eb704607bba - [view on LGTM.com](https://lgtm.com/projects/g/cfengine/core/rev/pr-5447b28bbdfb650fb84885084559b739e944fb7c)

**new alerts:**

* 1 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1310/)

https://ci.cfengine.com/job/pr-pipeline/1310/

**Pull request merged**
