### PR TITLE
Add: Tests to make sure we don't define containers based on invalid data

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
These test are all passing on 3.7.1, just looking to improve test coverage.

```
R: test description: Test that data containers are NOT defined when mergedata is used with a non-existing data container
R: /home/nickanderson/CFEngine/core2.git/tests/acceptance/01_vars/04_containers/./mergedata_with_unresolved_variables_does_not_define_datacontainer.cf Pass
R: test description: Test that a data container defined by using parsejson(storejson()) against a non existing data container will not define a new data container.
R: DEBUG init: serialized_data: '$(serialized_data)'
R: /home/nickanderson/CFEngine/core2.git/tests/acceptance/01_vars/04_containers/./parsejson_storejson_with_missing_container_does_not_create_new_container.cf Pass
R: test description: Test that data containers defined with parsejson that conatains unexpanded variables does NOT define a new datacontainer
R: /home/nickanderson/CFEngine/core2.git/tests/acceptance/01_vars/04_containers/./parsejson_with_unresolved_varibales_does_not_define_datacontainer.cf Pass
```

**Comment by jimis** [comment]
+1 more tests yeah

**Comment by jimis** [comment]
trigger build

**Comment by nickanderson** [comment]
trigger_build

**Comment by jimis** [comment]
Argh Ubuntu 12.04 [failed](http://jenkins.usdc.cfengine.com/view/Pull%20requests/job/testing-enterprise-pr_core/249/label=PACKAGES_x86_64_linux_ubuntu_12/testReport/junit/._00_basics_ifelapsed_and_expireafter_timed_defaults/cf/defaults_cf/) at test `./00_basics/ifelapsed_and_expireafter/timed/defaults.cf.defaults.cf`. This has nothing to do with the pull request, so I'll ignore the failure and merge.

@kacfengine I think you are the only one that understands that test, any ideas how to make it more resilient?

**Comment by jimis** [comment]
HP-UX still building as usual, but everything else is green (besides the spurious unrelated error mentioned above). 

I'm merging; what can go wrong?

**Pull request merged**
