### PR TITLE
CFE-3021: Added example promise for classfiltercsv

### PR DESCRIPTION
**Pull request by karlhto**
Shows how classes are ignored if they are not defined, as well
as that you are able to sort and use a header column. I will add
clearer definitions in the documentation entry for the function.

Ticket: CFE-3021
Changelog: None

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @olehermanse can review this?

**Comment by karlhto** [comment]
@cf-bottom jenkins with exotics, please.

@nickanderson Please review, don't know if `unix2dos` is the right way to solve the fact that we need to take CRLF line endings.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2310/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2310/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2310/

**Comment by nickanderson** [comment]
> @nickanderson Please review, don't know if `unix2dos` is the right way to solve the fact that we need to take CRLF line endings.

If you can't generate the file with the proper line endings in the prep section, maybe just check in a csv with the proper line endings to start with and use that file directly, perhaps as $(this.promise_filename).csv. Also I might use printfile => cat() to show the content of the csv before filtering.

**Pull request merged**
