### PR TITLE
ENT-5553: Added valgrind test using Ubuntu 20 container (3.15)

### PR DESCRIPTION
**Pull request by olehermanse**
Adapted from the Travis test. Community only for now,
enterprise will require some extra work.

Conflicts:

Related to static-check which is missing on 3.15.x

(cherry picked from commit 58ce156b766c5492ff8b4763c9b096abe543962c)

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom please start a jenkins build

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5569/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5569/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5569/

**Review by vpodzime — APPROVED** [review]
Looks good to me. There is a failure, but at least the checks are now running.

**Comment by olehermanse** [comment]
> Looks good to me. There is a failure, but at least the checks are now running.

I'll consider this PR successful, merge it and keep working on making it green.

**Pull request merged**
