### PR TITLE
CFE-3472: Replaced ifvarclass with if in examples

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Review by vpodzime — APPROVED** [review]
ACK

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5858/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5858/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5858/

**Comment by olehermanse** [comment]
Looks green enough, aborting build to save some time / resources.

**Pull request merged**
