### PR TITLE
Use StringMatchesOption() from libntech

### PR DESCRIPTION
**Pull request by olehermanse**
Also fixed a bunch of includes in libntech and core.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom: Test this in jenkins, with exotics, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/3009/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/3009/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-3009/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/3010/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/3010/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-3010/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/3013/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/3013/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-3013/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/3014/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/3014/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-3014/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/3016/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/3016/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-3016/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/3021/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/3021/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-3021/

**Comment by olehermanse** [comment]
@cf-bottom: Test this in jenkins, with exotics, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/3022/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/3022/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-3022/

**Comment by olehermanse** [comment]
@cf-bottom one more time in jenkins please, with exotics.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/3027/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/3027/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-3027/

**Comment by olehermanse** [comment]
@cf-bottom test this in jenkins again, with exotics.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/3030/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/3030/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-3030/

**Pull request merged**
