### PR TITLE
ENT-10699: Improve and re-enable windows acceptance test workflow (3.18)

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-10699
Changelog: none
(cherry picked from commit da214fa9593576926f11b553524958bc6680fee3)

 Conflicts:
	.github/workflows/ci.yml
	.github/workflows/windows_acceptance_tests.yml

Enabling windows acceptance test in 3.18.x but had to replace version in cf-remote install command.
Uses latest nightly.

### CODE REVIEW

**Comment by craigcomstock** [comment]
@larsewi @olehermanse is this PR, https://github.com/cfengine/core/pull/5497, fixing macos libtools/autotools business?

Ah, I see 3.21.x is done: https://github.com/cfengine/core/pull/5500 will we also do 3.18.x then?

**Comment by craigcomstock** [comment]
In order for this to succeed we will need to wait for tonight's nightly 3.18.x build which should include cf_secret.exe. I just merged a fix there for ENT-10405: https://github.com/cfengine/buildscripts/pull/1413

**Comment by craigcomstock** [comment]
retrying https://github.com/cfengine/core/actions/runs/9023029399

if green I will squash and revert changes I made to focus on only one job and ready for review/merge.

**Review by larsewi — APPROVED** [review]

**Comment by craigcomstock** [comment]
Well... I thought I might get lucky but apparently not

```
Failed tests:    136
```

Maybe more bits we didn't cherry pick back. :(

I will make a separate PR then for the non-windows related changes and let this one sit for a bit.

**Comment by craigcomstock** [comment]
will back-burner this PR and leave it as a branch to pick in ENT-11771

picked out the macos test fixes into https://github.com/cfengine/core/pull/5507

**Pull request closed without merging**
