### PR TITLE
Add: Tests for mustache not rendering with invalid data

### PR DESCRIPTION
**Pull request by nickanderson**
Ref: https://dev.cfengine.com/issues/7699

### CODE REVIEW

**Comment by nickanderson** [comment]
Please note there is potentially some debate on this behaviour. I know that @tzz was thinking that the existing behaviour should be preserved and this could be solved by some template extensions like {{var:/REJECT}} or something.

I am going to work on another set of tests that looks at how its falling back to datastate(), which is probably very related to this undesired behaviour.

@worr was talking about similar stuff recently as well.

**Comment by nickanderson** [comment]
Oh and test output:

```
R: test description: Test that a mustache template does not try to render when its given an invalid container directly
R: /home/nickanderson/CFEngine/core2.git/tests/acceptance/./10_files/templating/../../dcs.cf.sub SFAIL/redmine7699
    info: Deleted file '/tmp/TEST.cfengine'
    info: Created file '/tmp/TEST.cfengine', mode 0600
    info: Updated rendering of '/tmp/TEST.cfengine' from template mustache template '/home/nickanderson/CFEngine/core2.git/tests/acceptance/./10_files/templating/mustache_does_not_try_to_render_when_provided_datacontainer_via_direct_data_is_undefined.cf.mustache'
R: test: Found class 'template_render_with_non_existing_data_container_kept'
R: test: Found class 'template_render_with_non_existing_data_container_not_repaired'
R: test: Found class 'template_render_with_non_existing_data_container_repaired'
R: test: Found class 'template_render_with_non_existing_data_container_reached'
R: test: Found class 'template_render_with_non_existing_data_container_ok'
R: DEBUG check: Found 'template_render_with_non_existing_data_container_kept' that should not have been found
R: DEBUG check: Found 'template_render_with_non_existing_data_container_not_repaired' that should not have been found
R: DEBUG check: Found 'template_render_with_non_existing_data_container_repaired' that should not have been found
R: DEBUG check: Found 'template_render_with_non_existing_data_container_reached' that should not have been found
R: DEBUG check: Found 'template_render_with_non_existing_data_container_ok' that should not have been found
R: DEBUG check: Found the content of /tmp/TEST.cfengine was not as expected
R: /home/nickanderson/CFEngine/core2.git/tests/acceptance/./10_files/templating/mustache_does_not_try_to_render_when_provided_datacontainer_via_direct_data_is_undefined.cf FAIL
R: test description: Test that a mustache template does not try to render when its given an invalid container via mergedata
R: /home/nickanderson/CFEngine/core2.git/tests/acceptance/./10_files/templating/../../dcs.cf.sub SFAIL/redmine7699
    info: Deleted file '/tmp/TEST.cfengine'
    info: Created file '/tmp/TEST.cfengine', mode 0600
    info: Updated rendering of '/tmp/TEST.cfengine' from template mustache template '/home/nickanderson/CFEngine/core2.git/tests/acceptance/./10_files/templating/mustache_does_not_try_to_render_when_provided_datacontainer_via_mergedata_is_undefined.cf.mustache'
R: test: Found class 'template_render_with_non_existing_data_container_kept'
R: test: Found class 'template_render_with_non_existing_data_container_not_repaired'
R: test: Found class 'template_render_with_non_existing_data_container_repaired'
R: test: Found class 'template_render_with_non_existing_data_container_reached'
R: test: Found class 'template_render_with_non_existing_data_container_ok'
R: DEBUG check: Found 'template_render_with_non_existing_data_container_kept' that should not have been found
R: DEBUG check: Found 'template_render_with_non_existing_data_container_not_repaired' that should not have been found
R: DEBUG check: Found 'template_render_with_non_existing_data_container_repaired' that should not have been found
R: DEBUG check: Found 'template_render_with_non_existing_data_container_reached' that should not have been found
R: DEBUG check: Found 'template_render_with_non_existing_data_container_ok' that should not have been found
R: DEBUG check: Found the content of /tmp/TEST.cfengine was not as expected
R: /home/nickanderson/CFEngine/core2.git/tests/acceptance/./10_files/templating/mustache_does_not_try_to_render_when_provided_datacontainer_via_mergedata_is_undefined.cf FAIL
R: test description: Test that a mustache template does not try to render when its given an invalid container via parsejson(storejson())
R: /home/nickanderson/CFEngine/core2.git/tests/acceptance/./10_files/templating/../../dcs.cf.sub SFAIL/redmine7699
    info: Deleted file '/tmp/TEST.cfengine'
    info: Created file '/tmp/TEST.cfengine', mode 0600
    info: Updated rendering of '/tmp/TEST.cfengine' from template mustache template '/home/nickanderson/CFEngine/core2.git/tests/acceptance/./10_files/templating/mustache_does_not_try_to_render_when_provided_datacontainer_via_parsejson_storejson_is_undefined.cf.mustache'
R: test: Found class 'template_render_with_non_existing_data_container_kept'
R: test: Found class 'template_render_with_non_existing_data_container_not_repaired'
R: test: Found class 'template_render_with_non_existing_data_container_repaired'
R: test: Found class 'template_render_with_non_existing_data_container_reached'
R: test: Found class 'template_render_with_non_existing_data_container_ok'
R: DEBUG check: Found 'template_render_with_non_existing_data_container_kept' that should not have been found
R: DEBUG check: Found 'template_render_with_non_existing_data_container_not_repaired' that should not have been found
R: DEBUG check: Found 'template_render_with_non_existing_data_container_repaired' that should not have been found
R: DEBUG check: Found 'template_render_with_non_existing_data_container_reached' that should not have been found
R: DEBUG check: Found 'template_render_with_non_existing_data_container_ok' that should not have been found
R: DEBUG check: Found the content of /tmp/TEST.cfengine was not as expected
R: /home/nickanderson/CFEngine/core2.git/tests/acceptance/./10_files/templating/mustache_does_not_try_to_render_when_provided_datacontainer_via_parsejson_storejson_is_undefined.cf FAIL


```

**Comment by jimis** [comment]
Merging because @nickanderson is standing over my shoulder but it can change later depending on what he and @tzz figure out.

**Comment by tzz** [comment]
@nickanderson @jimis for reference, my proposal (which doesn't block and isn't blocked by this test) is in https://dev.cfengine.com/issues/7684#note-1

**Pull request merged**
