### PR TITLE
Failsafe key generation redmine7167

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
@nickanderson please review the changes in `failsafe.cf`

**Comment by jimis** [comment]
I get three test failures in my personal workstation, but it's unrelated to this (related to yaml support not being compiled-in, see [redmine#6180](https://dev.cfengine.com/issues/6180).

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
jenkins gave the green light!

**Comment by kacfengine** [comment]
Looks alright to me, but indeed should ask @pasinskim about the ``CheckAndSetHAState()`` call.

**Comment by pasinskim** [comment]
It shoud be OK with the HA stuff as well.

**Pull request merged**
