### PR TITLE
Update install-masterfiles-stage.sh

### PR DESCRIPTION
**Pull request by mgrothermel**
Fixed a couple of typos that affect ownership and permissions

### CODE REVIEW

**Review by craigcomstock — APPROVED** [review]
Ah, Thanks! My typos! :O

**Comment by nickanderson** [comment]
Thanks!

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9488/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9488/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9488/

**Review by vpodzime — APPROVED** [review]
Any chance we could shellcheck those files? Thanks for the fixes!

**Comment by craigcomstock** [comment]
> Any chance we could shellcheck those files? Thanks for the fixes!

Am checking now. We already use shellcheck on misc/cf-support so maybe we can add it to this subdir.

**Comment by craigcomstock** [comment]
@mgrothermel @vpodzime the files already there have a number of issues with shellcheck. Maybe better to run manually for now and check that code you changed didn't introduce new issues with shellcheck. :)

**Comment by craigcomstock** [comment]
FWIW: here's the changes to add to automake bits: https://github.com/cfengine/core/pull/5246

**Pull request merged**
