### PR TITLE
Various cleanups of capitalization, whitespace, typos, utf-8 etc.

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please, I hope these don't break anything.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4729/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4729/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4729/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4731/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4731/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4731/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4734/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4734/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4734/

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4738/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4738/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4738/

**Comment by olehermanse** [comment]
Failures on Debian 9 / 10 unrelated. (Timed package manager related tests).

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4743/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4743/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4743/

**Pull request merged**
