### PR TITLE
CFE-3409: Fixed format truncation warnings

### PR DESCRIPTION
**Pull request by olehermanse**
Merge together:
https://github.com/cfengine/core/pull/4308
https://github.com/cfengine/enterprise/pull/631
https://github.com/cfengine/nova/pull/1710

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5591/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5591/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5591/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5592/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5592/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5592/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5593/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5593/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5593/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5594/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5594/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5594/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5595/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5595/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5595/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5596/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5596/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5596/

**Review by vpodzime — APPROVED** [review]
Looks good to me.

**Pull request merged**
