### PR TITLE
CFE-2627: Acceptance test

### PR DESCRIPTION
**Pull request by nickanderson**
Changelog: None

### CODE REVIEW

**Comment by jimis** [comment]
close?

**Comment by jimis** [comment]
@nickanderson either close or commit as softfail and update the ticket?

**Comment by jimis** [comment]
still red

**Comment by olehermanse** [comment]
ping @nickanderson

**Comment by nickanderson** [comment]
Ah, you can't soft-fail this kind of error.

```
./tests/acceptance/02_classes/02_functions/and_classes_attribute_accepts_not_function_result.cf:24:47: error: Function does not return the required type
     and => {  not( isvariable("nosuchvar") ) };
                                                                             ^
```
I will just close this, and note it in the ticket.

**Pull request closed without merging**
