### PR TITLE
ENT-4136: Fixed more memory leaks in unit tests

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1649/)

https://ci.cfengine.com/job/pr-pipeline/1649/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1651/)

https://ci.cfengine.com/job/pr-pipeline/1651/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1654/)

https://ci.cfengine.com/job/pr-pipeline/1654/

**Pull request merged**
