### PR TITLE
Fixed memory leak in users promises (3.15)

### PR DESCRIPTION
**Pull request by olehermanse**
Found by running valgrind agent run on a demo hub.

(cherry picked from commit 571d28089833675065f5a9e2df61805bf7cb76ba)

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5808/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5808/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5808/

**Comment by craigcomstock** [comment]
Shoot. My bad. Sorry about that one @olehermanse  :) Thanks for the catch.

**Comment by olehermanse** [comment]
> Shoot. My bad. Sorry about that one @olehermanse  :) Thanks for the catch.

@craigcomstock No worries, this is just a cherry-pick though, it was fixed here:

https://github.com/cfengine/core/pull/4331

**Pull request merged**
