### PR TITLE
Replace the last few remaining occurences of cf-keycrypt

### PR DESCRIPTION
**Pull request by vpodzime**
cf-keycrypt was renamed to cf-secret in cfengine/core@b93fce47cf.

### CODE REVIEW

**Comment by vpodzime** [comment]
`git grep -i 'cf[_-]keycrypt'` now gives nothing.

**Comment by vpodzime** [comment]
> Looks like you accidentally added some change to libntech. Please remove this.

Done.

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5216/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5216/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5216/

**Pull request merged**
