### PR TITLE
Bumped libntech submodule

### PR DESCRIPTION
**Pull request by olehermanse**
Brings libntech submodule up to date with upstream master.

No behavior changes, just cleanups, code style, tests, etc.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6002/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6002/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6002/

**Review by larsewi — APPROVED** [review]
Looks good to me !

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
