### PR TITLE
CFE-2512: Test that pre-eval doesnt emit errors for readfile()

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by jimis** [comment]
@nickanderson this pull request is a reminder to fix the real issue? Is that why Travis is failing?

**Comment by nickanderson** [comment]
Yes its a real issue: https://tracker.mender.io/browse/CFE-2512

I hadn't soft failed it, added.

**Comment by nickanderson** [comment]
@jimis no longer red.

**Comment by jimis** [comment]
Thanks @nickanderson, your commit was cherry-picked to #2802; closing.

**Pull request closed without merging**
