### PR TITLE
CFE-3006: Moved known_dirs to libutils - 3.10.x

### PR DESCRIPTION
**Pull request by karlhto**
Also moved some windows-only things out from `cf-windows-functions`. `known_dirs` should not depend on something that uses `libpromises`-specific things.

Ticket: CFE-3006
Changelog: None

Blocked by: #3580

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @vpodzime can review this?

**Comment by vpodzime** [comment]
@karlhto please resolve the conflicts

**Comment by olehermanse** [comment]
@karlhto FWIW, this is being done for cf-check, which exists in 3.12.x, not 3.10.x. So backporting to 3.10 might be unnecessary.

**Comment by karlhto** [comment]
@olehermanse Should I just close this?

**Pull request closed without merging**
