### PR TITLE
Added github action to compile core and run unit tests

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-9155
Changelog: none

### CODE REVIEW

**Comment by craigcomstock** [comment]
acceptance tests took 41 minutes and had two failures, kind of hard to read/parse through the log. I wonder if there is a test report generator/format we could use to make it easier to find the failed tests. I will do some research.

Searching for `FAIL` doesn't really work due to the way that results scroll in the Details link above. The console output isn't auto-scrolled to each instance and the text 'fail' is all over the place so hard to find the actual failures.

The two failures were:

```
R: /home/runner/work/core/core/tests/acceptance/./31_tickets/CFE-3987/1/test.cf FAIL
R: /home/runner/work/core/core/tests/acceptance/./31_tickets/CFE-3988/1/test.cf FAIL
```

**Review by olehermanse — APPROVED** [review]
Looks good to me, thanks! Feel free to merge once you see it green.

**Comment by craigcomstock** [comment]
cherry picked to 3.15.x https://github.com/cfengine/core/pull/5052
and 3.18.x https://github.com/cfengine/core/pull/5053

**Comment by larsewi** [comment]
Awesome!

**Pull request merged**
