### PR TITLE
Code quality cherry-picks (3.12)

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1123/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1123/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1129/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1129/

**Comment by olehermanse** [comment]
The errors look unrelated. Merging.

**Pull request merged**
