### PR TITLE
Changed python version check in promise module tests

### PR DESCRIPTION
**Pull request by olehermanse**
This allows us to change to version 3.5 more easily soon.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6685/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6685/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6685/

**Review by vpodzime — APPROVED** [review]
ACK

**Review by tranchitella — APPROVED** [review]

**Review by larsewi — APPROVED** [review]
ACK

**Pull request merged**
