### PR TITLE
ENT-5528/3.12.x: Fixed service status cfengine3 on systemd managed hosts

### PR DESCRIPTION
**Pull request by nickanderson**
----

#

### CODE REVIEW

**Comment by nickanderson** [comment]
cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5008/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5008/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5008/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, with exotics, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5042/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5042/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5042/

**Comment by nickanderson** [comment]
@Lex-2008 can you review this and approve if that failure on aix is OK, seems to be totally unrelated.

**Pull request merged**
