### PR TITLE
Try enabling tests with osx on travis

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
@tzz ¯\_(ツ)_/¯

**Comment by tzz** [comment]
YES

**Comment by nickanderson** [comment]
@olehermanse I added osx here but it doesnt seem like it ran the tests on osx or am I just missing something obvious?

**Comment by olehermanse** [comment]
https://github.com/cfengine/core/pull/2770

I have this on hold at the moment. In my PR the tests run, but it hangs after unit tests complete.

**Comment by nickanderson** [comment]
Closing as @olehermanse has other PRs related to this he is workingon.

**Pull request closed without merging**
